/**
 * Textes de la fenêtre d'amis et du bouton « Ajouter en ami » (EN / FR / AR).
 * L'anglais sert de repli, comme partout sur le site.
 */
export const friendsCopy = {
  en: {
    launcher: 'FRIENDS',
    launcherOpen: 'Open the friends list',
    launcherClose: 'Close the friends list',
    online: 'online',
    onlineShort: 'ONLINE',
    offlineShort: 'OFFLINE',
    title: 'FRIENDS',
    subtitle: '{online} online · {total} friends',
    close: 'Close',
    refresh: 'Refresh',
    tabFriends: 'Friends',
    tabRequests: 'Requests',
    tabAdd: 'Add',
    sectionOnline: 'ONLINE',
    sectionOffline: 'OFFLINE',
    sectionReceived: 'RECEIVED',
    sectionSent: 'SENT',
    lastSeen: 'Seen {when}',
    level: 'LVL {level}',
    emptyFriends: 'No friends yet — find players in the Add tab, or send a request from any player profile.',
    emptyOnline: 'None of your friends are online right now.',
    emptyRequests: 'No pending requests.',
    emptySent: 'No request sent.',
    viewProfile: 'View profile',
    profileShort: 'Profile',
    accept: 'Accept',
    decline: 'Decline',
    cancelRequest: 'Cancel',
    remove: 'Remove',
    removeConfirm: 'Remove {name} from your friends?',
    add: 'Add friend',
    addShort: 'Add',
    sent: 'Request sent',
    pendingYou: 'Wants to be your friend',
    friends: 'Friends',
    you: 'You',
    searchLabel: 'Find a player',
    searchPlaceholder: 'Gamertag…',
    searchHint: 'Type at least 2 characters of a gamertag.',
    searching: 'Searching…',
    noResults: 'No player found for “{query}”.',
    loading: 'Loading your friends…',
    signInPrompt: 'Sign in to add friends',
    demoNote: 'Demo preview — simulated community, saved on this device only.',
    demoTarget: 'Demo profiles can only add players from the demo community.',
    realTarget: 'This is a demo profile — it cannot receive friend requests.',
    unavailable: 'Friends are not enabled on this deployment yet: run supabase/schema.sql (friendships table) on the Supabase project, then reload.',
    errGeneric: 'Something went wrong. Please try again.',
    errNetwork: 'Unable to reach the server — check your connection and try again.',
    errSignedOut: 'Your session has expired — sign in again.',
    hubTitle: 'MY FRIENDS',
    hubStats: '{friends} friends · {online} online · {pending} pending requests',
    hubSeeAll: 'See all my friends ({n})',
    hubSeeLess: 'Show less',
  },
  fr: {
    launcher: 'AMIS',
    launcherOpen: 'Ouvrir la liste d’amis',
    launcherClose: 'Fermer la liste d’amis',
    online: 'en ligne',
    onlineShort: 'EN LIGNE',
    offlineShort: 'HORS LIGNE',
    title: 'AMIS',
    subtitle: '{online} en ligne · {total} amis',
    close: 'Fermer',
    refresh: 'Actualiser',
    tabFriends: 'Amis',
    tabRequests: 'Demandes',
    tabAdd: 'Ajouter',
    sectionOnline: 'EN LIGNE',
    sectionOffline: 'HORS LIGNE',
    sectionReceived: 'REÇUES',
    sectionSent: 'ENVOYÉES',
    lastSeen: 'Vu {when}',
    level: 'NIV. {level}',
    emptyFriends: 'Pas encore d’amis — cherche des joueurs dans l’onglet Ajouter, ou envoie une demande depuis n’importe quel profil.',
    emptyOnline: 'Aucun de tes amis n’est en ligne pour le moment.',
    emptyRequests: 'Aucune demande en attente.',
    emptySent: 'Aucune demande envoyée.',
    viewProfile: 'Voir le profil',
    profileShort: 'Profil',
    accept: 'Accepter',
    decline: 'Refuser',
    cancelRequest: 'Annuler',
    remove: 'Retirer',
    removeConfirm: 'Retirer {name} de tes amis ?',
    add: 'Ajouter en ami',
    addShort: 'Ajouter',
    sent: 'Demande envoyée',
    pendingYou: 'Souhaite devenir ton ami',
    friends: 'Amis',
    you: 'Toi',
    searchLabel: 'Trouver un joueur',
    searchPlaceholder: 'Pseudo…',
    searchHint: 'Saisis au moins 2 caractères d’un pseudo.',
    searching: 'Recherche…',
    noResults: 'Aucun joueur trouvé pour « {query} ».',
    loading: 'Chargement de tes amis…',
    signInPrompt: 'Se connecter pour ajouter des amis',
    demoNote: 'Aperçu démo — communauté simulée, enregistrée sur cet appareil seulement.',
    demoTarget: 'Un profil démo ne peut ajouter que des joueurs de la communauté démo.',
    realTarget: 'Profil de démonstration — il ne peut pas recevoir de demande d’ami.',
    unavailable: 'Les amis ne sont pas encore activés sur ce déploiement : lance supabase/schema.sql (table friendships) sur le projet Supabase, puis recharge.',
    errGeneric: 'Une erreur est survenue. Réessaie.',
    errNetwork: 'Impossible de joindre le serveur — vérifie ta connexion et réessaie.',
    errSignedOut: 'Ta session a expiré — reconnecte-toi.',
    hubTitle: 'MES AMIS',
    hubStats: '{friends} amis · {online} en ligne · {pending} demandes en attente',
    hubSeeAll: 'Voir tous mes amis ({n})',
    hubSeeLess: 'Réduire',
  },
  ar: {
    launcher: 'الأصدقاء',
    launcherOpen: 'فتح قائمة الأصدقاء',
    launcherClose: 'إغلاق قائمة الأصدقاء',
    online: 'متصل',
    onlineShort: 'متصل',
    offlineShort: 'غير متصل',
    title: 'الأصدقاء',
    subtitle: '{online} متصل · {total} أصدقاء',
    close: 'إغلاق',
    refresh: 'تحديث',
    tabFriends: 'الأصدقاء',
    tabRequests: 'الطلبات',
    tabAdd: 'إضافة',
    sectionOnline: 'متصلون',
    sectionOffline: 'غير متصلين',
    sectionReceived: 'المستلمة',
    sectionSent: 'المرسلة',
    lastSeen: 'شوهد {when}',
    level: 'المستوى {level}',
    emptyFriends: 'لا أصدقاء بعد — ابحث عن لاعبين في تبويب «إضافة»، أو أرسل طلبًا من أي ملف لاعب.',
    emptyOnline: 'لا أحد من أصدقائك متصل الآن.',
    emptyRequests: 'لا توجد طلبات معلّقة.',
    emptySent: 'لم تُرسل أي طلب.',
    viewProfile: 'عرض الملف',
    profileShort: 'الملف',
    accept: 'قبول',
    decline: 'رفض',
    cancelRequest: 'إلغاء',
    remove: 'إزالة',
    removeConfirm: 'إزالة {name} من أصدقائك؟',
    add: 'إضافة صديق',
    addShort: 'إضافة',
    sent: 'تم إرسال الطلب',
    pendingYou: 'يريد أن يصبح صديقك',
    friends: 'أصدقاء',
    you: 'أنت',
    searchLabel: 'ابحث عن لاعب',
    searchPlaceholder: 'اسم اللاعب…',
    searchHint: 'اكتب حرفين على الأقل من اسم اللاعب.',
    searching: 'جارٍ البحث…',
    noResults: 'لم يُعثر على لاعب باسم «{query}».',
    loading: 'جارٍ تحميل أصدقائك…',
    signInPrompt: 'سجّل الدخول لإضافة أصدقاء',
    demoNote: 'معاينة تجريبية — مجتمع محاكى، محفوظ على هذا الجهاز فقط.',
    demoTarget: 'الحساب التجريبي لا يضيف إلا لاعبي المجتمع التجريبي.',
    realTarget: 'ملف تجريبي — لا يمكنه استقبال طلبات الصداقة.',
    unavailable: 'ميزة الأصدقاء غير مفعّلة بعد على هذا النشر: شغّل supabase/schema.sql (جدول friendships) على مشروع Supabase ثم أعد التحميل.',
    errGeneric: 'حدث خطأ. حاول مرة أخرى.',
    errNetwork: 'تعذّر الوصول إلى الخادم — تحقق من اتصالك وحاول مجددًا.',
    errSignedOut: 'انتهت جلستك — سجّل الدخول مجددًا.',
    hubTitle: 'أصدقائي',
    hubStats: '{friends} أصدقاء · {online} متصل · {pending} طلبات معلّقة',
    hubSeeAll: 'عرض كل أصدقائي ({n})',
    hubSeeLess: 'عرض أقل',
  },
};

export function friendsText(lang) {
  return friendsCopy[lang] || friendsCopy.en;
}

/** Remplace les `{jetons}` d'un libellé. */
export function fill(template, values) {
  return String(template || '').replace(/\{(\w+)\}/g, (match, key) => (
    values && values[key] !== undefined && values[key] !== null ? String(values[key]) : match
  ));
}

/** Message lisible pour une erreur Supabase du module amis. */
export function describeFriendsError(error, t) {
  const message = error?.message || '';
  const code = error?.code || '';
  if (error?.status === 0 || /failed to fetch|load failed|networkerror|fetch failed/i.test(message)) return t.errNetwork;
  if (code === '42501' || code === 'PGRST301' || error?.status === 401 || /row-level security|jwt|permission denied/i.test(message)) return t.errSignedOut;
  return message || t.errGeneric;
}
