import { gameTests } from '../reviewsData';
import { gameReleases } from '../releasesData';
import { quizzes as quizCatalog, quizLabel, quizQuestionsCount } from '../quizzesData';
import { baseUrl as base } from '../data';
import { youTubeThumbUrl } from '../lib/videoThumbnails';
// Les actus du jour générées par le robot rejoignent l’index de recherche.
import { autoSearchEntries } from '../lib/autoNews';

const news = [
  // Actus du mercredi 07.10.2026 — gaming, cinéma & séries, tech.
  ['GTA 6 sur PC : le démenti tombe sur le cloud', 'Après une nuit de rumeurs sur le Xbox Cloud Gaming, Matthew Ball (Xbox) dément formellement : GTA VI ne sera pas jouable sur PC via le cloud et reste exclusif aux consoles au lancement.', '/news/gta-6-cloud-pc-dementi-xbox', 'gaming rockstar gta 6 gta vi xbox cloud gaming pc streaming matthew ball asha sharma tom warren the verge ps5 series x', 'gta-6-cloud-pc-dementi-news.jpg'],
  ['Spider-Man 4 fixe son cap avec Cretton', 'Destin Daniel Cretton réalisera Spider-Man 4 avec Tom Holland et Zendaya : tournage calé pour l’été et sortie cinéma annoncée pour juillet 2027.', '/news/cinema/spider-man-4-destin-daniel-cretton', 'cinéma spider man 4 peter parker tom holland zendaya destin daniel cretton marvel studios sony pictures mcu avengers doomsday', 'spider-man-4-cretton-news.jpg'],
  ['L’AI Act s’active en Europe', 'Le Bureau européen de l’IA adresse ses premières demandes de conformité aux géants de la tech : 30 jours pour documenter les modèles frontières sous peine d’amendes allant jusqu’à 7 % du chiffre d’affaires.', '/news/tech/ai-act-europe-premiers-controles', 'tech ai act europe union européenne régulation intelligence artificielle ai office openai google anthropic meta reuters', 'ai-act-europe-regulation-news.jpg'],
  // Actus du mardi 06.10.2026 — gaming, cinéma & séries, tech.
  ['GTA 6 satirisera un monde inventé', 'Rockstar refuse de cibler « aucune personne, aucun événement ni aucun mouvement en particulier » : la satire du jeu portera sur un État fictif nourri de la Floride, rendu plus grotesque que la réalité.', '/news/gta-6-satire-monde-invente', 'gaming rockstar gta 6 gta vi satire politique floride rupert humphries rob nelson worldbuilding red dead redemption 2 19 novembre ps5 xbox series', 'https://cdn.gamekult.com/optim/images/news/30/3050872331/nous-ne-souhaitons-cibler-aucune-personne-aucun-evenement-ni-aucun-mouvement-en-particulier-gta-vi-ne-visera-pas-la-satire-d-une-actualite-reelle-33b4df1a__930_300__0-7-2548-833.jpg'],
  ['The Batman Part II suspend son tournage', 'Warner Bros. et DC Studios confirment la pause : Matt Reeves s’éloigne de la production pour une affaire familiale, sans date de reprise. La sortie américaine reste fixée au 18 février 2028.', '/news/cinema/the-batman-part-ii-tournage-suspendu', 'cinéma the batman part ii matt reeves robert pattinson dc studios warner bros deadline tournage suspendu gotham andy serkis colin farrell jeffrey wright 18 février 2028', youTubeThumbUrl('mqqft2x_Aa4')],
  ['La Norvège veut couper les caméras', 'Le gouvernement propose une interdiction temporaire des lunettes connectées dans les parcs, plages, écoles, crèches, salles de sport et événements publics. L’usage privé resterait autorisé, et le texte n’est pas encore voté.', '/news/tech/norvege-lunettes-connectees-interdiction', 'tech norvège lunettes connectées caméra ray-ban meta oakley vie privée surveillance interdiction rgpd oslo torgeir micaelsen afp', 'https://i.guim.co.uk/img/media/40af5768117abd5443d47eba0a698ad852dd88a1/451_0_4085_3270/master/4085.jpg?width=1200&dpr=1&s=none&crop=none'],
  // Actus du lundi 05.10.2026 — gaming, cinéma & séries, tech.
  ['E-Day est enfin là', 'Le préquel de The Coalition sort le 6 octobre sur Xbox Series X|S et PC, avec 87 sur Metacritic et une campagne de cinq actes et vingt-six chapitres.', '/news/gears-of-war-e-day-sortie-mondiale', 'gaming gears of war e-day the coalition xbox microsoft marcus fenix dom santiago kalona emergence day horde siege game pass métacritic préquel', youTubeThumbUrl('TOEuNKz3XW8')],
  ['Valjean et Javert sortent le 14 octobre', 'Fred Cavayé adapte Victor Hugo avec Vincent Lindon, Tahar Rahim, Noémie Merlant, Camille Cottin et Benjamin Lavernhe ; la bande-annonce est déjà en ligne.', '/news/cinema/les-miserables-cavaye-14-octobre', 'cinéma les misérables victor hugo fred cavayé vincent lindon tahar rahim noémie merlant camille cottin benjamin lavernhe javert valjean fantine pathé studiocanal', youTubeThumbUrl('ZZRo2fIbomE')],
  ['Aion 2 ouvre l’Occident', 'Le MMORPG de NCSOFT passe au free-to-play le 5 octobre à 13 h UTC sur PC, via Steam et PURPLE : serveurs européens, français en sous-titres et progression conservée après l’accès anticipé.', '/news/aion-2-ouverture-occidentale', 'gaming ncsoft aion 2 mmorpg free-to-play lancement occidental steam purple serveurs europe abyss packs fondateurs', youTubeThumbUrl('YYelxy0eEsA')],
  ['Les Marshals reprennent du service', 'La saison 2 de Marshals: A Yellowstone Story arrive le 5 octobre sur Paramount+ en France, avec Luke Grimes et l’enlèvement de Tate en fil rouge, pour au moins dix-huit épisodes.', '/news/cinema/marshals-saison-2-paramount-france', 'cinéma série marshals a yellowstone story saison 2 paramount+ france cbs luke grimes kayce dutton tate taylor sheridan spencer hudnut', youTubeThumbUrl('mtk4ZZutvLc')],
  ['L’IA s’appelle « SI »', 'Trump crée une « Super Intelligence Force » présidée par Jay Clayton, rapport attendu sous 120 jours, tandis qu’Elon Musk confirme vouloir renommer SpaceXAI en SpaceXSI.', '/news/tech/super-intelligence-force-spacexsi', 'tech ia intelligence artificielle si super intelligence force trump maison-blanche jay clayton elon musk spacexai spacexsi décret', youTubeThumbUrl('6UBA8iL3x54')],
  // Actus du week-end des 03-04.10.2026 — gaming, cinéma & séries, tech.
  ['RuneScape 4 écrit son Sixième Âge', 'Jagex officialise un quatrième MMORPG sous Unreal Engine au RuneFest, sans date de sortie, et détaille les feuilles de route de toute la franchise.', '/news/runescape-4-runefest-annonce', 'gaming jagex runescape 4 runefest mmorpg unreal engine gielinor sixième âge ashenfall dragonwilds reignited old school', 'runescape-4-teaser.jpg'],
  ['Castlevania fête ses 40 ans sur scène', 'Trois concerts symphoniques à Tokyo, Londres et Los Angeles en mars, avec les musiques de Belmont’s Curse jouées en live pour la première fois.', '/news/castlevania-40-ans-concerts-symphoniques', 'gaming konami castlevania 40 ans concerts symphoniques belmont’s curse evil empire konami tokyo londres los angeles', 'https://cdn.gamekult.com/optim/images/news/30/3050872268/pour-les-40-ans-de-castlevania-et-la-sortie-de-belmont-s-curse-des-concerts-symphoniques-vont-avoir-lieu-65c89bda__930_300__0-112-1887-720.png'],
  ['Le vibe coding pollue la préservation', 'RPCS3 menace de bannir les contributions générées par IA sans relecture, entre portage contesté de Mario Kart Wii et projets « 100 % humains ».', '/news/vibe-coding-emulation-decompilation', 'gaming émulation décompilation ia vibe coding rpcs3 mario kart wii donkey kong 64 super mario galaxy luma’s workshop préservation', 'https://cdn.gamekult.com/optim/images/news/30/3050872249/du-code-bacle-par-ia-ralentit-des-projets-d-emulation-et-de-decompilation-les-developpeurs-poussent-un-coup-de-gueule-7c5509e8__930_300__0-41-739-279.jpg'],
  ['Verity s’impose, Digger sombre', 'Le thriller d’Anne Hathaway vise 33,6 M$ pour son premier week-end américain, quand le film de Tom Cruise et Iñárritu s’effondre autour de 7,5 M$.', '/news/cinema/box-office-verity-digger', 'cinéma box-office verity anne hathaway colleen hoover digger tom cruise iñárritu resident evil heart of the beast kraken france', 'cinema-verity.jpg'],
  ['Dexter revient en crise existentielle', 'La saison 2 de Dexter: Resurrection arrive le 30 octobre sur Paramount+, avec Dan Stevens, Brian Cox et un Michael C. Hall en pleine cinquantaine.', '/news/cinema/dexter-resurrection-saison-2-bande-annonce', 'série dexter resurrection saison 2 paramount+ michael c. hall dan stevens brian cox uma thurman bande-annonce', youTubeThumbUrl('nTOf1FIsBcs')],
  ['Beware Boiúna divise la presse', 'Le film d’horreur de Mike P. Nelson, sorti le 2 octobre aux États-Unis, plafonne à 49 sur 100 sur Metacritic et n’a pas encore de date en France.', '/news/cinema/beware-boiuna-premiers-avis', 'cinéma beware boiúna horreur lionsgate mike p. nelson kiana madeira jessica rothe amazonie anaconda avis', 'https://www.ecranlarge.com/content/uploads/2026/10/0cd9b8ac42be3e75907c77e111310c4d-1260x840.webp'],
  ['Les Hauts-de-France victimes d’une cyberattaque', 'La Région confirme un accès non autorisé à des données personnelles via deux prestataires ; un pirate revendique plus de 700 000 comptes, dont des RIB.', '/news/tech/cyberattaque-hauts-de-france-rib', 'tech cybersécurité france hauts-de-france cyberattaque fuite données rib atexo docaposte anssi ldlc carrefour', 'https://www.01net.com/app/uploads/2025/06/fuite-donnees-france.jpg'],
  ['La Corée du Nord détourne Ethereum', 'La technique HashHiding cache les adresses de serveurs de commande dans la blockchain Ethereum, rendant les blocages de malware inefficaces.', '/news/tech/coree-du-nord-ethereum-hashhiding', 'tech cybersécurité corée du nord ethereum blockchain hashhiding xctdh ransomware isac malware développeurs', 'https://www.01net.com/app/uploads/2024/01/ethereum.jpg'],
  ['Tesla redresse, BYD s’envole', 'Tesla a livré 486 532 voitures au troisième trimestre, mieux que prévu, mais BYD en a vendu 762 478 et porte son avance à près de 276 000 unités.', '/news/tech/tesla-t3-2026-livraisons-byd', 'tech tesla byd livraisons troisième trimestre 2026 model 3 model y gigafactory berlin export chine', 'https://img.frandroid.com/images.frandroid.com/wp-content/uploads/2026/04/tesla-gigafactory-berlin-usine-00017.jpg?resize=1200,675&key=c61b8cfd'],
  ['Dynasty Warriors 3 ressort ses lames', 'Le remaster de Dynasty Warriors 3 et Xtreme Legends arrive le 1er octobre 2026 avec scénarios supplémentaires et coop à deux.', '/news/dynasty-warriors-3-remastered-sortie', 'gaming koei tecmo dynasty warriors 3 remastered xtreme legends coop', youTubeThumbUrl('O8hfaFyKMq0')],
  ['Matthew Perry raconté par les siens', 'Netflix dévoile le trailer de sa série documentaire en trois parties, attendue le 27 octobre 2026.', '/news/cinema/matthew-perry-documentaire-netflix', 'cinéma netflix matthew perry friends documentaire trailer', youTubeThumbUrl('_iM1AOFxoDI')],
  ['Suncatcher décolle pour son premier test', 'Google passe à la phase de mesures orbitales pour tester son matériel IA et ses liaisons entre satellites.', '/news/tech/project-suncatcher-lancement-test', 'tech google project suncatcher lancement satellite tpu espace', youTubeThumbUrl('o1JK79jszqo')],
  ['Ghost of Yōtei ouvre son nouveau chapitre', 'La Complete Edition arrive le 1er octobre sur PS5 avec Echoes of Sekigahara, Most Wanted et la mise à jour 2.0.', '/news/ghost-yotei-complete-edition-1er-octobre', 'gaming playstation ps5 ghost of yotei sucker punch echoes sekigahara most wanted', youTubeThumbUrl('2bQrrWCRkMY')],
  ['À l’Est d’Éden fait son entrée sur Netflix', 'La mini-série de Zoe Kazan avec Florence Pugh adapte le roman de John Steinbeck dès le 1er octobre.', '/news/cinema/a-l-est-d-eden-netflix', 'cinéma netflix a lest eden florence pugh zoe kazan steinbeck', youTubeThumbUrl('M9NWvGZViCg')],
  // Actus tech du jour (29.09.2026) (page /news/tech).
  ['Starship est enfin en orbite', 'Le vol 14 a atteint l’orbite pour la première fois le 28 septembre et déployé 26 satellites Starlink V3 opérationnels, avant un retour anticipé dans le Pacifique nord après la panne d’un moteur en montée.', '/news/tech/starship-vol-14-orbite-atteinte', 'tech espace spacex starship vol 14 orbite starlink v3 flight 14 raptor pacifique starbase', 'https://sxcontent9668.azureedge.us/cms-assets/assets/Flight_14_Website_Desktop_4_734a6bbf25.jpg'],
  ['NVIDIA met les agents en cage', 'L’Open Agent Safety Platform combine OpenShell, un bac à sable open source pour agents autonomes, et Sentry, une surveillance matérielle sur DPU BlueField-4 qui les met en quarantaine en quelques millisecondes.', '/news/tech/nvidia-open-agent-safety-platform', 'tech nvidia open agent safety platform openshell sentry bluefield jensen huang sécurite ia agents autonomes sandbox', 'https://iprsoftwaremedia.com/219/files/202609/c68dda94943a6e093074e9e88fd5ddef/6aba9c533d6332d60a0bb99a_nvidia-open-agent-safety-platform/nvidia-open-agent-safety-platform_mid.png?v=f9cea0c6-00ad-4b7f-b0a0-6bc06b39af63'],
  ['Trump reçoit les 6 boss de l’IA', 'Les patrons de Meta, Anthropic, OpenAI, Google, Palantir et Nvidia déjeunent à la Maison-Blanche pour arbitrer la régulation de l’IA, le jour où Hinton et Bengio alertent sur une « explosion d’intelligence ».', '/news/tech/midi-ia-maison-blanche', 'tech ia intelligence artificielle trump maison-blanche zuckerberg amodei brockman pichai karp huang régulation hinton bengio', 'https://img.semafor.com/4edcc71f032e922ad0fa3f238b2206d9949f984f-2048x1294.jpg?w=740&q=75&auto=format&h=467'],
  // Actus tech de la semaine du 21 au 28.09.2026 (page /news/tech).
  ['Starship vise l’orbite pour de vrai', 'Le vol 14 vise la première mise en orbite de Starship et le déploiement de 26 satellites Starlink V3, jusqu’à 26 Tbps de capacité. Fenêtre de 75 minutes ouverte à 12 h 15 UTC, repli les 29 et 30 septembre.', '/news/tech/starship-flight-14-premier-vol-orbital', 'tech espace spacex starship vol 14 orbite starlink v3 satellites starbase faa supersonic heavy', 'https://sxcontent9668.azureedge.us/cms-assets/assets/Flight_14_Website_Desktop_4_734a6bbf25.jpg'],
  ['Copilot devient un agent : Home, Code, Autopilot', 'Microsoft réorganise Copilot autour de trois briques, dont un agent hébergé dans le cloud qui continue de travailler hors connexion. Entreprises d’abord, facturation à l’usage pour les fonctions agentiques.', '/news/tech/copilot-home-code-autopilot', 'tech microsoft copilot ia intelligence artificielle autopilot code home cowork agent entreprise gestion', 'https://blogs.microsoft.com/wp-content/uploads/2026/09/OMB-Copilot-9-25-Hero-9_22_26.png'],
  ['Apple condamnée à 5,7 milliards de dollars', 'Un jury fédéral de San Diego juge que le Taptic Engine des iPhone et Apple Watch contrefait deux brevets de Taction Technology : le verdict le plus lourd jamais rendu contre une entreprise technologique aux États-Unis.', '/news/tech/apple-taptic-engine-verdict-5-7-milliards', 'tech apple taction taptic engine brevet justice procès san diego iphone apple watch haptique', 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/09/268738_Apple_Watch_Series_12_AKrales_0277.jpg?quality=90&strip=all&crop=0%2C0%2C100%2C100&w=1600'],
  ['Un agent OpenAI franchit le garde-fou', 'En juin, un agent d’OpenAI a atteint des fichiers non publics du portail de statistiques Medicare australien, sans consigne en ce sens. L’Australie n’a été prévenue que le 10 septembre.', '/news/tech/agent-openai-portail-australien', 'tech openai agent ia cybersécurité australie medicare services australia albanese intrusion', 'https://image.cnbcfm.com/api/v1/image/107431804-17189858722024-06-21t155215z_1214353438_rc2sj6aut6ur_rtrmadp_0_rockset-m-a-openai.jpeg?v=1757715670&w=1600&h=900&vtcrop=y'],
  ['Meta Connect 2026 : lunettes à 1 299 $ et Muse Charm', 'Des lunettes de réalité virtuelle à 1 299 dollars pour le printemps 2027, un Muse Charm pour parler à son agent IA sans sortir son téléphone, et Muse en tête des applications gratuites de l’App Store américain.', '/news/tech/meta-connect-2026-lunettes-muse-charm', 'tech meta connect 2026 zuckerberg lunettes vr réalité virtuelle muse charm agent ia ray-ban', 'https://image.cnbcfm.com/api/v1/image/108367218-Julia_Meta_VR_2.jpg?v=1790211668&w=1600&h=900&vtcrop=y'],
  // Actus cinéma du jour (29.09.2026).
  ['Endgame frôle le trône d’Avatar', 'Le week-end mondial de la ressortie atteint 86 M$ (26 M$ en Amérique du Nord, 60 M$ à l’international) et porte le total à environ 2,885 milliard — à 39 millions du record d’Avatar.', '/news/cinema/endgame-encore-record-avatar', 'cinéma box-office avengers endgame encore avatar record mondial ressortie marvel disney', youTubeThumbUrl('L2NAh3CIdig')],
  ['Coyote vs. Acme passe en ligne', 'Le film sauvé de la déduction fiscale de Warner Bros. par Ketchup Entertainment est disponible en numérique dès le 29 septembre à 24,99 $, après plus de 100 M$ au box-office mondial.', '/news/cinema/coyote-vs-acme-numerique', 'cinéma looney tunes coyote vs acme ketchup entertainment warner will forte john cena lana condor numérique pvod', youTubeThumbUrl('Bpg3tJ4f3v0')],
  ['Mononoke clôture sa trilogie', 'Mononoke The Movie: Chapter III – The Curse of the Serpent arrive sur Netflix le 29 septembre : le Marchand de médicaments affronte une malédiction née dans les rangs supérieurs de l’Ōoku.', '/news/cinema/mononoke-chapter-3-netflix', 'cinéma anime mononoke chapter 3 curse of the serpent netflix medicine seller ōoku studio kafka eota twin engine', youTubeThumbUrl('R6PUcxSZ7YM')],
  ['Box-office : Endgame confirme ses 26 millions', 'Bilan consolidé du week-end américain des 25-27 septembre : Endgame – Encore premier (26 M$), Resident Evil deuxième (23,3 M$), meilleur 39e week-end depuis 2015.', '/news/cinema/box-office-us-endgame-encore-26-millions', 'cinéma box-office avengers endgame encore resident evil deadline primetime heart of the beast weekend', youTubeThumbUrl('L2NAh3CIdig')],
  ['The Last of Us saison 3 : John Goodman, Laura Bailey et Ian Alexander', 'HBO annonce trois nouveaux visages pour la saison 3 : Goodman (Joey), Alexander (Paco) et Bailey, la voix d’Abby dans le jeu, en cheffe des Séraphites.', '/news/cinema/the-last-of-us-saison-3-john-goodman-laura-bailey', 'série hbo the last of us saison 3 casting john goodman laura bailey ian alexander abby séraphites craig mazin', 'https://variety.com/wp-content/uploads/2026/09/LastofUs.Split_.1.jpg?w=1000&h=667&crop=1'],
  ['Godzilla Minus Zero rugit à New York', 'Première mondiale applaudie au New York Film Festival, premier Godzilla classé R ; sortie le 3 novembre au Japon, le 4 en France, le 6 aux États-Unis.', '/news/cinema/godzilla-minus-zero-premiere-nyff', 'cinéma godzilla minus zero minus one takashi yamazaki toho nyff festival kaiju classé r', 'https://variety.com/wp-content/uploads/2026/09/GettyImages-2297305809.jpg?w=1000&h=667&crop=1'],
  ['Box-office : Endgame contre Resident Evil', 'La ressortie d’Avengers: Endgame vise 24 à 26 M$ sur le week-end américain, devant le reboot Resident Evil.', '/news/cinema/box-office-us-endgame-resident-evil', 'cinéma box-office avengers endgame marvel resident evil sony zombies', youTubeThumbUrl('L2NAh3CIdig')],
  ['Werwulf montre ses crocs', 'La deuxième bande-annonce de Werwulf, l’horreur médiévale de Robert Eggers, sort le 25 décembre 2026.', '/news/cinema/werwulf-trailer-eggers', 'cinéma robert eggers werwulf trailer horreur loup-garou aaron taylor-johnson dafoe', 'https://images.contentstack.io/v3/assets/blt223a4a92692ca457/bltc56e9a2c23500694/6a3d520c6391ef7c261677e4/werwulf_4marquee_image.png?branch=production&width=1600'],
  ['Le biopic Fred Astaire trouve ses danseuses', 'Tom Holland, Margaret Qualley et Sabrina Carpenter réunis par Sony et Paul King.', '/news/cinema/fred-astaire-biopic-tom-holland', 'cinéma biopic fred astaire tom holland sabrina carpenter margaret qualley ginger rogers sony', 'https://variety.com/wp-content/uploads/2026/09/margaret-tom-sabrina.jpg?w=1200&h=800&crop=1'],
  ['Steel Ball Run — la course reprend', 'L’épisode 2 ouvre onze épisodes hebdomadaires sur Netflix, chaque vendredi jusqu’au 4 décembre.', '/news/cinema/jojo-steel-ball-run-episode-2', 'jojo steel ball run netflix anime david production gyro zeppeli johnny joestar', 'cinema-jojo-steel-ball-run.jpg'],
  ['Dune: Messiah — la bande-annonce officielle', 'Mise à jour : Warner Bros. a publié la bande-annonce du troisième chapitre, titré Dune: Part Three, pour une sortie le 18 décembre 2026. Villeneuve referme la prophétie de Paul Atréides.', '/news/cinema/dune-messiah-trailer', 'cinéma dune messiah part three trailer bande-annonce teaser villeneuve warner bros chalamet zendaya', 'cinema-dune-messiah.jpg'],
  ['The Last of Us saison 3 confirmée', 'HBO adapte la seconde moitié de Part II, du point de vue d’Abby.', '/news/cinema/last-of-us-saison-3', 'hbo the last of us série abby ellie Naughty Dog', 'cinema-last-of-us.jpg'],
  ['Doctor Doom prend les rênes du MCU', 'Robert Downey Jr. masqué, d’Avengers: Doomsday jusqu’à Secret Wars.', '/news/cinema/marvel-doctor-doom', 'marvel doctor doom robert downey jr avengers doomsday secret wars', 'cinema-doctor-doom.jpg'],
  ['Stranger Things 5 : date et trailer', 'La saison finale arrive en mars 2027 sur Netflix, huit épisodes.', '/news/cinema/stranger-things-saison-5', 'netflix stranger things vecna hawkins saison finale', 'cinema-stranger-things.jpg'],
  ['Joker 2 divise encore', 'Bilan d’un malentendu : la comédie musicale de Todd Phillips continue de fendre le public.', '/news/cinema/joker-folie-a-deux', 'joker folie à deux warner phoenix lady gaga todd phillips', 'cinema-joker.jpg'],
  ['House of the Dragon : tournage de la saison 3', 'La Danse des Dragons entre dans sa phase brutale, retour attendu en 2027.', '/news/cinema/house-of-dragon-saison-3', 'hbo house of the dragon westeros danse des dragons', 'cinema-hotd.jpg'],
  ['Blade retrouve un réalisateur', 'Sept ans de chantier et, enfin, un capitaine pour le Daywalker de Mahershala Ali.', '/news/cinema/blade-reboot', 'marvel blade mahershala ali daywalker reboot', 'cinema-blade.jpg'],
  ['Arcane saison 2 : dernière ligne droite', 'Les affiches de la saison finale arrivent, à quelques semaines de la sortie sur Netflix.', '/news/cinema/arcane-saison-2', 'arcane netflix riot games zaun piltover fortiche', 'cinema-arcane.jpg'],
  ['Physint à 400 M$ ? Xbox a signé pour beaucoup moins', 'Christopher Dring évoque un simple bruit de couloir et Jason Schreier assure que Microsoft a conclu son accord avec Kojima Productions pour un montant nettement inférieur.', '/news/physint-budget-400-millions-xbox', 'physint hideo kojima kojima productions xbox playstation sony budget 400 millions jason schreier christopher dring bill skarsgard', 'kojima_mindplayer.webp'],
  ['God of War Laufey : l’arc-serpent et les éditions', 'À l’ouverture des précommandes, Santa Monica Studio détaille l’arc-serpent de Faye, ses deux modes de visée et sa personnalisation, puis la grille des éditions : 79,99 € en Standard, 89,99 € en numérique Deluxe, mise à niveau à 10 €, aucun collector.', '/news/god-of-war-laufey-precommandes-arc-serpent', 'god of war laufey faye kratos santa monica studio playstation ps5 précommande éditions deluxe arc-serpent empyrée phranque sekhmet begtse 16 février 2027', 'https://blog.fr.playstation.com/tachyon/sites/10/2026/09/5bd30eac480284e480a9ba68e9f06472584219f4.jpg?resize=1088%2C612&crop_strategy=smart'],
  ['Le Minecraft World Hotel ouvre en 2027 à Chessington', 'Près de 70 chambres sur quatre étages, restaurant sous-marin et bar à potions : le premier hôtel officiel Minecraft au monde, annoncé au Minecraft Live, accompagnera le rollercoaster Escape the Nether en 2027.', '/news/minecraft-world-hotel-chessington-2027', 'minecraft world hotel chessington mojang merlin entertainments escape the nether rollercoaster parc à thème 2027 hôtel', 'screenshots/minecraft-world-hotel/01.jpg'],
  ['Minecraft ouvre une nouvelle dimension : le Sift', 'Dévoilé au Minecraft Live, le Sift est la première nouvelle dimension depuis quinze ans : dans Minecraft Dungeons II le 29 septembre, puis sur Java et Bedrock en 2027.', '/news/minecraft-the-sift-nouvelle-dimension', 'minecraft mojang the sift dimension minecraft live dungeons ii switch 2 grottes de glace', 'https://www.minecraft.net/content/dam/minecraftnet/games/spicewood/screenshots/MCL_Dungeons2_sift_1280x720.jpg'],
  ['The Witcher 3 Remastered sort le 29 septembre', 'Déverrouillage mondial à 10 h UTC (11 h à Alger) sur PC, PS5, Xbox Series X|S et Switch 2 ; gratuit pour les propriétaires, 45 Go, sans préchargement.', '/news/the-witcher-3-remastered-sortie-29-septembre', 'the witcher 3 wild hunt remastered cd projekt red geralt sortie 29 septembre gratuit switch 2 battle.net', 'https://public.cdn.cdpr.app/common/news/974db3ceaf0e6035a922cbbd7c7770b0_q90_1280x720.jpeg'],
  ['Nadella défend la restructuration Xbox', 'Le PDG de Microsoft juge « formidable » la rationalisation menée par Asha Sharma et promet un retour à la croissance, malgré près de 3 200 postes supprimés.', '/news/xbox-nadella-restructuration', 'xbox microsoft satya nadella asha sharma licenciements restructuration halo activision ninja theory', 'https://news.microsoft.com/source/wp-content/uploads/2024/10/MS-Exec-Nadella-Satya.jpg'],
  ['EA Sports FC 27 — la carrière devient vivante', 'Note globale dynamique, valeur marchande hebdomadaire via TransferRoom et scénarios créés par la communauté.', '/news/ea-sports-fc-27-carriere-dynamique', 'ea sports fc 27 electronic arts football carrière transferts manager', 'ea-sports-fc-27-carriere-pitch-notes.jpg'],
  ['Kingdom Hearts 4 — Le monde de Coco', 'Sora est apparu au milieu d’une séquence Disney consacrée à Coco.', '/news/kingdom-hearts-4-coco', 'square enix disney', 'kingdom-hearts-4-coco-news.jpg'],
  ['Marvel’s Wolverine', 'Une exclusivité PS5 développée par Insomniac Games.', '/news/wolverine-exclu-ps5', 'marvel sony insomniac ps5', 'wolverine-countdown.jpg'],
  ['Fire Emblem: Fortune’s Weave', 'Le nouvel épisode revient sur ses quatre protagonistes et ses scénarios croisés.', '/news/fire-emblem-fortunes-weave', 'nintendo switch 2', 'fire-emblem-fortunes-weave-news.jpg'],
  ['Rayman Legends Retold', 'Le remaster Ubisoft est repoussé au 3 décembre 2026.', '/news/rayman-legends-retold', 'ubisoft remaster', 'rayman-legends-retold-news.jpg'],
  ['Cyberpunk 2077 change de quartier', 'L’Ultimate Edition rejoindra Battle.net plus tard cette année.', '/news/cyberpunk-2077-battlenet', 'cd projekt red blizzard pc', 'cyberpunk-2077-battlenet-news.webp'],
  ['Persona 6 arrive en physique', 'Le prochain épisode de Persona aura aussi une édition physique sur Switch 2.', '/news/persona-6-switch-2', 'sega atlus switch 2', 'persona-6-news.jpg'],
  ['Le mod multijoueur de The Last of Us II', 'Sony a demandé l’arrêt d’un projet de fans sur la version PC.', '/news/last-of-us-ii-mod', 'playstation sony pc', 'last-of-us-mod-news.jpg'],
  ['StarCraft passe au FPS', 'Blizzard prépare un shooter en monde ouvert dans l’univers StarCraft.', '/news/starcraft-fps', 'blizzard fps', 'starcraft-fps-news.jpeg'],
  ['Diablo V se prépare', 'Le prochain chapitre arrivera au printemps 2029.', '/news/diablo-v', 'blizzard action rpg', 'diablo-v-news.webp'],
  ['Diablo IV arrive sur Switch 2', 'La collection Age of Hatred réunit le jeu et ses extensions.', '/news/diablo-switch-2', 'blizzard nintendo', 'diablo-switch2-news.jpg'],
  ['Diablo étend son univers', 'Une série animée Diablo est en préparation pour Netflix.', '/news/diablo-netflix', 'blizzard netflix', 'diablo-netflix-news.webp'],
  ['Monster Hunter Wilds sur Switch 2', 'Monster Hunter Wilds fixe sa sortie au 4 décembre 2026.', '/news/monster-hunter-wilds', 'capcom switch 2', 'monster-hunter-wilds-switch2.jpg'],
  ['Zelda fête ses 40 ans', 'Nintendo dévoile une Switch 2, une manette Pro et deux amiibo.', '/news/zelda-40th', 'nintendo switch 2 ocarina of time', 'zelda-40th-switch2.jpg'],
  ['Metroid Ravenous', 'La nouvelle aventure 2D de Samus arrivera sur Nintendo Switch 2.', '/news/metroid-ravenous', 'nintendo metroid switch 2', 'metroid-ravenous-news.webp'],
  ['Wardogs', 'Le jeu de stratégie et de mercenaires arrive sur PC.', '/news/wardogs', 'pc stratégie', 'wardogs-news.jpg'],
  ['Physint', 'Le projet de jeu d’action espion de PlayStation.', '/news/physint', 'playstation sony', 'physint-news.jpg'],
  ['Zelda: Ocarina of Time', 'Le classique de Nintendo revient sur Switch 2.', '/news/zelda-ocarina', 'nintendo zelda switch 2', 'zelda-ocarina-news.jpg'],
  ['Onimusha: Way of the Sword', 'Le retour samouraï de Capcom dépasse le million de ventes.', '/news/onimusha-million', 'capcom samouraï', 'onimusha-million-news.jpg'],
].map(([title, description, route, keywords, image]) => ({ type: 'news', title, description, route, keywords, image: /^https?:\/\//i.test(image) ? image : `${base}${image}` }));

const dossiers = [
  ['La PS2, la reine', 'Vingt-cinq ans après son lancement, retour sur la PlayStation 2.', '/dossiers/25-ans-playstation-2', 'playstation sony histoire', 'A2VPhWOUMHI'],
  ['La Xbox 360, une génération', 'Retour sur Xbox Live, la haute définition et le Red Ring of Death.', '/dossiers/20-ans-xbox-360', 'xbox microsoft histoire', '8NqnTzVh5O0'],
  ['Le choc des générations', 'Les consoles, les jeux et les communautés qui ont façonné notre manière de jouer.', '/dossiers/choc-generations-gaming', 'culture gaming consoles', 't1Re8ki_gsw'],
  ['La PlayStation 1, une révolution', 'Retour sur la console qui a fait passer le jeu vidéo aux CD et à la 3D.', '/dossiers/heritage-playstation-1', 'playstation sony histoire', 'oOyW_rjiZ5w'],
  ['Let’s Play Awards 2025', 'Les jeux qui ont marqué l’année et le choix du GOTY.', '/dossiers/let-play-awards-2025', 'awards gaming goty', '0ThNyFItASM'],
  ['GOYA et HicoSoft Studio', 'Dans les coulisses du projet GOYA et de la scène indépendante algérienne.', '/dossiers/goya-hicosoft', 'goya hicosoft algérie indépendant', 'aTs0zhm6Leg'],
  ['Games & Comic Con Dzair 2026', 'Cosplay, invités, découvertes et communauté gaming.', '/dossiers/games-comic-con-dzair', 'comic con culture algérie', 'HzigJZOxz2o'],
  ['Pourquoi les Souls ?', 'Difficulté, narration, dopamine de la victoire et communauté.', '/dossiers/pourquoi-les-souls', 'souls fromsoftware analyse', 'OH51fSHznwg'],
].map(([title, description, route, keywords, videoId]) => ({ type: 'dossier', title, description, route, keywords, image: youTubeThumbUrl(videoId, 'hq') }));

const reviews = gameTests.map((test) => ({
  type: 'review', title: test.name, description: test.excerpt, route: test.route,
  keywords: [test.platforms, test.genre, test.studio, test.cardTitle].join(' '),
  meta: `${test.score}/10 · ${test.platforms}`, image: test.image,
}));

const releases = gameReleases.map((game) => ({
  type: 'release', title: game.title, description: `${game.platforms} · sortie prévue au calendrier`,
  route: game.to || '/calendrier', keywords: game.platforms,
  meta: game.year ? `${game.day}/${game.month}/${game.year}` : `${game.day}/${game.month}/2026`,
  image: game.image ? `${base}${game.image}` : null,
}));

// `slug` : la page de recherche et la recherche instantanée de la nav s'en
// servent pour reconnaître un quizz TERMINÉ (ses trois niveaux faits) et le
// griser comme sur la grille `/quizz`.
const quizzes = quizCatalog.map((quiz) => ({
  type: 'quiz',
  slug: quiz.slug,
  title: quizLabel(quiz.labels, 'fr')?.title || quiz.slug,
  description: quizLabel(quiz.labels, 'fr')?.text || '',
  route: quiz.route,
  keywords: quiz.keywords,
  meta: `${quizQuestionsCount(quiz)} questions`,
  image: quiz.image || youTubeThumbUrl(quiz.videoId, 'hq'),
}));

export const searchIndex = [...news, ...reviews, ...dossiers, ...releases, ...quizzes];

export function normalizeSearch(value = '') {
  return String(value).toLocaleLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu, '').replace(/[’'`]/g, '').replace(/[^\p{Letter}\p{Number}]+/gu, ' ').trim();
}

export function searchContent(query) {
  const normalized = normalizeSearch(query);
  if (!normalized) return [];
  const terms = normalized.split(/\s+/).filter(Boolean);
  const matchesToken = (tokens, term) => tokens.some((token) => token === term || (term.length >= 3 && token.startsWith(term)));
  const matchesAll = (tokens) => terms.every((term) => matchesToken(tokens, term));
  const scored = searchIndex.map((item) => {
    const title = normalizeSearch(item.title), description = normalizeSearch(item.description), keywords = normalizeSearch(item.keywords);
    const titleTokens = title.split(' '), descriptionTokens = description.split(' '), keywordTokens = keywords.split(' ');
    const titleMatch = matchesAll(titleTokens), keywordMatch = matchesAll(keywordTokens), metadataMatch = titleMatch || keywordMatch;
    const descriptionMatch = matchesAll(descriptionTokens);
    const score = terms.reduce((total, term) => (
      total + (titleTokens.includes(term) ? 12 : 0) + (keywordTokens.includes(term) ? 6 : 0) + (descriptionTokens.includes(term) ? 1 : 0)
    ), 0) + (title === normalized ? 20 : 0);
    return { ...item, score, metadataMatch, descriptionMatch };
  });
  const strongMatches = scored.filter((item) => item.metadataMatch);
  const matches = strongMatches.length ? strongMatches : scored.filter((item) => item.descriptionMatch);
  return matches.sort((a, b) => b.score - a.score || a.title.localeCompare(b.title));
}

export const searchCounts = { news: news.length + autoSearchEntries.length, review: reviews.length, dossier: dossiers.length, release: releases.length, quiz: quizzes.length };
