import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { baseUrl as base } from '../data';
import Comments from '../components/Comments';
import ArticleEngagement from '../components/ArticleEngagement';
import { youTubeEmbedUrl } from '../lib/videoPlayback';
import NotFound from './NotFound';
// Les actus du jour générées par le robot (src/news/autoIndex.js, vide au
// départ) cohabitent avec les articles manuels ci-dessous : même gabarit.
import { autoStories } from '../news/autoIndex';
import { incrementArticleView, getArticleViews, normalizeArticleId, formatViews } from '../lib/articleViews';
import { inferSentimentForStory, sentimentMeta } from '../lib/articleSentiment';

const stories = {
  'ea-sports-fc-27-carriere-dynamique': {
    date: '22.09.2026', category: 'EA SPORTS FC 27 · MODE CARRIÈRE', image: 'ea-sports-fc-27-carriere-pitch-notes.jpg', imageAlt: 'EA Sports FC 27 — fiche joueur du mode Carrière avec sa note globale et sa valeur marchande xTV calculée avec TransferRoom (visuel officiel EA Sports FC)', cover: 'EA SPORTS FC 27',
    title: 'EA SPORTS FC 27', accent: 'LA CARRIÈRE DEVIENT VIVANTE.', dek: 'Valeur marchande recalculée chaque semaine avec TransferRoom, note globale qui monte et qui chute, scénarios créés par la communauté : le mode Carrière est le vrai chantier de l’édition 2027.',
    lead: 'On n’attendait plus grand-chose d’un mode Carrière de football : une saison, puis l’impression d’avoir déjà tout vu. Ce que décrit Electronic Arts pour EA Sports FC 27 n’est pas une retouche de plus — le club se met à réagir en temps réel à ce qui se passe sur le terrain.',
    intro: 'Les Pitch Notes publiées par EA à trois jours de la sortie détaillent une refonte complète de la gestion : performances, forme, moral et valeur des joueurs pèsent désormais sur chaque décision. L’objectif affiché par les développeurs est simple à énoncer, difficile à tenir : effacer la routine des saisons répétitives pour se rapprocher du quotidien d’un entraîneur professionnel.',
    h2: 'LE MARCHÉ DES TRANSFERTS DEVIENT UN DOSSIER VIVANT', p1: 'Premier changement, et il est structurel : le prix d’un joueur ne reste plus figé à un montant calculé en fonction de son âge. Electronic Arts s’est associé à TransferRoom, la plateforme qu’utilisent les clubs professionnels, et reprend son système xTV pour estimer la valeur marchande à partir des performances réelles et du temps de jeu. Résultat : la cote d’un footballeur bouge chaque semaine, comme un cours en bourse. Une série de buts la fait grimper, une blessure ou un banc la fait chuter. Les négociations se déroulent elles aussi en plusieurs étapes étalées dans le temps — assez pour qu’un club concurrent s’invite au dernier moment et fasse capoter un transfert presque bouclé. Les contrats gagnent enfin des options réclamées depuis des années : paiement échelonné sur plusieurs saisons, clause de rachat, pourcentage à la revente, ou prêt immédiat du joueur acheté à son club d’origine. Selon EA, l’IA des clubs adverses a également été réécrite : elle recrute selon une stratégie tactique précise au lieu d’empiler des remplaçants inutiles.',
    quote: 'Une valeur qui bouge chaque semaine, c’est une saison qui ne peut plus se rejouer à l’identique.', quoteBy: 'L’ANALYSE LET’S PLAY',
    h2b: 'LA NOTE GLOBALE MONTE… ET DESCEND', p2: 'Deuxième bascule : la note globale devient dynamique. Dans les épisodes précédents, la progression d’un joueur suivait une courbe largement prédéfinie. Ici, elle peut monter ou chuter au fil de la saison selon la forme, le moral au quotidien et la condition physique. Le système d’entraînement manuel disparaît au profit de la récupération d’énergie : on ne passe plus ses semaines à optimiser des séances, on gère de la fraîcheur. Avec une conséquence très réaliste, et potentiellement cruelle : aligner un joueur tout juste revenu de blessure, sans être totalement rétabli, expose à une rechute immédiate.',
    p3: 'La progression gagne aussi en variété. Six profils de croissance sont intégrés : certains jeunes talents explosent très vite avant de stagner, d’autres ne révèlent leur potentiel qu’après plusieurs saisons. La polyvalence s’élargit, un joueur pouvant couvrir jusqu’à sept postes préférentiels sans pénalité sur sa note. En parallèle, le mode Manager Live ouvre un portail de création de scénarios accessible par un code QR : la communauté pourra concevoir et partager ses propres défis de carrière, avec des règles imposées dès le départ — pénalité de points au classement, plafond salarial strict, obligation d’aligner des jeunes du centre de formation. S’y ajoute un moteur d’événements imprévisibles qui sort du terrain : litiges financiers, sanctions de la ligue, tensions dans le vestiaire, et des conférences de presse où chaque réponse modifie le moral du groupe. En Carrière Joueur, des rivalités individuelles apparaissent face à un joueur géré par l’ordinateur au même poste.',
    p4: 'Reste la vraie question, celle qu’aucun patch note ne tranche. Le mode Carrière de la série souffre d’un syndrome connu : des saisons qui se ressemblent, une fois la première boucle comprise. Ce que décrit EA — un club qui vit, une valeur qui fluctue, un vestiaire qui s’agace — ressemble à la première tentative sérieuse pour casser ce rythme. Il faudra vérifier sur pièces que cette vie ne se résume pas à une pile de chiffres, et que les crises restent lisibles plutôt qu’aléatoires. Bonne nouvelle : la refonte s’appuie aussi sur le moteur de match détaillé dans les Pitch Notes de gameplay, qui renforce le contrôle manuel en défense. Rendez-vous le 25 septembre 2026, sur PC, PS5, Xbox Series et Switch, pour savoir si la routine a vraiment pris fin.',
    sentiment: 'positive', take: 'RÉSUMÉ', takeText: 'EA Sports FC 27 cherche surtout à rendre le mode Carrière moins statique : le club, le marché et les histoires de vestiaire devraient enfin peser ensemble sur une saison.',
    source: 'D’après les Pitch Notes d’Electronic Arts (« FC 27 Career Mode Deep Dive ») et l’article de jeuxvideo.com publié le 22.09.2026.', sourceUrl: 'https://www.jeuxvideo.com/news/2105158/ea-sports-fc-27-les-nouveautes-du-mode-carriere-qui-changent-tout.htm', sourceDetail: 'Lire l’article de référence',
    credit: 'Image : visuel officiel EA SPORTS FC 27 — fiche joueur du mode Carrière, valeur marchande xTV calculée avec TransferRoom. © Electronic Arts.'
  },
  'netmarble-tgs-2026': {
    date: '21.09.2026', category: 'NETMARBLE · TOKYO GAME SHOW', image: 'tokyo-game-show-2026-news.jpg', imageAlt: 'Visuel officiel du Tokyo Game Show 2026', cover: 'NETMARBLE', video: 'NyGVobZDCgo', videoTitle: 'Netmarble TGS 2026 — live officielle',
    title: 'NETMARBLE QUITTE', accent: 'LE TGS AVEC TROIS JEUX.', dek: 'Le bilan publié le 21 septembre confirme trois projets jouables au Tokyo Game Show 2026 : Shangri-La Frontier: The Seven Colossi, Solo Leveling: KARMA et Pearl in Blue.',
    lead: 'Netmarble a clôturé sa deuxième participation consécutive au Tokyo Game Show avec un line-up qui joue la carte de la diversité. Trois projets à venir ont été présentés sur le salon, avec des démos et des animations sur scène.',
    intro: 'Le communiqué confirme un fait important, mais souvent noyé dans les annonces de salon : ces jeux ont été montrés, pas datés. Aucune date de sortie n’est annoncée dans ce bilan, et les questions de disponibilité internationale ou de modèle économique restent donc ouvertes.',
    h2: 'TROIS PROMESSES, TROIS FORMATS', p1: 'Shangri-La Frontier: The Seven Colossi a été présenté comme un RPG collectible à combats en équipe et a bénéficié de sa première démonstration jouable au TGS. Solo Leveling: KARMA, en développement pour mobile, assume une formule d’action roguelite dans l’univers de la licence, avec des combinaisons d’armes et de bonus.',
    quote: 'Un line-up jouable n’est pas encore un calendrier de sortie.', quoteBy: 'L’ANALYSE LET’S PLAY',
    h2b: 'PEARL IN BLUE GARDE LE MYSTÈRE', p2: 'Pearl in Blue complète ce trio avec une proposition originale centrée sur ses personnages et son univers. Netmarble y a montré une première expérience jouable, accompagnée d’un espace thématique et de contenus sur scène.', p3: 'Cette sélection dessine un portefeuille très lisible : une adaptation d’IP manga/anime, un dérivé mobile de Solo Leveling et une nouvelle licence. C’est une démonstration de direction, pas encore une promesse de lancement à court terme.', p4: 'Pour les joueurs, le prochain signal à surveiller sera donc moins une nouvelle bande-annonce qu’une fenêtre de sortie précise. En attendant, les trois titres restent des projets en développement dont le potentiel devra être jugé sur pièces.',
    take: 'RÉSUMÉ', takeText: 'Netmarble veut occuper le terrain avec trois projets déjà montrables, mais garde encore la décision la plus importante — quand y jouer — pour plus tard.', source: 'Communiqué Netmarble publié le 21.09.2026 via EQS News.', sourceUrl: 'https://www.eqs-news.com/news/corporate/netmarble-wraps-up-tokyo-game-show-2026-with-three-upcoming-titles/3fca48e2-6062-4712-8715-83b095654f1a_en', sourceDetail: 'Lire la source',
    sentiment: 'positive'
  },
  'control-resonant-24-septembre': {
    date: '21.09.2026', category: 'REMEDY · SORTIE', image: 'physint-news.jpg', imageAlt: 'Visuel éditorial Let’s Play sur l’action paranormale', cover: 'CONTROL RESONANT', video: 'JZuJlSGpgQo', videoTitle: 'CONTROL Resonant — Story Trailer officiel',
    title: 'CONTROL RESONANT ARRIVE', accent: 'À J-3.', dek: 'Le prochain jeu de Remedy sortira le 24 septembre 2026 sur PS5, Xbox Series et PC. La version Mac est annoncée pour plus tard dans l’année.',
    lead: 'Ce n’est pas une annonce surprise du 21 septembre, mais c’est le rendez-vous le plus concret de la semaine : CONTROL Resonant est désormais à trois jours de son lancement mondial.',
    intro: 'Remedy a fixé la sortie au 24 septembre sur PlayStation 5, Xbox Series X|S, Steam et l’Epic Games Store. Le studio annonce aussi une compatibilité GeForce NOW dès le lancement, tandis que la version Mac arrivera plus tard en 2026.',
    h2: 'UNE DATE, DES PLATEFORMES', p1: 'Le jeu place Dylan Faden au centre d’une nouvelle crise paranormale à Manhattan. Ces éléments relèvent de la présentation officielle de Remedy ; ils ne préjugent ni de l’accueil critique ni du succès commercial du titre.',
    quote: 'À J-3, le plus important est ce qui est verrouillé.', quoteBy: 'L’ANALYSE LET’S PLAY',
    h2b: 'LE MAC RESTE À L’ÉCART DU JOUR J', p2: 'La fenêtre Mac est bien confirmée pour 2026 via Steam et l’App Store, mais aucune date plus précise n’est donnée. Il serait donc prématuré de parler d’une sortie simultanée sur tous les supports.', p3: 'Le calendrier publié le 21 septembre par ActuGaming replace simplement CONTROL Resonant dans la semaine du 21 au 27 septembre. La date de l’article ne doit pas être confondue avec celle de l’annonce de Remedy, publiée le 2 juin.', p4: 'À trois jours du lancement, l’information utile tient en quelques lignes : plateformes confirmées, rendez-vous fixé, et une version Mac qui suivra. Le reste devra attendre que le jeu soit entre les mains des joueurs.',
    take: 'RÉSUMÉ', takeText: 'CONTROL Resonant arrive avec une fenêtre claire sur les consoles et le PC ; l’absence de date Mac laisse toutefois une partie du public dans l’attente.', source: 'Remedy Entertainment et calendrier ActuGaming consultés le 21.09.2026.', sourceUrl: 'https://www.remedygames.com/article/control-resonant-launches-worldwide-on-september-24', sourceDetail: 'Lire l’annonce de Remedy',
    sentiment: 'positive'
  },
  'sorties-24-septembre': {
    date: '21.09.2026', category: 'SORTIES · 24 SEPTEMBRE', image: 'monster-hunter-wilds-switch2.jpg', imageAlt: 'Visuel éditorial Let’s Play consacré aux sorties de la semaine', cover: '24 SEPTEMBRE', video: 'eXLfSEipn7I', videoTitle: 'Silent Hill: Townfall — trailer officiel',
    title: 'LE 24 SEPTEMBRE VA FAIRE', accent: 'DU BRUIT.', dek: 'CONTROL Resonant et Silent Hill: Townfall partagent la même date de sortie. Deux visions du paranormal se retrouvent face à face dans le calendrier de la semaine.',
    lead: 'La semaine du 21 au 27 septembre 2026 se concentre autour d’un jeudi particulièrement chargé. Les deux dates les plus solides du calendrier sont celles de CONTROL Resonant et Silent Hill: Townfall, tous deux annoncés pour le 24 septembre.',
    intro: 'Le premier mise sur l’action paranormale et le retour de Dylan Faden, tandis que le second suit Simon sur l’île de St. Amelia dans une expérience d’horreur à la première personne. Le point commun s’arrête presque là : leurs promesses de jeu visent deux publics voisins mais pas identiques.',
    h2: 'DEUX VISIONS DU PARANORMAL', p1: 'CONTROL Resonant arrivera sur PS5, Xbox Series X|S, Steam et Epic Games Store. Silent Hill: Townfall est confirmé sur PS5, avec une approche à la première personne, le CRTV comme outil d’exploration et une enquête au cœur de son dispositif.',
    quote: 'Deux sorties le même jour : le choix se fera au ton, pas seulement au calendrier.', quoteBy: 'L’ANALYSE LET’S PLAY',
    h2b: 'UN JEUDI À SUIVRE, PAS UN VERDICT', p2: 'Le calendrier publié le 21 septembre par ActuGaming confirme cette concentration autour du 24 septembre. Les annonces de référence sont toutefois antérieures : Remedy a communiqué le 2 juin et le PlayStation Blog les 16-17 septembre selon la région.', p3: 'Cette nuance compte. La sélection du jour est un repérage éditorial des sorties confirmées, pas une liste exhaustive de tous les jeux de la semaine et encore moins un classement de qualité.', p4: 'Pour les joueurs, la question devient très concrète : préférez-vous l’étrangeté systémique de Remedy ou l’angoisse plus resserrée de Konami ? Dans les deux cas, le 24 septembre mérite d’être marqué dans le calendrier.',
    take: 'RÉSUMÉ', takeText: 'Le 24 septembre concentre deux sorties très différentes : une semaine chargée qui mérite d’être planifiée, plutôt qu’une nouvelle annonce à surinterpréter.', source: 'ActuGaming, « Les sorties jeux vidéo de la semaine du 21 septembre », consulté le 21.09.2026.', sourceUrl: 'https://www.actugaming.net/les-sorties-jeux-video-de-la-semaine-du-21-septembre-control-resonant-silent-hill-townfall-826185/', sourceDetail: 'Lire le calendrier',
    sentiment: 'positive'
  },
  'kingdom-hearts-4-coco': {
    date: '15.09.2026', category: 'SQUARE ENIX · DISNEY', image: 'kingdom-hearts-4-coco-news.jpg', imageAlt: 'Kingdom Hearts 4 — Sora, le visage peint en calavera, brandit une Keyblade en forme de guitare dans le monde de Coco (capture du trailer officiel D23 2026)', cover: 'KINGDOM HEARTS 4',
    title: 'LE MONDE DE COCO', accent: 'N’A RIEN D’UN HASARD.', dek: 'Square Enix a glissé Sora au milieu d’une séquence Disney consacrée à Coco. Derrière l’effet de surprise, c’est peut-être le monde le plus raccord avec la saga depuis des années.',
    lead: 'Personne ne l’avait vu venir sous cette forme. Alors que Disney parlait de la suite de son film d’animation Coco, les images ont basculé et Sora est apparu à l’écran : ce n’était pas une bande-annonce de film, mais l’officialisation d’un des mondes inédits de Kingdom Hearts 4.',
    intro: 'La rumeur circulait depuis des mois dans la communauté, sans jamais dépasser le stade du bruit de couloir. L’annonce a donc fait son effet, et elle relance immédiatement la question que se pose la saga depuis son retour : qui choisit les mondes, et sur quels critères ?',
    h2: 'UNE ANNONCE DÉGUISÉE EN SÉQUENCE DISNEY', p1: 'Le premier réflexe est de voir la manœuvre marketing. Une suite de Coco est en préparation, Kingdom Hearts est une vitrine mondiale, et l’on a longtemps entendu que Disney poussait pour installer ses licences les plus fortes — jusqu’aux univers live-action — dans les prochains épisodes. L’hypothèse n’est pas absurde. Elle est juste très incomplète.',
    quote: 'Dans Coco, on meurt deux fois. La seconde quand plus personne, chez les vivants, ne se souvient de vous. Kingdom Hearts raconte ça depuis vingt ans.', quoteBy: 'Let’s Play · Le vrai point commun',
    h2b: 'LA SECONDE MORT, TERRAIN DE JEU FAVORI DE NOMURA', p2: 'Car sur le fond, peu de mondes Disney collent aussi bien à l’écriture de Tetsuya Nomura. Chez Coco, la mort n’est pas une fin mais un passage : le Pays des Morts est un endroit habité, organisé, où l’on continue d’exister tant que quelqu’un, de l’autre côté, vous garde en mémoire. Le jour où le souvenir s’efface, l’existence s’efface avec lui.',
    p3: 'C’est exactement la mécanique émotionnelle de Kingdom Hearts. Quand Xion disparaît et que son cœur rejoint celui de Sora, Roxas et Axel ne perdent pas une amie : ils perdent jusqu’au souvenir de son existence. La saga a passé des épisodes entiers à répéter qu’un personnage n’est rien d’autre que la somme des cœurs qui se souviennent de lui — et voilà un monde Disney construit sur cette règle, avec ses propres autels et ses propres photos.',
    p4: 'Le reste de la connexion tient au cœur lui-même, qui est dans les deux univers le siège de la mémoire et des émotions. Chez Coco, c’est la musique qui vient rouvrir ce qui était enfoui ; chez Kingdom Hearts, le cœur n’oublie jamais tout à fait et sert même de boussole — Sora ouvre bien un chemin vers le Colisée au début de Kingdom Hearts 3 en se fiant à ce qu’il ressent. Autrement dit : si Square Enix choisit ses mondes avec ce niveau de soin, les mois qui nous séparent de la sortie — calée fin 2027 — méritent qu’on y regarde de très près.',
    take: 'RÉSUMÉ', takeText: 'L’arrivée de Coco élargit encore la promesse de Kingdom Hearts 4 : Square Enix mise sur la surprise et la variété pour faire patienter jusqu’à 2027.',
    source: 'D’après l’analyse de jeuxvideo.com (17.08.2026) et le communiqué officiel Square Enix (15.08.2026).', sourceUrl: 'https://www.jeuxvideo.com/news/2099264/kingdom-hearts-4-ce-monde-disney-est-probablement-bien-plus-adapte-a-la-saga-qu-on-ne-l-imagine.htm', sourceDetail: 'Lire l’article original',
    credit: 'Image : capture du trailer officiel KINGDOM HEARTS IV — D23 2026. KINGDOM HEARTS © Disney. © Disney/Pixar. Developed by SQUARE ENIX.',
    sentiment: 'positive'
  },
  'wolverine-exclu-ps5': {
    date: '15.09.2026', category: 'SONY · INSOMNIAC GAMES', image: 'wolverine-countdown.jpg', imageAlt: 'Marvel’s Wolverine — Logan griffes sorties, key art officiel d’Insomniac Games', cover: 'WOLVERINE',
    title: 'MARVEL’S WOLVERINE', accent: 'FAIT DES JALOUX.', dek: 'Le jeu sort aujourd’hui, et uniquement sur PS5. Après deux heures manette en main chez Insomniac Games, on vous raconte pourquoi l’aventure de Logan est l’exclu que les joueurs PC et Xbox Series regardent de travers.',
    lead: 'Jour J pour le mutant. Marvel’s Wolverine débarque ce 15 septembre sur PS5, sans aucune autre machine à l’horizon. Un choix que Sony assume, et que deux heures de prise en main suffisent à expliquer : entre récit original, combats bestiaux et mise en scène de cinéma, Logan signe l’une des aventures les plus enviables de la génération.',
    intro: 'Le postulat de départ a de quoi décontenancer : dans cet univers, les X-Men n’existent pas. Les mutants sont bien là, mais aucune grande équipe ne défend leurs intérêts. Logan, retiré depuis trois ans, a autrefois appartenu à la Team X de Nathaniel Essex, aux côtés de Dents de Sabre, Mystique et Jean Grey. Quand Bolivar Trask commence à enlever des mutants, il n’a d’autre choix que de ressortir les griffes.',
    h2: 'UNE OUVERTURE QUI NE FAIT PAS DE QUARTIER', p1: 'Pas de préambule, pas de tutoriel déguisé en promenade : le jeu s’ouvre in media res à bord d’un hélicoptère pris pour cible par la DCA. Provocé par Dents de Sabre, Logan répond en se laissant tomber dans le vide, griffes sorties et double doigt d’honneur à l’appui. Oubliez la formule Spider-Man : Marvel’s Wolverine assume une aventure linéaire, ponctuée de zones semi-ouvertes, entièrement dédiée à la mise en scène.',
    quote: 'Un hélicoptère en feu, un saut dans le vide, un doigt d’honneur : en une scène, Logan est déjà chez lui.', quoteBy: 'Let’s Play · Carnet de prise en main',
    h2b: 'BESTIAL, MÊME QUAND IL SE FAIT DISCRET', p2: 'La linéarité n’empêche pas le voyage. Telambang, Madripoor, Tokyo : les décors, partiellement destructibles, mêlent réalisme et esthétique de comics modernes, portés par une caméra « in game » conçue sur mesure pour donner au jeu son grain de cinéma. C’est beau, c’est dense, et ça ne se dilue jamais.',
    p3: 'En combat, Insomniac ne retire rien : attaques, parades, esquives et exécutions sanglantes s’enchaînent dans un système qui célèbre la férocité du personnage. Même la furtivité reste brutale — Logan traque ses ennemis à l’odorat avant de les éliminer. Le tout s’appuie sur une progression light RPG : techniques, capacités spéciales et adaptations génétiques améliorent régénération, dégâts ou mobilité, pendant que des défis cachés débloquent des souvenirs perdus.',
    p4: 'Et puis il y a Jean Grey. Une scène particulièrement touchante laisse entrevoir un récit plus intime qu’attendu, qui explore autant la violence du mutant que les blessures de l’homme derrière les griffes. Ajoutez plusieurs dizaines de costumes et de griffes à personnaliser, et vous tenez l’exclu que tout le monde va regarder sortir… depuis une autre machine que la sienne. Notre verdict complet, lui, vous attend déjà dans la rubrique Tests.',
    take: 'RÉSUMÉ', takeText: 'Wolverine assume une direction plus resserrée et plus adulte : une aventure solo qui cherche son identité propre plutôt que de simplement collectionner les apparitions Marvel.',
    source: 'Basé sur la prise en main de jeuxvideo.com (15.08.2026).', sourceUrl: 'https://www.jeuxvideo.com/news/2096034/marvel-s-wolverine-l-exclu-ps5-enviee-par-tous-les-joueurs-pc-et-xbox-series.htm', sourceDetail: 'Lire l’article original',
    sentiment: 'positive'
  },
  'persona-6-switch-2': {
    date: '14.09.2026', category: 'SEGA · RPG', image: 'persona-6-news.jpg', imageAlt: 'Visuel officiel de l’univers Persona — site Atlus', cover: 'PERSONA 6',
    title: 'PERSONA 6 ARRIVE', accent: 'EN PHYSIQUE.', dek: 'Le prochain épisode de la série Persona sortira aussi en version physique sur Switch 2. Une bonne nouvelle pour les joueurs qui aiment garder leurs RPG près d’eux.',
    lead: 'SEGA avait déjà confirmé Persona 6 sur Switch 2, PS5, Xbox Series et PC. La console de Nintendo aura finalement droit à sa propre édition physique, en plus de la disponibilité numérique annoncée.',
    intro: 'La date de sortie reste inconnue, mais le projet commence à préciser son contour. Après l’annonce de la version physique sur PS5, la Switch 2 rejoint donc la liste des machines qui accueilleront le prochain grand RPG de SEGA.',
    h2: 'UNE CARTE QUI CHANGE TOUT', p1: 'Il faut toutefois garder une nuance importante : SEGA utilise régulièrement le format de la carte clé pour ses sorties physiques sur Switch 2. La boîte sera bien présente en magasin, mais le contenu pourrait nécessiter un téléchargement.',
    quote: 'Une édition physique, oui. Une cartouche complète, pas forcément.', quoteBy: 'Let’s Play · Ce qu’il faut retenir',
    h2b: 'LE GAME PASS DANS L’ÉQUATION', p2: 'Persona 6 sera également ajouté au Xbox Game Pass dès sa sortie. Une manière de toucher immédiatement un large public, alors que l’attente autour de la série dépasse depuis longtemps le cercle des habitués de Persona.', p3: 'Pour SEGA, le choix est cohérent : multiplier les portes d’entrée sans abandonner les collectionneurs. Les joueurs Switch 2 pourront choisir entre le confort du numérique et la présence d’une édition en boîte.', p4: 'Il reste maintenant à découvrir le jeu lui-même. Tant que la date, le prix et le contenu exact de la carte clé ne sont pas précisés, cette annonce doit surtout être lue comme un signe de confiance envers la nouvelle console.',
    take: 'RÉSUMÉ', takeText: 'Persona 6 devient un lancement multiplateforme dès le départ, un choix qui peut élargir son audience sans effacer l’importance de la version Switch 2.',
    sentiment: 'positive'
  },
  'last-of-us-ii-mod': {
    date: '14.09.2026', category: 'PLAYSTATION · PC', image: 'last-of-us-mod-news.jpg', imageAlt: 'The Last of Us Part II Remastered — visuel officiel PlayStation', cover: 'THE LAST OF US II',
    title: 'LE MULTIJOUEUR', accent: 'RESTE AU GARAGE.', dek: 'Un projet de mod voulait offrir une expérience multijoueur à la version PC de The Last of Us Part II. Sony a demandé son arrêt avant sa sortie.',
    lead: 'The Last of Us Part II Remastered est arrivé sur PC sans le mode multijoueur imaginé pendant le développement du jeu. Des fans ont tenté de combler ce manque avec un mod financé par leur communauté.',
    intro: 'L’équipe Specizer travaillait depuis janvier sur cette composante en ligne, avec une sortie envisagée ce mois-ci. Le projet avait trouvé son public grâce à Patreon et à plusieurs extraits diffusés en ligne.',
    h2: 'QUAND LES FANS REPRENNENT LE RELAIS', p1: 'L’histoire est révélatrice d’une attente qui n’a jamais vraiment disparu. Naughty Dog avait d’abord abandonné le multijoueur prévu pour The Last of Us Part II, avant de mettre fin à son projet connecté autonome. Les joueurs, eux, ont continué à imaginer ce que cet univers pouvait donner en ligne.',
    quote: 'Le projet devait sortir ce mois-ci. Il ne verra finalement jamais le jour.', quoteBy: 'Specizer · Message à sa communauté',
    h2b: 'UNE QUESTION DE DROITS, MAIS AUSSI DE CONTRÔLE', p2: 'Les moddeurs ont confirmé avoir reçu une lettre de Sony Interactive Entertainment leur demandant de ne pas publier le mod. Le contenu n’avait pas encore été officiellement lancé, mais ses images suffisaient à rendre le projet visible.', p3: 'La décision peut se comprendre du point de vue de l’éditeur : un mod non officiel qui reprend des éléments d’une licence protégée peut brouiller la frontière entre fan project et produit concurrent.', p4: 'Elle laisse malgré tout une frustration particulière. Après l’annulation du multijoueur officiel, cette tentative indépendante représentait l’une des rares façons de voir cette idée continuer à vivre. Les extraits encore disponibles témoignent surtout d’un projet qui n’aura pas eu le temps de rencontrer son public.',
    take: 'RÉSUMÉ', takeText: 'Le dossier rappelle la limite des projets communautaires autour des licences propriétaires : une idée prometteuse peut s’arrêter avant même d’avoir rencontré son public.',
    sentiment: 'negative'
  },
  'cyberpunk-2077-battlenet': {
    date: '14.09.2026', category: 'CD PROJEKT RED · PC', image: 'cyberpunk-2077-battlenet-news.webp', imageAlt: 'Cyberpunk 2077 Ultimate Edition — visuel officiel CD PROJEKT RED', cover: 'CYBERPUNK 2077',
    title: 'CYBERPUNK 2077', accent: 'CHANGE DE QUARTIER.', dek: 'L’Ultimate Edition rejoindra Battle.net plus tard cette année. CD Projekt RED et Blizzard continuent d’élargir leur partenariat autour de leurs grands RPG.',
    lead: 'Après The Witcher 3: Wild Hunt — Remastered, c’est au tour de Cyberpunk 2077: Ultimate Edition de prendre la direction de Battle.net. La sortie est confirmée pour 2026, sans date précise pour le moment.',
    intro: 'L’annonce s’inscrit dans un partenariat officialisé le 26 août entre CD Projekt RED et Blizzard. Le premier rendez-vous est fixé au 29 septembre avec The Witcher 3: Wild Hunt — Remastered, avant l’arrivée de Night City sur le même écosystème.',
    h2: 'NIGHT CITY SUR LE LAUNCHER BLIZZARD', p1: 'Pour les joueurs PC, le changement sera surtout une question d’écosystème. Cyberpunk 2077: Ultimate Edition regroupe déjà le jeu et son extension Phantom Liberty ; son arrivée sur Battle.net lui donnera une nouvelle vitrine auprès du public habitué aux jeux Blizzard.',
    quote: 'Deux univers de RPG, un même point d’entrée sur PC.', quoteBy: 'Let’s Play · L’enjeu de l’annonce',
    h2b: 'UN PARTENARIAT QUI PREND DE L’AMPLEUR', p2: 'Le choix n’est pas anodin. Battle.net est historiquement associé aux licences de Blizzard, mais la plateforme accueille aussi des jeux partenaires. The Witcher 3 puis Cyberpunk 2077 installent progressivement une passerelle entre deux publics de joueurs.', p3: 'Il faudra encore attendre les précisions pratiques : date exacte, prix, gestion des sauvegardes et éventuelles conditions pour les propriétaires de l’Ultimate Edition. Rien de tout cela n’a été détaillé à ce stade.', p4: 'Cette arrivée ne change pas le contenu de Cyberpunk 2077, mais elle confirme que CD Projekt RED cherche de nouveaux chemins de distribution pour ses jeux. Pour Night City, le prochain arrêt est donc connu ; le calendrier reste à écrire.',
    take: 'RÉSUMÉ', takeText: 'Cette arrivée complète la distribution de Cyberpunk 2077 sur PC, mais son intérêt dépendra surtout des avantages concrets de cette édition et de sa date réelle.',
    sentiment: 'positive'
  },
  'rayman-legends-retold': {
    date: '15.09.2026', category: 'UBISOFT · PLATEFORMES', image: 'rayman-legends-retold-news.jpg', imageAlt: 'Rayman Legends Retold — miniature officielle du trailer Ubisoft', cover: 'RAYMAN LEGENDS',
    title: 'RAYMAN RETOLD', accent: 'REPORTÉ À DÉCEMBRE.', dek: 'Le remaster ne sortira plus le 1er octobre. Ubisoft repousse le rendez-vous au 3 décembre 2026 pour peaufiner sa version.',
    lead: 'Les joueurs devront patienter quelques semaines de plus avant de retrouver Rayman. Alors que Rayman Legends Retold était attendu le 1er octobre 2026, Ubisoft vient d’annoncer un report au 3 décembre.',
    intro: 'Le changement concerne les versions PS5, Xbox Series, Switch 2 et PC. Le développement est présenté comme terminé, mais l’équipe souhaite profiter de ce délai supplémentaire pour améliorer les derniers détails et viser le niveau de qualité attendu pour ce retour.',
    h2: 'UN REPORT POUR POLIR LE REMASTER', p1: 'Ce décalage ne ressemble donc pas à une remise en question du projet. Rayman Legends Retold garde son calendrier de sortie et ses plateformes, tandis que les développeurs s’offrent un peu d’air pour finaliser l’expérience dans de meilleures conditions.',
    quote: 'Quelques semaines de plus pour laisser le remaster trouver son meilleur rythme.', quoteBy: 'Let’s Play · Le point calendrier',
    h2b: 'UN NOUVEAU RENDEZ-VOUS EN DÉCEMBRE', p2: 'La nouvelle date est fixée au 3 décembre 2026. Elle place le jeu au cœur d’une période chargée en sorties, mais offre aussi à Ubisoft une fenêtre supplémentaire pour présenter les nouveautés et les ajustements de cette version revisitée.', p3: 'Pour accompagner cette attente, une importante vidéo de gameplay est annoncée le 22 septembre. Ce sera l’occasion de voir plus concrètement le travail réalisé sur le remaster et de vérifier comment ses niveaux cultes se comportent sur les machines actuelles.', p4: 'Le rendez-vous change, mais l’envie reste intacte : Rayman Legends Retold vise toujours la PS5, les Xbox Series, la Switch 2 et le PC. Il faudra simplement attendre le début du mois de décembre pour lancer cette nouvelle partie.',
    take: 'RÉSUMÉ', takeText: 'Rayman revient dans une configuration large, avec une promesse qui devra maintenant se vérifier manette en main : la prochaine vidéo sera plus parlante que le calendrier.',
    sentiment: 'negative'
  },
  'fire-emblem-fortunes-weave': {
    date: '15.09.2026', category: 'NINTENDO · SWITCH 2', image: 'fire-emblem-fortunes-weave-news.jpg', imageAlt: 'Fire Emblem: Fortune’s Weave — visuel officiel Nintendo', cover: 'FIRE EMBLEM',
    title: 'FORTUNE’S WEAVE', accent: 'JOUE SA DERNIÈRE CARTE.', dek: 'À deux jours de sa sortie, Fire Emblem: Fortune’s Weave revient sur ses quatre destins et la liberté laissée aux joueurs pour les entrelacer.',
    lead: 'Le prochain Fire Emblem s’apprête à entrer en scène sur Nintendo Switch 2. Attendu le 17 septembre 2026, Fortune’s Weave profite de cette dernière ligne droite pour rappeler ce qui distingue son aventure : quatre protagonistes, quatre parcours et une destinée à reconstruire.',
    intro: 'Les héros sont présentés comme morts dans un futur proche avant de recevoir une seconde chance grâce à Eshmel, une oracle qui veut infléchir leur sort. Cette prémisse installe immédiatement l’enjeu du jeu : comprendre ce qui s’est brisé, puis réunir les fragments d’une histoire commune.',
    h2: 'QUATRE DESTINS, UNE SEULE ISSUE', p1: 'Chaque protagoniste dispose de son propre scénario, mais Fortune’s Weave ne cloisonne pas ces récits. Il sera possible de passer librement de l’un à l’autre afin de faire progresser les quatre fils narratifs et de viser la conclusion la plus favorable.',
    quote: 'Le joueur ne choisit plus seulement qui suivre : il choisit quand faire avancer chaque destin.', quoteBy: 'Let’s Play · La nouvelle mécanique narrative',
    h2b: 'ENTRE DEUX BATAILLES, LE TEMPS DES LIENS', p2: 'La formule stratégique reste familière aux habitués. Entre deux combats majeurs, le hub sert de point d’ancrage pour discuter avec les alliés, renforcer les soutiens, recruter de nouveaux personnages et explorer les environs.', p3: 'Ces moments de respiration ne sont pas qu’une parenthèse. Les échanges et les recrutements devraient nourrir la progression des quatre campagnes, tout en donnant au joueur les clés pour comprendre les enjeux de ce monde et les relations entre ses héros.', p4: 'La sortie est fixée au 17 septembre 2026, exclusivement sur Nintendo Switch 2. Une longue vidéo de présentation accompagne cette dernière étape et permet de revoir les bases de l’aventure avant de se lancer dans la bataille.',
    take: 'RÉSUMÉ', takeText: 'Fortune’s Weave mise sur la liberté de parcours pour renouveler la formule : son vrai défi sera de rendre ces choix aussi significatifs que nombreux.',
    sentiment: 'positive'
  },
  'tokyo-game-show-2026-annulation': {
    date: '20.09.2026', category: 'TOKYO GAME SHOW · JAPON', image: 'tokyo-game-show-2026-news.jpg', imageAlt: 'Visuel officiel Tokyo Game Show 2026 avec la mascotte de l’événement', cover: 'TGS 2026',
    title: 'LE TGS 2026', accent: 'PERD SON DERNIER JOUR.', dek: 'Le Tokyo Game Show annule officiellement sa journée du 21 septembre à cause de l’approche du typhon n°25. Le dimanche 20 reste maintenu, sous réserve des conditions locales.',
    lead: 'Le Tokyo Game Show 2026 n’ira pas jusqu’au bout de son programme initial. La CESA a annoncé le 19 septembre l’annulation complète de la journée du lundi 21, alors que le typhon n°25 doit renforcer les vents et les pluies sur la région de Tokyo.',
    intro: 'Le dimanche 20 septembre est maintenu comme prévu au Makuhari Messe, mais l’organisation demande aux visiteurs de surveiller la météo et les transports. Cette édition anniversaire, pensée pour durer cinq jours, se retrouve donc ramenée à quatre journées effectives.',
    h2: 'LA SÉCURITÉ PASSE AVANT LE SHOW', p1: 'La décision répond à un risque très concret : l’intensification annoncée des intempéries pourrait perturber les transports et compliquer le retour des visiteurs, exposants et équipes. La CESA a également prévenu que certaines installations ou activités du dimanche pourraient être modifiées si la situation l’exige.',
    quote: 'Le dimanche est maintenu. Le lundi est annulé pour permettre à chacun de rentrer en sécurité.', quoteBy: 'CESA · Avis officiel du 19 septembre 2026',
    h2b: 'UN PROGRAMME À SAUVER EN LIGNE', p2: 'Les billets du 21 septembre feront l’objet d’un remboursement via leur canal d’achat. Pour les scènes prévues ce jour-là, l’organisateur cherche encore à mettre en place des diffusions en ligne, sans avoir confirmé les contenus ni les horaires.', p3: 'L’enjeu dépasse la simple logistique. Le TGS célébrait ses trente ans et inaugurait un format de cinq jours ; cette annulation devient un précédent pour un salon déjà en pleine expansion. Les annonces importantes ne disparaissent pas forcément, mais leur mise en scène pourrait désormais passer par le numérique.', p4: 'À ce stade, le seul calendrier certain est celui du dimanche 20 septembre, maintenu sur place. Le reste dépendra de la trajectoire du typhon et des prochaines communications officielles de la CESA.',
    take: 'RÉSUMÉ', takeText: 'L’annulation perturbe le rendez-vous sans effacer son intérêt : les annonces importantes pourraient simplement se déplacer vers les formats numériques.', source: 'D’après l’avis officiel de la CESA publié le 19.09.2026.', sourceUrl: 'https://tgs.cesa.or.jp/2026/en/news/detail/00061', sourceDetail: 'Lire l’avis officiel', credit: 'Image : visuel officiel Tokyo Game Show 2026. © CESA / Nikkei Business Publications.',
    sentiment: 'negative'
  },
  'eshop-switch-2-20-septembre': {
    date: '20.09.2026', category: 'NINTENDO · SWITCH 2', image: 'fire-emblem-fortunes-weave-news.jpg', imageAlt: 'Fire Emblem: Fortune’s Weave — visuel officiel Nintendo', cover: 'ESHOP SWITCH 2',
    title: 'FIRE EMBLEM', accent: 'GARDE LA PREMIÈRE PLACE.', dek: 'Dans les classements eShop Switch 2 de la semaine du 20 septembre, Fortune’s Weave reste numéro un devant Diablo 4 et les deux éditions de LEGO Batman.',
    lead: 'Fire Emblem: Fortune’s Weave conserve la tête des ventes sur l’eShop de la Nintendo Switch 2 pour la semaine du 20 septembre 2026. Le RPG stratégique de Nintendo devance Diablo 4, arrivé quelques jours plus tôt, et les deux éditions de LEGO Batman: Legacy of the Dark Knight.',
    intro: 'Le résultat prolonge l’effet du préchargement commencé la semaine précédente : Fortune’s Weave était déjà installé en tête avant sa sortie. Le classement ne mesure donc pas uniquement les achats du week-end, mais il donne une première photographie de la demande autour du nouveau Fire Emblem.',
    h2: 'UN DUEL ENTRE NOUVEAUTÉS', p1: 'Le deuxième rang de Diablo 4 est le signal le plus parlant. Le jeu de Blizzard s’installe immédiatement derrière une exclusivité Switch 2, tandis que LEGO Batman occupe les troisième et quatrième places avec ses éditions standard et Deluxe. Le haut du tableau reste ainsi dominé par des licences déjà très identifiables.',
    quote: 'Fortune’s Weave reste numéro un ; Diablo 4 prend la tête du classement des jeux uniquement numériques.', quoteBy: 'Let’s Play · Lecture des classements du 20 septembre',
    h2b: 'LA SWITCH 2 ÉLARGIT SON ÉVENTAIL', p2: 'Le reste du top 10 montre une console qui accueille désormais des profils très différents : RuneScape: Dragonwilds arrive sixième, tandis que Trails in the Sky 2nd Chapter se place neuvième. Entre RPG, jeux-service et grands portages, l’eShop ne dépend plus d’un seul type de sortie.', p3: 'Il faut toutefois garder une nuance : ce tableau est un classement de ventes, pas un baromètre de qualité ni un chiffre de ventes communiqué par Nintendo. Il indique une hiérarchie à un instant donné, avec l’effet des précommandes et des éditions multiples.', p4: 'Pour Fortune’s Weave, le premier signal reste favorable. Sa première place confirme l’intérêt du public pour une aventure stratégique pensée autour de quatre destins, alors que le jeu entre dans sa première semaine complète de disponibilité.',
    take: 'RÉSUMÉ', takeText: 'Ce classement montre que Fire Emblem bénéficie déjà d’une forte visibilité sur Switch 2, mais ne suffit pas encore à mesurer son endurance commerciale.', source: 'Classement publié par Nintendo Everything le 20.09.2026.', sourceUrl: 'https://nintendoeverything.com/nintendo-switch-2-eshop-charts-september-20-2026/', sourceDetail: 'Voir le classement complet', credit: 'Image : visuel officiel Nintendo de Fire Emblem: Fortune’s Weave.',
    sentiment: 'positive'
  },
  'sony-licence-jeux-numeriques': {
    date: '20.09.2026', category: 'PLAYSTATION · JUSTICE', image: 'playstation-store-ownership-news.jpg', imageAlt: 'Interface officielle du PlayStation Store présentée par Sony Interactive Entertainment', cover: 'PLAYSTATION STORE',
    title: 'VOUS ACHETEZ UN JEU', accent: 'OU UNE LICENCE ?', dek: 'Dans une action collective en Californie, Sony soutient qu’un consommateur raisonnable sait qu’un achat numérique sur le PlayStation Store ne transfère pas la propriété du jeu.',
    lead: 'Le mot « acheter » vaut-il encore ce qu’il promet dans une boutique numérique ? C’est la question posée par une plainte collective déposée en Californie contre Sony. En réponse, l’entreprise affirme que les joueurs obtiennent une licence personnelle d’utilisation, et non la propriété du jeu téléchargé.',
    intro: 'L’affaire concerne quatre consommateurs qui reprochent au PlayStation Store d’employer des formulations comme « Buy Now » et « Confirm Purchase » sans expliquer assez clairement, au moment de la transaction, que l’accès reste encadré par les conditions de licence de PlayStation. Sony cherche pour sa part à faire rejeter la procédure ou à empêcher son traitement comme action collective.',
    h2: 'LE MOT « ACHETER » AU CŒUR DU DOSSIER', p1: 'La plainte s’appuie sur la loi californienne AB 2426, qui encadre depuis 2025 l’emploi de termes comme « buy » ou « purchase » pour des biens numériques. Lorsqu’une plateforme ne vend pas une propriété illimitée mais accorde une licence, elle doit le signaler de manière claire et visible avant la transaction, selon l’interprétation défendue par les plaignants.',
    quote: 'Le logiciel est concédé sous licence, et non vendu.', quoteBy: 'Conditions d’utilisation PlayStation, citées dans la procédure',
    h2b: 'UNE LICENCE N’EST PAS UNE LOCATION ORDINAIRE', p2: 'La nuance mérite d’être posée précisément. Un jeu numérique acheté sur le Store reste attaché au compte de l’utilisateur et peut être téléchargé selon les conditions de PlayStation. Mais le contrat ne décrit pas cette opération comme un transfert de propriété : il accorde un droit d’utilisation personnel, soumis aux règles du service et présenté comme révocable.', p3: 'Sony avance qu’il serait peu plausible qu’un consommateur raisonnable confonde cette licence avec la possession d’un objet physique. L’entreprise prend notamment l’exemple de Resident Evil Requiem : plusieurs personnes peuvent acheter le même fichier numérique, ce qui distingue cette transaction d’un bien matériel vendu une seule fois.', p4: 'C’est précisément ce raisonnement que la justice devra examiner. Le dossier ne signifie pas que les jeux déjà achetés vont disparaître, ni que Sony a déjà été condamné. Il pose une question de transparence : les conditions générales et les liens de licence sont-ils suffisamment visibles pour corriger l’impression créée par le bouton « Acheter » ?',
    take: 'RÉSUMÉ', takeText: 'L’enjeu dépasse Sony : cette affaire peut clarifier la manière dont les plateformes doivent présenter la propriété, la licence et les droits réels liés à un achat numérique.', source: 'Réécrit à partir de l’article Jeuxvideo.com du 20.09.2026, recoupé avec CNET et Polygon.', sourceUrl: 'https://www.jeuxvideo.com/news/2104611/les-joueurs-ne-possedent-pas-leurs-jeux-ps5-ils-ne-font-que-les-louer-sony-l-affirme-en-justice.htm', sourceDetail: 'Lire l’article de référence', credit: 'Image : visuel officiel PlayStation Store — Sony Interactive Entertainment.',
    sentiment: 'negative'
  }
};

function Arrow(){ return <span aria-hidden="true">↗</span>; }

export default function CurrentNews({ slug }) {
  const routeSlug = useParams().slug;
  const allStories = { ...autoStories, ...stories };
  const key = slug || routeSlug;
  const story = key ? allStories[key] : stories['persona-6-switch-2'];
  if (!story) return <NotFound />;
  const articleId = `/news/${key}`;
  const sentimentId = inferSentimentForStory(story);
  const meta = sentimentMeta(sentimentId);
  const [views, setViews] = useState(null);

  useEffect(() => {
    let cancelled = false;
    // Incrément global (anti-spam 30 min par navigateur) + lecture du total
    incrementArticleView(articleId).catch(() => {});
    getArticleViews([articleId]).then((map) => {
      if (!cancelled) setViews(map[normalizeArticleId(articleId)] ?? null);
    });
    // Rafraîchit le total après l'incrément (le RPC retourne déjà la valeur,
    // mais on relit pour couvrir le fallback local).
    const t = setTimeout(() => {
      getArticleViews([articleId]).then((map) => {
        if (!cancelled) setViews(map[normalizeArticleId(articleId)] ?? null);
      });
    }, 900);
    return () => { cancelled = true; clearTimeout(t); };
  }, [articleId]);

  return <>
    <section className="article-hero wrap"><div className="section-label"><span>ACTUS À LA UNE</span><span>{story.date} · {story.category}</span></div><div className="article-heading"><div><p className="eyebrow"><span className="live-dot" /> {story.auto ? 'ACTU DU JOUR · LET’S PLAY' : 'RÉÉCRIT POUR LET’S PLAY'}</p><h1>{story.title}<br/><em>{story.accent}</em></h1><p className="article-dek">{story.dek}</p><div className="article-byline"><span>LET’S PLAY</span><span>4 MIN DE LECTURE</span>{views != null && <span className="article-views-inline"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true" width="14" height="14"><path d="M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12z" /><circle cx="12" cy="12" r="3.2" /></svg> {formatViews(views)} vues</span>}<span className={`article-sentiment-inline ${meta.color}`} title={meta.label}>{meta.emoji} {meta.label}</span></div></div><div className="article-cover hud-frame"><img src={`${base}${story.thumbnail || story.image}`} alt={story.imageAlt} /><div><small>{story.category}</small><strong>{story.cover}</strong></div><span className={`news-sentiment ${meta.color}`} style={{ top: 12, right: 12 }} aria-label={meta.label} title={meta.label}>{meta.emoji}</span>{views != null && <span className="news-views" style={{ left: 12, bottom: 12 }}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12z" /><circle cx="12" cy="12" r="3.2" /></svg>{formatViews(views)}</span>}</div></div></section>
    <main className="article-layout wrap"><article className="article-body"><p className="article-lead">{story.lead}</p>{story.intro ? <p>{story.intro}</p> : null}{story.video ? <section className="article-video"><div className="section-label"><span><b>VIDÉO</b> / OFFICIELLE</span><span>{story.category}</span></div><div className="article-video-frame"><iframe src={youTubeEmbedUrl(story.video)} title={story.videoTitle} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><p className="article-source">Vidéo officielle : {story.videoTitle} · <a href={`https://www.youtube.com/watch?v=${story.video}`} target="_blank" rel="noreferrer">Voir sur YouTube</a></p></section> : null}<h2>{story.h2}</h2><p>{story.p1}</p>{story.quote ? <div className="article-pullquote"><span>“</span><p>{story.quote}</p><small>{story.quoteBy}</small></div> : null}{story.p2 ? <p>{story.p2}</p> : null}{story.p3 ? <><h2>{story.h2b}</h2><p>{story.p3}</p></> : null}<p>{story.p4}</p>{story.takeText ? <div className="article-endnote"><span className="live-dot" /><strong>{story.take}</strong><span>{story.takeText}</span></div> : null}{story.source ? <p className="article-source">{story.source} <a href={story.sourceUrl} target="_blank" rel="noreferrer">{story.sourceDetail}</a></p> : null}{story.credit ? <p className="article-source">{story.credit}</p> : null}</article><aside className="article-aside"><div className="aside-card"><span className="aside-kicker">EN BREF</span><strong>{story.date}</strong><strong>{story.category}</strong><strong>{story.auto ? 'ACTU DU JOUR · SOURCÉE' : 'LET’S PLAY ORIGINAL'}</strong>{views != null && <><span className="aside-kicker" style={{ marginTop: 14 }}>VUES GLOBALES</span><strong>{formatViews(views)} vues</strong></>}<span className="aside-kicker" style={{ marginTop: 14 }}>TON DE L’ACTU</span><strong className={`sentiment-text ${meta.color}`}>{meta.emoji} {meta.label}</strong></div><div className="aside-card aside-card-accent"><span className="aside-kicker">À LIRE AUSSI</span><strong>LES ACTUS À LA UNE</strong><p>Retrouvez les dernières annonces et analyses de la rédaction.</p><Link className="arrow-link" to="/news">RETOUR AUX ACTUS <Arrow/></Link></div></aside></main>
    <ArticleEngagement articleId={`/news/${key}`} title={`${story.title} ${story.accent}`} />
    <Comments />
    <section className="cta wrap"><div><p className="eyebrow"><span className="live-dot" /> LA SUITE SUR LET’S PLAY</p><h2>RESTEZ DANS<br/><em>LE GAME.</em></h2></div><Link className="button button-yellow" to="/news">VOIR LES ACTUS <Arrow/></Link></section>
  </>;
}

export { stories };
