import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { baseUrl as base } from '../data';
import Comments from '../components/Comments';

const stories = {
  'kingdom-hearts-4-coco': {
    date: '15.09.2026', category: 'SQUARE ENIX · DISNEY', image: 'kingdom-hearts-4-coco-news.jpg', imageAlt: 'Kingdom Hearts 4 — Sora, le visage peint en calavera, brandit une Keyblade en forme de guitare dans le monde de Coco (capture du trailer officiel D23 2026)', cover: 'KINGDOM HEARTS 4',
    title: 'LE MONDE DE COCO', accent: 'N’A RIEN D’UN HASARD.', dek: 'Square Enix a glissé Sora au milieu d’une séquence Disney consacrée à Coco. Derrière l’effet de surprise, c’est peut-être le monde le plus raccord avec la saga depuis des années.',
    lead: 'Personne ne l’avait vu venir sous cette forme. Alors que Disney parlait de la suite de son film d’animation Coco, les images ont basculé et Sora est apparu à l’écran : ce n’était pas une bande-annonce de film, mais l’officialisation d’un des mondes inédits de Kingdom Hearts 4.',
    intro: 'La rumeur circulait depuis des mois dans la communauté, sans jamais dépasser le stade du bruit de couloir. L’annonce a donc fait son effet, et elle relance immédiatement la question que se pose la saga depuis son retour : qui choisit les mondes, et sur quels critères ?',
    h2: 'UNE ANNONCE DÉGUISÉE EN SÉQUENCE DISNEY', p1: 'Le premier réflexe est de voir la manœuvre marketing. Une suite de Coco est en préparation, Kingdom Hearts est une vitrine mondiale, et l’on a longtemps entendu que Disney poussait pour installer ses licences les plus fortes — jusqu’aux univers live-action — dans les prochains épisodes. L’hypothèse n’est pas absurde. Elle est juste très incomplète.',
    quote: 'Dans Coco, on meurt deux fois. La seconde quand plus personne, chez les vivants, ne se souvient de vous. Kingdom Hearts raconte ça depuis vingt ans.', quoteBy: 'Let’s Play · Le vrai point commun',
    h2b: 'LA SECONDE MORT, TERRAIN DE JEU FAVORI DE NOMURA', p2: 'Car sur le fond, peu de mondes Disney collent aussi bien à l’écriture de Tetsuya Nomura. Chez Coco, la mort n’est pas une fin mais un passage : le Pays des Morts est un endroit habité, organisé, où l’on continue d’exister tant que quelqu’un, de l’autre côté, vous garde en mémoire. Le jour où le souvenir s’efface, l’existence s’efface avec lui.',
    p3: 'C’est exactement la mécanique émotionnelle de Kingdom Hearts. Quand Xion disparaît et que son cœur rejoint celui de Sora, Roxas et Axel ne perdent pas une amie : ils perdent jusqu’au souvenir de son existence. La saga a passé des épisodes entiers à répéter qu’un personnage n’est rien d’autre que la somme des cœurs qui se souviennent de lui — et voilà un monde Disney construit sur cette règle, avec ses propres autels et ses propres photos.',
    p4: 'Le reste de la connexion tient au cœur lui-même, qui est dans les deux univers le siège de la mémoire et des émotions. Chez Coco, c’est la musique qui vient rouvrir ce qui était enfoui ; chez Kingdom Hearts, le cœur n’oublie jamais tout à fait et sert même de boussole — Sora ouvre bien un chemin vers le Colisée au début de Kingdom Hearts 3 en se fiant à ce qu’il ressent. Autrement dit : si Square Enix choisit ses mondes avec ce niveau de soin, les mois qui nous séparent de la sortie — calée fin 2027 — méritent qu’on y regarde de très près.',
    take: 'À RETENIR', takeText: 'Le monde de Coco est confirmé parmi les univers inédits de Kingdom Hearts 4, attendu fin 2027 sur PS5, Xbox Series X|S, Switch 2 et PC.',
    source: 'D’après l’analyse de jeuxvideo.com (17.08.2026) et le communiqué officiel Square Enix (15.08.2026).', sourceUrl: 'https://www.jeuxvideo.com/news/2099264/kingdom-hearts-4-ce-monde-disney-est-probablement-bien-plus-adapte-a-la-saga-qu-on-ne-l-imagine.htm', sourceDetail: 'Lire l’article original',
    credit: 'Image : capture du trailer officiel KINGDOM HEARTS IV — D23 2026. KINGDOM HEARTS © Disney. © Disney/Pixar. Developed by SQUARE ENIX.'
  },
  'wolverine-exclu-ps5': {
    date: '15.09.2026', category: 'SONY · INSOMNIAC GAMES', image: 'wolverine-countdown.jpg', imageAlt: 'Marvel’s Wolverine — Logan griffes sorties, key art officiel d’Insomniac Games', cover: 'WOLVERINE',
    title: 'MARVEL’S WOLVERINE', accent: 'FAIT DES JALOUX.', dek: 'Le jeu sort aujourd’hui, et uniquement sur PS5. Après deux heures manette en main chez Insomniac Games, on vous raconte pourquoi l’aventure de Logan est l’exclu que les joueurs PC et Xbox Series regardent de travers.',
    lead: 'Jour J pour le mutant. Marvel’s Wolverine débarque ce 15 septembre sur PS5, sans aucune autre machine à l’horizon. Un choix que Sony assume, et que deux heures de prise en main suffisent à expliquer : entre récit original, combats bestiaux et mise en scène de cinéma, Logan signe l’une des aventures les plus enviables de la génération.',
    intro: 'Le postulat de départ a de quoi décontenancer : dans cet univers, les X-Men n’existent pas. Les mutants sont bien là, mais aucune grande équipe ne défend leurs intérêts. Logan, retiré depuis trois ans, a autrefois appartenu à la Team X de Nathaniel Essex, aux côtés de Dents de Sabre, Mystique et Jean Grey. Quand Bolivar Trask commence à enlever des mutants, il n’a d’autre choix que de ressortir les griffes.',
    h2: 'UNE OUVERTURE QUI NE FAIT PAS DE QUARTIER', p1: 'Pas de préambule, pas de tutoriel déguisé en promenade : le jeu s’ouvre in media res à bord d’un hélicoptère pris pour cible par la DCA. Provocé par Dents de Sabre, Logan répond en se laissant tomber dans le vide, griffes sorties et double doigt d’honneur à l’appui. Oubliez la formule Spider-Man : Marvel’s Wolverine assume une aventure linéaire, ponctuée de zones semi-ouvertes, entièrement dédiée à la mise en scène.',
    quote: 'Un hélicoptère en feu, un saut dans le vide, un doigt d’honneur : en une scène, Logan est déjà chez lui.', quoteBy: 'Let’s Play · Carnet de prise en main',
    h2b: 'BESTIAL, MÊME QUAND IL SE FAIT DISCRET', p2: 'La linéarité n’empêche pas le voyage. Telambang, Madripoor, Tokyo : les décors, partiellement destructibles, mêlent réalisme et esthétique de comics modernes, portés par une caméra « in game » conçue sur mesure pour donner au jeu son grain de cinéma. C’est beau, c’est dense, et ça ne se dilue jamais.',
    p3: 'En combat, Insomniac ne retire rien : attaques, parades, esquives et exécutions sanglantes s’enchaînent dans un système qui célèbre la férocité du personnage. Même la furtivité reste brutale — Logan traque ses ennemis à l’odorat avant de les éliminer. Le tout s’appuie sur une progression light RPG : techniques, capacités spéciales et adaptations génétiques améliorent régénération, dégâts ou mobilité, pendant que des défis cachés débloquent des souvenirs perdus.',
    p4: 'Et puis il y a Jean Grey. Une scène particulièrement touchante laisse entrevoir un récit plus intime qu’attendu, qui explore autant la violence du mutant que les blessures de l’homme derrière les griffes. Ajoutez plusieurs dizaines de costumes et de griffes à personnaliser, et vous tenez l’exclu que tout le monde va regarder sortir… depuis une autre machine que la sienne. Notre verdict complet, lui, vous attend déjà dans la rubrique Tests.',
    take: 'À RETENIR', takeText: 'Marvel’s Wolverine est disponible ce 15 septembre 2026, uniquement sur PS5 : une aventure linéaire et brutale, portée par un récit original sans X-Men et une mise en scène de cinéma.',
    source: 'Basé sur la prise en main de jeuxvideo.com (15.08.2026).', sourceUrl: 'https://www.jeuxvideo.com/news/2096034/marvel-s-wolverine-l-exclu-ps5-enviee-par-tous-les-joueurs-pc-et-xbox-series.htm', sourceDetail: 'Lire l’article original'
  },
  'persona-6-switch-2': {
    date: '14.09.2026', category: 'SEGA · RPG', image: 'persona-6-news.jpg', imageAlt: 'Visuel officiel de l’univers Persona — site Atlus', cover: 'PERSONA 6',
    title: 'PERSONA 6 ARRIVE', accent: 'EN PHYSIQUE.', dek: 'Le prochain épisode de la série Persona sortira aussi en version physique sur Switch 2. Une bonne nouvelle pour les joueurs qui aiment garder leurs RPG près d’eux.',
    lead: 'SEGA avait déjà confirmé Persona 6 sur Switch 2, PS5, Xbox Series et PC. La console de Nintendo aura finalement droit à sa propre édition physique, en plus de la disponibilité numérique annoncée.',
    intro: 'La date de sortie reste inconnue, mais le projet commence à préciser son contour. Après l’annonce de la version physique sur PS5, la Switch 2 rejoint donc la liste des machines qui accueilleront le prochain grand RPG de SEGA.',
    h2: 'UNE CARTE QUI CHANGE TOUT', p1: 'Il faut toutefois garder une nuance importante : SEGA utilise régulièrement le format de la carte clé pour ses sorties physiques sur Switch 2. La boîte sera bien présente en magasin, mais le contenu pourrait nécessiter un téléchargement.',
    quote: 'Une édition physique, oui. Une cartouche complète, pas forcément.', quoteBy: 'Let’s Play · Ce qu’il faut retenir',
    h2b: 'LE GAME PASS DANS L’ÉQUATION', p2: 'Persona 6 sera également ajouté au Xbox Game Pass dès sa sortie. Une manière de toucher immédiatement un large public, alors que l’attente autour de la série dépasse depuis longtemps le cercle des habitués de Persona.', p3: 'Pour SEGA, le choix est cohérent : multiplier les portes d’entrée sans abandonner les collectionneurs. Les joueurs Switch 2 pourront choisir entre le confort du numérique et la présence d’une édition en boîte.', p4: 'Il reste maintenant à découvrir le jeu lui-même. Tant que la date, le prix et le contenu exact de la carte clé ne sont pas précisés, cette annonce doit surtout être lue comme un signe de confiance envers la nouvelle console.',
    take: 'À RETENIR', takeText: 'Persona 6 est annoncé sur Switch 2, PS5, Xbox Series et PC, avec une édition physique prévue sur Switch 2.'
  },
  'last-of-us-ii-mod': {
    date: '14.09.2026', category: 'PLAYSTATION · PC', image: 'last-of-us-mod-news.jpg', imageAlt: 'The Last of Us Part II Remastered — visuel officiel PlayStation', cover: 'THE LAST OF US II',
    title: 'LE MULTIJOUEUR', accent: 'RESTE AU GARAGE.', dek: 'Un projet de mod voulait offrir une expérience multijoueur à la version PC de The Last of Us Part II. Sony a demandé son arrêt avant sa sortie.',
    lead: 'The Last of Us Part II Remastered est arrivé sur PC sans le mode multijoueur imaginé pendant le développement du jeu. Des fans ont tenté de combler ce manque avec un mod financé par leur communauté.',
    intro: 'L’équipe Specizer travaillait depuis janvier sur cette composante en ligne, avec une sortie envisagée ce mois-ci. Le projet avait trouvé son public grâce à Patreon et à plusieurs extraits diffusés en ligne.',
    h2: 'QUAND LES FANS REPRENNENT LE RELAIS', p1: 'L’histoire est révélatrice d’une attente qui n’a jamais vraiment disparu. Naughty Dog avait d’abord abandonné le multijoueur prévu pour The Last of Us Part II, avant de mettre fin à son projet connecté autonome. Les joueurs, eux, ont continué à imaginer ce que cet univers pouvait donner en ligne.',
    quote: 'Le projet devait sortir ce mois-ci. Il ne verra finalement jamais le jour.', quoteBy: 'Specizer · Message à sa communauté',
    h2b: 'UNE QUESTION DE DROITS, MAIS AUSSI DE CONTRÔLE', p2: 'Les moddeurs ont confirmé avoir reçu une lettre de Sony Interactive Entertainment leur demandant de ne pas publier le mod. Le contenu n’avait pas encore été officiellement lancé, mais ses images suffisaient à rendre le projet visible.', p3: 'La décision peut se comprendre du point de vue de l’éditeur : un mod non officiel qui reprend des éléments d’une licence protégée peut brouiller la frontière entre fan project et produit concurrent.', p4: 'Elle laisse malgré tout une frustration particulière. Après l’annulation du multijoueur officiel, cette tentative indépendante représentait l’une des rares façons de voir cette idée continuer à vivre. Les extraits encore disponibles témoignent surtout d’un projet qui n’aura pas eu le temps de rencontrer son public.',
    take: 'À RETENIR', takeText: 'Sony a demandé l’arrêt du mod multijoueur PC de The Last of Us Part II avant sa publication.'
  },
  'cyberpunk-2077-battlenet': {
    date: '14.09.2026', category: 'CD PROJEKT RED · PC', image: 'cyberpunk-2077-battlenet-news.webp', imageAlt: 'Cyberpunk 2077 Ultimate Edition — visuel officiel CD PROJEKT RED', cover: 'CYBERPUNK 2077',
    title: 'CYBERPUNK 2077', accent: 'CHANGE DE QUARTIER.', dek: 'L’Ultimate Edition rejoindra Battle.net plus tard cette année. CD Projekt RED et Blizzard continuent d’élargir leur partenariat autour de leurs grands RPG.',
    lead: 'Après The Witcher 3: Wild Hunt — Remastered, c’est au tour de Cyberpunk 2077: Ultimate Edition de prendre la direction de Battle.net. La sortie est confirmée pour 2026, sans date précise pour le moment.',
    intro: 'L’annonce s’inscrit dans un partenariat officialisé le 26 août entre CD Projekt RED et Blizzard. Le premier rendez-vous est fixé au 29 septembre avec The Witcher 3: Wild Hunt — Remastered, avant l’arrivée de Night City sur le même écosystème.',
    h2: 'NIGHT CITY SUR LE LAUNCHER BLIZZARD', p1: 'Pour les joueurs PC, le changement sera surtout une question d’écosystème. Cyberpunk 2077: Ultimate Edition regroupe déjà le jeu et son extension Phantom Liberty ; son arrivée sur Battle.net lui donnera une nouvelle vitrine auprès du public habitué aux jeux Blizzard.',
    quote: 'Deux univers de RPG, un même point d’entrée sur PC.', quoteBy: 'Let’s Play · L’enjeu de l’annonce',
    h2b: 'UN PARTENARIAT QUI PREND DE L’AMPLEUR', p2: 'Le choix n’est pas anodin. Battle.net est historiquement associé aux licences de Blizzard, mais la plateforme accueille aussi des jeux partenaires. The Witcher 3 puis Cyberpunk 2077 installent progressivement une passerelle entre deux publics de joueurs.', p3: 'Il faudra encore attendre les précisions pratiques : date exacte, prix, gestion des sauvegardes et éventuelles conditions pour les propriétaires de l’Ultimate Edition. Rien de tout cela n’a été détaillé à ce stade.', p4: 'Cette arrivée ne change pas le contenu de Cyberpunk 2077, mais elle confirme que CD Projekt RED cherche de nouveaux chemins de distribution pour ses jeux. Pour Night City, le prochain arrêt est donc connu ; le calendrier reste à écrire.',
    take: 'À RETENIR', takeText: 'Cyberpunk 2077: Ultimate Edition arrivera sur Battle.net plus tard en 2026, sans date précise annoncée.'
  },
  'rayman-legends-retold': {
    date: '15.09.2026', category: 'UBISOFT · PLATEFORMES', image: 'rayman-legends-retold-news.jpg', imageAlt: 'Rayman Legends Retold — miniature officielle du trailer Ubisoft', cover: 'RAYMAN LEGENDS',
    title: 'RAYMAN LEGENDS RETOLD', accent: 'PREND UN PEU DE RETARD.', dek: 'Le remaster ne sortira plus le 1er octobre. Ubisoft repousse le rendez-vous au 3 décembre 2026 pour peaufiner sa version.',
    lead: 'Les joueurs devront patienter quelques semaines de plus avant de retrouver Rayman. Alors que Rayman Legends Retold était attendu le 1er octobre 2026, Ubisoft vient d’annoncer un report au 3 décembre.',
    intro: 'Le changement concerne les versions PS5, Xbox Series, Switch 2 et PC. Le développement est présenté comme terminé, mais l’équipe souhaite profiter de ce délai supplémentaire pour améliorer les derniers détails et viser le niveau de qualité attendu pour ce retour.',
    h2: 'UN REPORT POUR POLIR LE REMASTER', p1: 'Ce décalage ne ressemble donc pas à une remise en question du projet. Rayman Legends Retold garde son calendrier de sortie et ses plateformes, tandis que les développeurs s’offrent un peu d’air pour finaliser l’expérience dans de meilleures conditions.',
    quote: 'Quelques semaines de plus pour laisser le remaster trouver son meilleur rythme.', quoteBy: 'Let’s Play · Le point calendrier',
    h2b: 'UN NOUVEAU RENDEZ-VOUS EN DÉCEMBRE', p2: 'La nouvelle date est fixée au 3 décembre 2026. Elle place le jeu au cœur d’une période chargée en sorties, mais offre aussi à Ubisoft une fenêtre supplémentaire pour présenter les nouveautés et les ajustements de cette version revisitée.', p3: 'Pour accompagner cette attente, une importante vidéo de gameplay est annoncée le 22 septembre. Ce sera l’occasion de voir plus concrètement le travail réalisé sur le remaster et de vérifier comment ses niveaux cultes se comportent sur les machines actuelles.', p4: 'Le rendez-vous change, mais l’envie reste intacte : Rayman Legends Retold vise toujours la PS5, les Xbox Series, la Switch 2 et le PC. Il faudra simplement attendre le début du mois de décembre pour lancer cette nouvelle partie.',
    take: 'À RETENIR', takeText: 'Rayman Legends Retold sortira le 3 décembre 2026 sur PS5, Xbox Series, Switch 2 et PC. Une vidéo de gameplay est prévue le 22 septembre.'
  },
  'fire-emblem-fortunes-weave': {
    date: '15.09.2026', category: 'NINTENDO · SWITCH 2', image: 'fire-emblem-fortunes-weave-news.jpg', imageAlt: 'Fire Emblem: Fortune’s Weave — visuel officiel Nintendo', cover: 'FIRE EMBLEM',
    title: 'FORTUNE’S WEAVE', accent: 'JOUE SA DERNIÈRE CARTE.', dek: 'À deux jours de sa sortie, Fire Emblem: Fortune’s Weave revient sur ses quatre destins et la liberté laissée aux joueurs pour les entrelacer.',
    lead: 'Le prochain Fire Emblem s’apprête à entrer en scène sur Nintendo Switch 2. Attendu le 17 septembre 2026, Fortune’s Weave profite de cette dernière ligne droite pour rappeler ce qui distingue son aventure : quatre protagonistes, quatre parcours et une destinée à reconstruire.',
    intro: 'Les héros sont présentés comme morts dans un futur proche avant de recevoir une seconde chance grâce à Eshmel, une oracle qui veut infléchir leur sort. Cette prémisse installe immédiatement l’enjeu du jeu : comprendre ce qui s’est brisé, puis réunir les fragments d’une histoire commune.',
    h2: 'QUATRE DESTINS, UNE SEULE ISSUE', p1: 'Chaque protagoniste dispose de son propre scénario, mais Fortune’s Weave ne cloisonne pas ces récits. Il sera possible de passer librement de l’un à l’autre afin de faire progresser les quatre fils narratifs et de viser la conclusion la plus favorable.',
    quote: 'Le joueur ne choisit plus seulement qui suivre : il choisit quand faire avancer chaque destin.', quoteBy: 'Let’s Play · La nouvelle mécanique narrative',
    h2b: 'ENTRE DEUX BATAILLES, LE TEMPS DES LIENS', p2: 'La formule stratégique reste familière aux habitués. Entre deux combats majeurs, le hub sert de point d’ancrage pour discuter avec les alliés, renforcer les soutiens, recruter de nouveaux personnages et explorer les environs.', p3: 'Ces moments de respiration ne sont pas qu’une parenthèse. Les échanges et les recrutements devraient nourrir la progression des quatre campagnes, tout en donnant au joueur les clés pour comprendre les enjeux de ce monde et les relations entre ses héros.', p4: 'La sortie est fixée au 17 septembre 2026, exclusivement sur Nintendo Switch 2. Une longue vidéo de présentation accompagne cette dernière étape et permet de revoir les bases de l’aventure avant de se lancer dans la bataille.',
    take: 'À RETENIR', takeText: 'Fire Emblem: Fortune’s Weave sortira le 17 septembre 2026 sur Nintendo Switch 2, avec quatre protagonistes et des scénarios que le joueur pourra suivre librement.'
  }
};

function Arrow(){ return <span aria-hidden="true">↗</span>; }

export default function CurrentNews({ slug }) {
  const routeSlug = useParams().slug;
  const story = stories[slug || routeSlug] || stories['persona-6-switch-2'];
  return <>
    <section className="article-hero wrap"><div className="section-label"><span><b>01</b> / ACTUS À LA UNE</span><span>{story.date} · {story.category}</span></div><div className="article-heading"><div><p className="eyebrow"><span className="live-dot" /> RÉÉCRIT POUR LET’S PLAY</p><h1>{story.title}<br/><em>{story.accent}</em></h1><p className="article-dek">{story.dek}</p><div className="article-byline"><span>LET’S PLAY</span><span>4 MIN DE LECTURE</span></div></div><div className="article-cover hud-frame"><img src={`${base}${story.image}`} alt={story.imageAlt} /><div><small>{story.category}</small><strong>{story.cover}</strong></div></div></div></section>
    <main className="article-layout wrap"><article className="article-body"><p className="article-lead">{story.lead}</p><p>{story.intro}</p><h2>{story.h2}</h2><p>{story.p1}</p><div className="article-pullquote"><span>“</span><p>{story.quote}</p><small>{story.quoteBy}</small></div><p>{story.p2}</p><h2>{story.h2b}</h2><p>{story.p3}</p><p>{story.p4}</p><div className="article-endnote"><span className="live-dot" /><strong>{story.take}</strong><span>{story.takeText}</span></div>{story.source ? <p className="article-source">{story.source} <a href={story.sourceUrl} target="_blank" rel="noreferrer">{story.sourceDetail}</a></p> : null}{story.credit ? <p className="article-source">{story.credit}</p> : null}</article><aside className="article-aside"><div className="aside-card"><span className="aside-kicker">EN BREF</span><strong>{story.date}</strong><strong>{story.category}</strong><strong>LET’S PLAY ORIGINAL</strong></div><div className="aside-card aside-card-accent"><span className="aside-kicker">À LIRE AUSSI</span><strong>LES ACTUS À LA UNE</strong><p>Retrouvez les dernières annonces et analyses de la rédaction.</p><Link className="arrow-link" to="/news">RETOUR AUX ACTUS <Arrow/></Link></div></aside></main>
    <Comments />
    <section className="cta wrap"><div><p className="eyebrow"><span className="live-dot" /> LA SUITE SUR LET’S PLAY</p><h2>RESTEZ DANS<br/><em>LE GAME.</em></h2></div><Link className="button button-yellow" to="/news">VOIR LES ACTUS <Arrow/></Link></section>
  </>;
}

export { stories };
