import React from 'react';
import { Link } from 'react-router-dom';
import { baseUrl as base } from '../data';

function Arrow(){ return <span aria-hidden="true">↗</span>; }

export default function Physint(){
  return <>
    <section className="article-hero wrap">
      <div className="section-label"><span><b>NEWS</b> / FEATURED STORY</span><span>10.09.2026 · GAMING INDUSTRY</span></div>
      <div className="article-heading"><div><p className="eyebrow"><span className="live-dot" /> INDUSTRY SHIFT</p><h1>PHYSINT<br/><em>CHANGES SIDES.</em></h1><p className="article-dek">PlayStation steps away from Kojima Productions’ next stealth-action game. Xbox is now stepping in to keep the project moving.</p><div className="article-byline"><span>BY LET’S PLAY EDITORIAL</span><span>6 MIN READ</span></div></div><div className="article-cover hud-frame"><img src={`${base}physint-news.jpg`} alt="PHYSINT promotional artwork" /><div><small>A HIDEO KOJIMA GAME</small><strong>PHYSINT</strong></div></div></div>
    </section>
    <main className="article-layout wrap"><article className="article-body"><p className="article-lead">A project once presented as a PlayStation partnership now has a very different future: Hideo Kojima says Physint is continuing with Xbox.</p><p>The news lands as one of the biggest publishing pivots in Kojima Productions’ history. PlayStation has confirmed that it is stepping away from the collaboration, while Kojima says the decision to keep Physint alive led the studio to Xbox.</p><h2>FROM PLAYSTATION TO XBOX</h2><p>Physint was revealed in 2024 as Kojima’s return to tactical espionage action — the lane that made his name synonymous with stealth, cinematic storytelling and elaborate world-building. The game has been described as an experience designed to blur the line between film and interactive play.</p><div className="article-pullquote"><span>“</span><p>Determined to keep the project alive, we have spent the last three months searching tirelessly for a new partner.</p><small>— Hideo Kojima, September 2026</small></div><p>According to Kojima, PlayStation informed the studio in mid-June that it would cancel the project. Xbox then became the partner whose vision aligned with the team’s ambitions. Xbox executive Asha Sharma called the partnership a chance to support a project that challenges conventions.</p><h2>WHAT WE KNOW — AND WHAT WE DON’T</h2><p>Development is ongoing, but Physint is still far from release and has no announced launch date. The game’s exact technical path is also unclear. One open question is whether it will continue to use Decima, the engine developed by Sony’s Guerrilla Games.</p><p>What is clearer is the larger strategy. Xbox already publishes Kojima Productions’ OD, and the new agreement is expected to stretch beyond games into film and television collaborations. For players, that makes Physint more than a platform switch: it is a new chapter in Kojima’s long-running experiment with the borders between mediums.</p><div className="article-endnote"><span className="live-dot" /><strong>THE LET’S PLAY TAKE</strong><span>Big pivot. Early days. Worth watching.</span></div><p className="article-source">Sources: <a href="https://news.instant-gaming.com/fr/articles/21827-physint-le-prochain-jeu-de-kojima-est-annule-par-playstation-avant-d-etre-sauve-par-xbox" target="_blank" rel="noreferrer">Instant Gaming</a>, PlayStation, Kojima Productions and Xbox statements, cross-checked with GameSpot and PC Gamer.</p></article><aside className="article-aside"><div className="aside-card"><span className="aside-kicker">QUICK READ</span><strong>01 / The switch</strong><strong>02 / The stakes</strong><strong>03 / The unknowns</strong></div><div className="aside-card aside-card-accent"><span className="aside-kicker">NEXT MOVE</span><strong>Keep the signal on.</strong><p>We’ll follow Physint as Kojima Productions reveals more.</p><Link className="arrow-link" to="/news">BACK TO NEWS <Arrow/></Link></div></aside></main>
    <section className="cta wrap"><div><p className="eyebrow"><span className="live-dot" /> MORE STORIES, LESS NOISE</p><h2>KEEP<br/><em>PLAYING.</em></h2></div><Link className="button button-yellow" to="/news">Back to news <Arrow/></Link></section>
  </>;
}
