import React from 'react';
import { Link } from 'react-router-dom';
import { baseUrl as base } from '../data';
import Comments from '../components/Comments';

function Arrow(){ return <span aria-hidden="true">↗</span>; }

export default function Zelda40th(){
  return <>
    <section className="article-hero wrap"><div className="section-label"><span><b>NEWS</b> / NINTENDO</span><span>08.09.2026 · SWITCH 2</span></div><div className="article-heading"><div><p className="eyebrow"><span className="live-dot" /> ANNIVERSAIRE</p><h1>ZELDA<br/><em>40 ANS.</em></h1><p className="article-dek">Nintendo prépare le retour d’Ocarina of Time avec une Switch 2 collector, une manette Pro assortie et deux amiibo chargés de nostalgie.</p><div className="article-byline"><span>PAR LA RÉDACTION LET’S PLAY</span><span>4 MIN DE LECTURE</span></div></div><div className="article-cover hud-frame"><img src={`${base}zelda-40th-switch2.jpg`} alt="The Legend of Zelda Ocarina of Time sur Nintendo Switch 2" /><div><small>THE LEGEND OF ZELDA · 40TH</small><strong>OCARINA</strong></div></div></div></section>
    <main className="article-layout wrap"><article className="article-body"><p className="article-lead">Pour célébrer les 40 ans de The Legend of Zelda, Nintendo ne mise pas uniquement sur le remake d’Ocarina of Time : toute une collection d’objets aux couleurs d’Hyrule arrive autour de la Switch 2.</p><p>Présentée pendant le Direct anniversaire, l’édition spéciale de la console reprend les codes visuels de la saga avec un motif Triforce très présent, des détails dorés sur les Joy-Con et des références discrètes à Link et Zelda.</p><h2>UNE SWITCH 2 POUR HYRULE</h2><p>Les Joy-Con verts sont ponctués d’accents dorés, tandis qu’un petit Link pixelisé apparaît sur le Joy-Con gauche et Zelda sur le droit. Le dock noir et or complète l’ensemble avec une Triforce mise en avant sur sa façade.</p><div className="article-pullquote"><span>“</span><p>Nintendo transforme le retour d’Ocarina of Time en véritable rendez-vous collector : console, manette et accessoires racontent la même histoire.</p><small>— L’ANALYSE LET’S PLAY</small></div><p>La gamme ne s’arrête pas à la console. Une manette Pro Nintendo Switch 2 adopte le même langage graphique, accompagnée d’une housse de transport assortie. Un support d’exposition dédié est également prévu, en exclusivité sur le Nintendo Store.</p><h2>LA NOSTALGIE PASSE EN AMIIBO</h2><p>Deux amiibo inspirés du remake d’Ocarina of Time sont annoncés : Link enfant et Zelda enfant. En jeu, ils permettront d’obtenir deux masques reprenant les visages stylisés de l’ère Nintendo 64, une récompense qui assume pleinement la fibre nostalgique de cette célébration.</p><p>La console, la manette, la housse et le support sont annoncés pour le 29 octobre. Les amiibo arriveront en 2027, tandis que The Legend of Zelda: Ocarina of Time Remake est attendu le 5 novembre 2026.</p><div className="article-endnote"><span className="live-dot" /><strong>LE POINT LET’S PLAY</strong><span>Une célébration pensée pour les collectionneurs, mais aussi une manière claire de faire d’Ocarina of Time le grand événement Zelda de cette fin d’année.</span></div><p className="article-source">Source : <a href="https://www.nintendo.com/" target="_blank" rel="noreferrer">Nintendo</a>, consultés le 12 septembre 2026.</p></article><aside className="article-aside"><div className="aside-card"><span className="aside-kicker">À RETENIR</span><strong>Console et accessoires : 29 octobre</strong><strong>Remake : 5 novembre 2026</strong><strong>Amiibo : 2027</strong></div><div className="aside-card aside-card-accent"><span className="aside-kicker">NEXT MOVE</span><strong>Retourner à Hyrule.</strong><p>Le remake et ses objets collector donnent déjà le ton de l’anniversaire.</p><Link className="arrow-link" to="/news">RETOUR AUX NEWS <Arrow/></Link></div></aside></main>
    <Comments />
    <section className="cta wrap"><div><p className="eyebrow"><span className="live-dot" /> MORE STORIES, LESS NOISE</p><h2>KEEP<br/><em>PLAYING.</em></h2></div><Link className="button button-yellow" to="/news">BACK TO NEWS <Arrow/></Link></section>
  </>;
}
