// Habillage visuel de chaque ville de Vice City Rush : ciel, météo, enseignes,
// boutiques, sponsors des tribunes et porte de mi-parcours. Les règles de jeu
// restent dans cityRushRules.js ; ici il n'y a que de la direction artistique.
export const CITY_RUSH_THEMES = Object.freeze({
  'vice-city': Object.freeze({
    sky: Object.freeze({
      top: 0x120f3a, mid: 0x5a2a7a, horizon: 0xff7a6b, haze: 0xffb08a,
      sun: Object.freeze({ color: 0xffe08a, glow: 0xff5fa2, elevation: 0.11, radius: 0.19, stripes: 1 }),
      stars: 0.35, moon: 0,
    }),
    weather: 'clear',
    fogNear: 70, fogFar: 250,
    facade: Object.freeze({ style: 'deco', floor: 1.55, litRatio: 0.52, litColors: ['#ffd27a', '#ff8ac9', '#7cf0ea'] }),
    shops: Object.freeze([
      { text: 'CAFÉ CUBANO', color: '#43ead5', awning: '#ff5db8' },
      { text: 'NEON BAY SURF', color: '#ff5db8', awning: '#43ead5' },
      { text: 'VICE RECORDS', color: '#ffd36b', awning: '#8d6bff' },
      { text: 'HOTEL PALMA', color: '#c89bff', awning: '#ffd36b' },
    ]),
    verticalSigns: Object.freeze(['HOTEL', 'OCEAN', 'CLUB', 'VICE']),
    sponsors: Object.freeze(['LET’S PLAY', 'RADIO VICE 98.6', 'NEON BAY HOTEL', 'PALMA TYRES', 'SUNSET CLUB']),
    gate: Object.freeze({ style: 'deco-arch', text: 'WELCOME TO VICE CITY' }),
    gantryText: 'OCEAN DRIVE',
    crowdColors: Object.freeze([0xff5db8, 0x43ead5, 0xffd36b, 0xf6f1e4, 0xc89bff, 0xff8d5a]),
    roadTint: 0x1a1830, laneColor: '#d7e9ef', edgeColor: '#ff5db8', sidewalkTint: 0x4d3752,
    lamp: 'deco', tree: 'palm',
  }),
  'new-york': Object.freeze({
    sky: Object.freeze({
      top: 0x060a1e, mid: 0x152447, horizon: 0x5b4a6e, haze: 0xffb871,
      sun: Object.freeze({ color: 0xfff1c9, glow: 0xffc06b, elevation: 0.2, radius: 0.045, stripes: 0 }),
      stars: 0.75, moon: 1,
    }),
    weather: 'clear',
    fogNear: 60, fogFar: 240,
    facade: Object.freeze({ style: 'brick', floor: 1.45, litRatio: 0.46, litColors: ['#ffd98a', '#ffe9b8', '#9fd3ff'] }),
    shops: Object.freeze([
      { text: 'PIZZA 24H', color: '#ff6b5c', awning: '#d93a3a' },
      { text: 'DELI · GROCERY', color: '#ffc45c', awning: '#2d7a4a' },
      { text: 'LIQUOR', color: '#ff5fa2', awning: '#1f1f2f' },
      { text: 'NIGHT SHIFT BAR', color: '#4fd6e8', awning: '#2a2f4a' },
    ]),
    verticalSigns: Object.freeze(['HOTEL', 'DINER', 'PARKING', 'JAZZ']),
    sponsors: Object.freeze(['LET’S PLAY', 'BROADWAY NIGHTS', 'MIDTOWN CAB CO.', 'EMPIRE OIL', '42ND ST RADIO']),
    gate: Object.freeze({ style: 'overpass', text: 'MIDTOWN · 42ND ST' }),
    gantryText: 'MIDTOWN',
    crowdColors: Object.freeze([0xffc45c, 0x4fd6e8, 0xf0ece6, 0x2f4f8f, 0xc94040, 0x8c8c99]),
    roadTint: 0x16181f, laneColor: '#ffe28a', edgeColor: '#ffc45c', sidewalkTint: 0x3a3d47,
    lamp: 'cobra', tree: 'street',
  }),
  tokyo: Object.freeze({
    sky: Object.freeze({
      top: 0x0a0a24, mid: 0x2a1650, horizon: 0x7a2d7c, haze: 0xff6fc0,
      sun: Object.freeze({ color: 0xfff6e0, glow: 0xf54eae, elevation: 0.24, radius: 0.05, stripes: 0 }),
      stars: 0.55, moon: 1,
    }),
    weather: 'drizzle',
    fogNear: 55, fogFar: 230,
    facade: Object.freeze({ style: 'dense', floor: 1.35, litRatio: 0.6, litColors: ['#9af4ff', '#ffffff', '#ff7dd1', '#ffe08a'] }),
    shops: Object.freeze([
      { text: 'ラーメン', color: '#ff5b9a', awning: '#d9302f' },
      { text: 'パチンコ', color: '#42e6ff', awning: '#1b2750' },
      { text: 'カラオケ', color: '#ffe066', awning: '#5a2d8a' },
      { text: '居酒屋', color: '#ff9f43', awning: '#302030' },
    ]),
    verticalSigns: Object.freeze(['ネオン', '渋谷', 'TOKYO', '夜', 'カフェ', 'ゲーム']),
    sponsors: Object.freeze(['LET’S PLAY', 'SHIBUYA FM', 'NEO TYRES', 'ミラージュ', 'TOKYO NIGHT RUN']),
    gate: Object.freeze({ style: 'torii', text: '渋谷' }),
    gantryText: 'SHIBUYA',
    crowdColors: Object.freeze([0xff5b9a, 0x42e6ff, 0xffffff, 0xffe066, 0x8a6bff, 0x202a44]),
    roadTint: 0x15172a, laneColor: '#e2f4ff', edgeColor: '#42e6ff', sidewalkTint: 0x2e2a40,
    lamp: 'modern', tree: 'cherry',
  }),
  paris: Object.freeze({
    sky: Object.freeze({
      top: 0x1d1a3f, mid: 0x5b3f72, horizon: 0xf2a36b, haze: 0xffd0a8,
      sun: Object.freeze({ color: 0xfff0c8, glow: 0xffa86b, elevation: 0.07, radius: 0.12, stripes: 0 }),
      stars: 0.25, moon: 0,
    }),
    weather: 'clear',
    fogNear: 65, fogFar: 245,
    facade: Object.freeze({ style: 'haussmann', floor: 1.6, litRatio: 0.44, litColors: ['#ffdca3', '#fff0cf', '#ffc98a'] }),
    shops: Object.freeze([
      { text: 'CAFÉ DE LA NUIT', color: '#ffd9a8', awning: '#b8322f' },
      { text: 'BOULANGERIE', color: '#ffe6b8', awning: '#2f5d44' },
      { text: 'TABAC · PRESSE', color: '#ff8c8c', awning: '#c9402f' },
      { text: 'BRASSERIE 86', color: '#72d9d0', awning: '#2a3a66' },
    ]),
    verticalSigns: Object.freeze(['HÔTEL', 'MÉTRO', 'CINÉMA', 'BAL']),
    sponsors: Object.freeze(['LET’S PLAY', 'RADIO RIVE GAUCHE', 'PNEUS LUMIÈRE', 'CAFÉ 1986', 'SEINE MOTORS']),
    gate: Object.freeze({ style: 'arc', text: 'RIVE GAUCHE' }),
    gantryText: 'RIVE GAUCHE',
    crowdColors: Object.freeze([0xffb7a4, 0x72d9d0, 0xf5f0e6, 0x2f3f7a, 0xd94a4a, 0xf2d36c]),
    roadTint: 0x26232c, laneColor: '#f0e7d8', edgeColor: '#ffb7a4', sidewalkTint: 0x6b5b58,
    lamp: 'globe', tree: 'plane',
  }),
  london: Object.freeze({
    sky: Object.freeze({
      top: 0x0b1226, mid: 0x1f3047, horizon: 0x4f5f6c, haze: 0xd8b27a,
      sun: Object.freeze({ color: 0xfff4de, glow: 0xffc879, elevation: 0.17, radius: 0.05, stripes: 0 }),
      stars: 0.3, moon: 1,
    }),
    weather: 'rain',
    fogNear: 40, fogFar: 200,
    facade: Object.freeze({ style: 'georgian', floor: 1.5, litRatio: 0.42, litColors: ['#ffd98d', '#ffe9c0', '#ffc46b'] }),
    shops: Object.freeze([
      { text: 'THE NEON CROWN', color: '#e8bd64', awning: '#1d3b2a' },
      { text: 'FISH & CHIPS', color: '#ffd98d', awning: '#2a3a66' },
      { text: 'SOHO RECORDS', color: '#70cbd1', awning: '#3a1f3f' },
      { text: 'TUBE · SOHO', color: '#ff6b6b', awning: '#1a1f2f' },
    ]),
    verticalSigns: Object.freeze(['PUB', 'THEATRE', 'HOTEL', 'SOHO']),
    sponsors: Object.freeze(['LET’S PLAY', 'SOHO FM', 'THAMES TYRES', 'PICCADILLY MOTORS', 'NIGHTLINE']),
    gate: Object.freeze({ style: 'tower-bridge', text: 'SOHO' }),
    gantryText: 'SOHO',
    crowdColors: Object.freeze([0xe8bd64, 0x70cbd1, 0xf3eee4, 0xb83a3a, 0x2f3f5f, 0x6b6f7a]),
    roadTint: 0x171a22, laneColor: '#e9efe9', edgeColor: '#e8bd64', sidewalkTint: 0x3f434b,
    lamp: 'victorian', tree: 'street',
  }),
});

export function cityRushTheme(cityId) {
  return CITY_RUSH_THEMES[cityId] || CITY_RUSH_THEMES['vice-city'];
}
