// Contenu de la démo de combat — « Le Sablier de Bab El » (concept B).
//
// Ce fichier est la seule partie du prototype qui connaît l'univers : noms,
// chiffres, textes. Le moteur (rpgCombat.js) ne lit que des structures. Pour
// essayer un autre concept du dossier, il suffit d'écrire un autre fichier
// comme celui-ci.
//
// Échelle de lecture : une compétence de base tape autour de 100-115 % de
// l'Attaque, une compétence à 3 PA autour de 260-330 %, et tout ce qui coûte
// du sable tape plus fort que son coût en PA ne le laisserait croire.

export const RPG_ELEMENT_ICONS = {
  braise: '🔥',
  souffle: '🌀',
  sable: '⏳',
  eau: '💧',
  encre: '🖋',
  verre: '◇',
};

// ── L'équipe ───────────────────────────────────────────────────────────────
export const RPG_DEMO_PARTY = [
  {
    id: 'salem',
    name: 'SALEM',
    role: 'Le Sondeur · Sable',
    element: 'sable',
    level: 12,
    maxHp: 205,
    atk: 28,
    def: 19,
    mag: 16,
    res: 17,
    spd: 12,
    agi: 66,
    nameSegments: 3,
    portrait: 'salem',
    line: 'Je descends vérifier. Je remonte toujours avec quelqu’un. Jamais assez.',
    skills: [
      {
        id: 'sonde',
        name: 'Sonde',
        element: 'sable',
        kind: 'physique',
        pa: 1,
        power: 112,
        felure: 8,
        target: 'ennemi',
        text: 'Un coup de perche franc. Fiable, et ça monte la Fêlure.',
      },
      {
        id: 'crochet',
        name: 'Crochet de palier',
        element: 'sable',
        kind: 'physique',
        pa: 1,
        power: 72,
        push: 1,
        target: 'ennemi',
        text: 'Il accroche et tire vers le bas : l’ennemi descend d’un étage. Du 3e au 1er, c’est une Chute (×1,4).',
      },
      {
        id: 'effondrement',
        name: 'Effondrement',
        element: 'sable',
        kind: 'physique',
        pa: 3,
        power: 230,
        target: 'tous-ennemis',
        crystallizePower: 460,
        text: 'Le palier cède sous tout le monde. Touche tous les ennemis.',
      },
      {
        id: 'le-dernier-etage',
        name: 'Le Dernier Étage',
        element: 'sable',
        kind: 'physique',
        pa: 3,
        power: 320,
        felure: 20,
        target: 'ennemi',
        requiresName: 3,
        text: 'Il frappe comme on ferme une porte sur un étage condamné.',
      },
    ],
  },
  {
    id: 'yamina',
    name: 'YAMINA',
    role: 'L’Horlogère · Verre',
    element: 'verre',
    level: 12,
    maxHp: 168,
    atk: 13,
    def: 12,
    mag: 30,
    res: 22,
    spd: 14,
    agi: 80,
    nameSegments: 3,
    backline: true,
    portrait: 'yamina',
    line: 'J’ai signé une Liste à dix-neuf ans. Depuis, je compte avant de signer.',
    skills: [
      {
        id: 'aiguille',
        name: 'Aiguille',
        element: 'verre',
        kind: 'magie',
        pa: 2,
        power: 190,
        interrupt: true,
        target: 'ennemi',
        text: 'Rapide et précise : interrompt une incantation ennemie si l’élément correspond.',
      },
      {
        id: 'retard',
        name: 'Retard',
        element: 'verre',
        kind: 'magie',
        pa: 1,
        power: 0,
        delay: true,
        target: 'ennemi',
        text: 'Le coup annoncé par cet ennemi attendra un round de plus. Le temps de préparer autre chose.',
      },
      {
        id: 'avance',
        name: 'Avance',
        element: 'verre',
        kind: 'magie',
        pa: 1,
        power: 0,
        gainPa: 1,
        target: 'soi',
        text: 'Elle remonte le mécanisme : +1 PA pour toute l’équipe ce tour-ci.',
      },
      {
        id: 'heure-pleine',
        name: 'Heure pleine',
        element: 'verre',
        kind: 'magie',
        pa: 3,
        power: 300,
        gainPa: 1,
        target: 'ennemi',
        requiresName: 3,
        text: 'Elle donne l’heure exacte. Ça fait très mal, et l’équipe retrouve un PA.',
      },
    ],
  },
  {
    id: 'boualem',
    name: 'BOUALEM',
    role: 'Le Puisatier · Eau',
    element: 'eau',
    level: 12,
    maxHp: 215,
    atk: 18,
    def: 20,
    mag: 27,
    res: 24,
    spd: 8,
    agi: 45,
    nameSegments: 3,
    portrait: 'boualem',
    line: 'L’eau monte, le sable aussi. Moi je fais monter ce qui aide.',
    skills: [
      {
        id: 'puisage',
        name: 'Puisage',
        element: 'eau',
        kind: 'soin',
        pa: 1,
        power: 95,
        target: 'allie',
        text: 'Soigne un compagnon. Le seul soin direct de l’équipe.',
      },
      {
        id: 'nappe',
        name: 'Nappe',
        element: 'eau',
        kind: 'magie',
        pa: 1,
        power: 0,
        ground: 40,
        target: 'soi',
        text: 'Il fait remonter la nappe : +40 sable sur notre sol, à dépenser en barrages ou en sorts.',
      },
      {
        id: 'vague',
        name: 'Vague',
        element: 'eau',
        kind: 'magie',
        pa: 2,
        power: 175,
        interrupt: true,
        target: 'ennemi',
        crystallizePower: 350,
        text: 'Un mur d’eau tiède qui sort du sol. Éteint une Chaudière en cours d’incantation.',
      },
      {
        id: 'deluge',
        name: 'Déluge',
        element: 'eau',
        kind: 'magie',
        pa: 3,
        power: 265,
        sandCost: 40,
        target: 'tous-ennemis',
        requiresName: 3,
        text: 'Coûte 40 sable de notre sol. Il ouvre les vannes : tout le monde est touché.',
      },
    ],
  },
  {
    id: 'feriel',
    name: 'FÉRIEL',
    role: 'La Souffleuse de verre · Braise',
    element: 'braise',
    level: 12,
    maxHp: 175,
    atk: 26,
    def: 14,
    mag: 24,
    res: 16,
    spd: 13,
    agi: 90,
    nameSegments: 3,
    portrait: 'feriel',
    line: 'Le sable, c’est du verre qui n’a pas encore compris.',
    skills: [
      {
        id: 'eclat-de-verre',
        name: 'Éclat de verre',
        element: 'verre',
        kind: 'physique',
        pa: 1,
        power: 100,
        interrupt: true,
        target: 'ennemi',
        text: 'Un shard lancé à la main. Interrompt une incantation d’Encre.',
      },
      {
        id: 'bulle',
        name: 'Bulle',
        element: 'verre',
        kind: 'magie',
        pa: 1,
        power: 0,
        shield: true,
        target: 'allie',
        text: 'Un barrage de verre sur un compagnon : il absorbe avant les PV.',
      },
      {
        id: 'four',
        name: 'Four',
        element: 'braise',
        kind: 'magie',
        pa: 2,
        power: 205,
        target: 'ennemi',
        crystallizePower: 410,
        text: 'Elle ouvre son four de souffleur. Ça ne pardonne pas.',
      },
      {
        id: 'verre-fondu',
        name: 'Verre fondu',
        element: 'braise',
        kind: 'magie',
        pa: 3,
        power: 330,
        target: 'ennemi',
        requiresName: 3,
        text: 'Une coulée à mille degrés. Le plus gros dégât monocible de l’équipe.',
      },
    ],
  },
];

// Tarek : la réserve. La permutation coûte le tour de celui qui entre.
export const RPG_DEMO_RESERVE = [
  {
    id: 'tarek',
    name: 'TAREK',
    role: 'Le Porteur · Sable',
    element: 'sable',
    level: 12,
    maxHp: 250,
    atk: 31,
    def: 27,
    mag: 12,
    res: 19,
    spd: 7,
    agi: 40,
    nameSegments: 2, // il lui manque un segment de Nom : son Ultime est verrouillée
    portrait: 'tarek',
    line: 'Je porte les cartons. Personne ne m’a jamais demandé ce qu’il y a dedans.',
    skills: [
      {
        id: 'palette',
        name: 'Palette',
        element: 'sable',
        kind: 'physique',
        pa: 1,
        power: 125,
        felure: 12,
        target: 'ennemi',
        text: 'Il frappe avec ce qu’il porte. Monte la Fêlure plus vite que tout le reste.',
      },
      {
        id: 'rempart',
        name: 'Rempart',
        element: 'sable',
        kind: 'physique',
        pa: 1,
        power: 0,
        shield: true,
        target: 'soi',
        text: 'Un barrage sur lui-même : c’est le meilleur endroit pour le poser.',
      },
      {
        id: 'charge',
        name: 'Charge',
        element: 'sable',
        kind: 'physique',
        pa: 2,
        power: 190,
        push: 1,
        target: 'ennemi',
        text: 'Il pousse. L’ennemi descend d’un étage.',
      },
    ],
  },
];

// ── Les ennemis de la démo ─────────────────────────────────────────────────
const BALAYEUR = {
  id: 'balayeur',
  name: 'BALAYEUR',
  role: 'Il nettoie ce que le cycle laisse',
  element: 'sable',
  level: 11,
  maxHp: 285,
  atk: 27,
  def: 15,
  mag: 14,
  res: 14,
  spd: 9,
  agi: 42,
  rewards: { xp: 52, sable: 34 },
  moves: [
    { id: 'raclette', label: 'Raclette', family: 'lourd', power: 128, kind: 'physique', weight: 3 },
    { id: 'tourbillon', label: 'Tourbillon', family: 'zone', power: 104, kind: 'physique', weight: 2.2 },
    { id: 'sac', label: 'Sac de sable', family: 'sablier', power: 0, weight: 1.6 },
  ],
};

const GREFFIER = {
  id: 'greffier',
  name: 'GREFFIER',
  role: 'Il tamponne les noms, page après page',
  element: 'encre',
  level: 12,
  maxHp: 300,
  atk: 17,
  def: 13,
  mag: 30,
  res: 23,
  spd: 10,
  agi: 55,
  backline: true,
  rewards: { xp: 66, sable: 48 },
  moves: [
    { id: 'tampon', label: 'Tampon', family: 'lourd', power: 150, kind: 'magie', element: 'encre', weight: 2.4 },
    {
      id: 'radiation',
      label: 'Radiation',
      family: 'incantation',
      power: 280,
      kind: 'magie',
      element: 'encre',
      weight: 2,
      counterElement: 'verre',
    },
  ],
};

const SONNIER = {
  id: 'sonnier',
  name: 'SONNIER',
  role: 'Il sonne pour les autres',
  element: 'souffle',
  level: 12,
  maxHp: 265,
  atk: 20,
  def: 14,
  mag: 26,
  res: 18,
  spd: 11,
  agi: 60,
  rewards: { xp: 60, sable: 40 },
  moves: [
    { id: 'tocsin', label: 'Tocsin', family: 'zone', power: 118, kind: 'magie', element: 'souffle', weight: 2.6 },
    { id: 'carillon', label: 'Carillon', family: 'soutien', power: 0, weight: 1.8 },
  ],
};

// Le boss : deux phases, et l'Astrolabe sonne plus souvent à partir de la 2e.
const PROTOTYPE = {
  id: 'prototype',
  name: 'LE PROTOTYPE',
  role: 'Construit pour descendre à la place des hommes',
  element: 'sable',
  level: 14,
  maxHp: 2400,
  atk: 36,
  def: 22,
  mag: 24,
  res: 21,
  spd: 12,
  agi: 50,
  rewards: { xp: 460, sable: 420, registres: 1 },
  phases: [
    {
      threshold: 0.5,
      label: 'Le Prototype ouvre sa chaudière : l’Astrolabe sonnera plus souvent',
      clockInterval: 4,
    },
  ],
  moves: [
    { id: 'piston', label: 'Piston', family: 'lourd', power: 168, kind: 'physique', weight: 3, phase: 1 },
    { id: 'jet', label: 'Jet de vapeur', family: 'zone', power: 128, kind: 'physique', element: 'souffle', weight: 2.4, phase: 1 },
    {
      id: 'chaudiere',
      label: 'Chaudière',
      family: 'incantation',
      power: 300,
      kind: 'magie',
      element: 'braise',
      weight: 1.8,
      counterElement: 'eau',
      phase: 1,
    },
    { id: 'marteau', label: 'Marteau de laiton', family: 'lourd', power: 215, kind: 'physique', push: 1, weight: 3, phase: 2 },
    { id: 'purge', label: 'Purge', family: 'zone', power: 172, kind: 'magie', element: 'braise', weight: 2.6, phase: 2 },
    { id: 'surcharge', label: 'Surcharge', family: 'soutien', power: 0, weight: 1.4, phase: 2 },
  ],
};

/** Les trois vagues de la démo : montée en tension, puis le boss. */
export const RPG_DEMO_WAVES = [
  {
    id: 'vague-1',
    title: 'Vague 1 — les quais',
    intro: 'Deux balayeurs travaillent. L’un d’eux ramassera le sable du sol : soufflez-le avant.',
    clockInterval: 5,
    foes: [{ ...BALAYEUR, id: 'balayeur-a' }, { ...BALAYEUR, id: 'balayeur-b' }],
  },
  {
    id: 'vague-2',
    title: 'Vague 2 — le greffe',
    intro: 'Le Greffier incante une Radiation. Seule une attaque de Verre qui interrompt (Aiguille, Éclat de verre) peut la faire tomber.',
    clockInterval: 5,
    foes: [{ ...GREFFIER, id: 'greffier-a' }, { ...SONNIER, id: 'sonnier-a' }],
  },
  {
    id: 'vague-3',
    title: 'Boss — le Prototype',
    intro: 'Sous la moitié de sa vie, il ouvre sa chaudière : l’Astrolabe sonne tous les 4 rounds au lieu de 5. Sa Chaudière s’interrompt à l’Eau (la Vague de Boualem).',
    clockInterval: 5,
    foes: [PROTOTYPE],
  },
];

/** Textes d'aide affichés autour du combat. */
export const RPG_DEMO_HELP = [
  {
    title: 'Tout est annoncé',
    text: 'Chaque ennemi montre son prochain coup un round à l’avance : ⬇ lourd, ⬒ zone, ⧗ incantation, ⛃ sablier, ⚑ soutien. Aucune attaque ne surprend.',
  },
  {
    title: 'Quatre réponses, zéro réflexe',
    text: 'Garde (−60 %, +1 Verre si vous étiez la cible), Barrage de verre (absorbe), Contre-élément (l’attaque ennemie −50 % et +15 Fêlure), Reposition (monter d’un étage).',
  },
  {
    title: 'Le sable est une deuxième barre de vie',
    text: 'La moitié des PV perdus tombe au sol. Récoltez-le pour vous soigner, soufflez celui de l’ennemi, ou dépensez-le dans les sorts les plus lourds.',
  },
  {
    title: 'Les étages fondent',
    text: 'Frapper de haut fait +15 % par étage, être en haut protège. Tout le monde descend d’un étage chaque round — et une chute du 3e au 1er fait ×1,4.',
  },
  {
    title: 'L’Astrolabe sonne',
    text: 'Tous les 5 rounds (4 sur les boss), les ennemis gagnent +20 % d’Attaque et tout le monde descend d’un étage. Les combats longs se retournent.',
  },
  {
    title: 'Fêlure et Consonance',
    text: 'À 100 de Fêlure, l’ennemi est Fêlé : il n’agit pas, subit ×2, et le premier coup qui le touche est gratuit. Trois éléments dans un round : ×1,5 et +1 Verre.',
  },
];
