// ⚙️ FICHIER GÉNÉRÉ par scripts/news-bot/fetch-news.mjs — ne pas éditer à la main.
// Dernière génération : 2026-09-22T10:40:00.000Z — 3 article(s).
// Ce module alimente la page Actus et les routes /news/<slug> du site.
export const autoStories = {
  "xbox-consolidation-studios-licenciements-rapport": {
    "slug": "xbox-consolidation-studios-licenciements-rapport",
    "date": "22.09.2026",
    "category": "XBOX · INDUSTRIE",
    "image": "news-auto/xbox-consolidation-studios-licenciements-rapport.svg",
    "imageAlt": "Xbox — visuel éditorial Let’s Play sur le rapport de réorganisation",
    "cover": "XBOX",
    "title": "XBOX PRÉPARERAIT",
    "accent": "UNE NOUVELLE VAGUE DE CONSOLIDATION.",
    "dek": "Selon VGC, Microsoft préparerait une réduction majeure des effectifs et une consolidation de plusieurs studios Xbox. L’information n’est pas confirmée par Microsoft.",
    "lead": "Le conditionnel est ici essentiel. VGC rapporte le 22 septembre 2026, en citant The Information, qu’une nouvelle vague de licenciements pourrait toucher Xbox Game Studios, Bethesda, Activision et Blizzard.",
    "intro": "Le rapport évoque des centaines de postes et de possibles fusions ou transferts entre entités. À ce stade, Microsoft n’a pas confirmé publiquement la forme exacte de la réorganisation : il s’agit donc d’une information de presse, pas d’une annonce officielle de Xbox.",
    "h2": "LE CONDITIONNEL AVANT LE BUZZ",
    "p1": "Le dossier arrive après une première vague annoncée en juillet. VGC rappelle alors un plan évoquant 1 600 suppressions de postes, avec 1 600 autres prévues d’ici la fin de l’exercice de Microsoft. Les chiffres et le périmètre rapportés aujourd’hui doivent encore être distingués de toute décision officiellement publiée.",
    "quote": "Quand une restructuration n’est pas encore confirmée, le premier devoir d’une actu est de garder le conditionnel.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "PLUSIEURS BRANCHES DANS LA MÊME ZONE",
    "p2": "Xbox Game Studios, Bethesda, Activision et Blizzard sont cités dans le rapport, ce qui dessinerait une opération plus large qu’un simple ajustement d’équipe. Une consolidation peut prendre plusieurs formes : fusion de structures, déplacement de fonctions ou fermeture de projets.",
    "p3": "La prudence est d’autant plus importante que les annonces de licenciements ont un impact humain direct. Tant que Microsoft n’a pas communiqué, impossible de confirmer le nombre de personnes concernées, les studios précis ou le calendrier d’application.",
    "p4": "Let’s Play suivra la confirmation officielle avant de transformer ce rapport en fait établi. Pour l’instant, l’information est suffisamment importante pour être signalée, mais pas pour être présentée comme une décision actée.",
    "take": "À RETENIR",
    "takeText": "VGC rapporte une nouvelle vague de licenciements et de consolidations chez Xbox, mais Microsoft n’a pas confirmé ces informations.",
    "source": "D’après VGC, publié le 22.09.2026, citant The Information. Information non confirmée par Microsoft au moment de la publication.",
    "sourceUrl": "https://www.videogameschronicle.com/news/xbox-will-reportedly-consolidate-several-studios-in-new-major-wave-of-layoffs/",
    "sourceDetail": "Lire le rapport VGC",
    "sourceName": "VGC",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "auto": true,
    "thumbnail": "news-auto/xbox-consolidation-studios-licenciements-rapport-official.webp",
    "officialThumbnailUrl": "https://files.manuscdn.com/search-media/310519663645820794/DkH0qyi7rbv66dQnKZOL3K/q6ZUZ8sDnFfvj9HKrgMPhf.jpg"
  },
  "tencent-ecs-jeux-asiatiques-esport-2026": {
    "slug": "tencent-ecs-jeux-asiatiques-esport-2026",
    "date": "22.09.2026",
    "category": "E-SPORT · TENCENT",
    "image": "news-auto/tencent-ecs-jeux-asiatiques-esport-2026.svg",
    "imageAlt": "Tencent Esports Competition Solution — visuel éditorial Let’s Play",
    "cover": "TENCENT ECS",
    "title": "TENCENT INSTALLE",
    "accent": "SON ECS AUX JEUX ASIATIQUES.",
    "dek": "Tencent annonce le déploiement de sa solution ECS pour encadrer les 11 épreuves d’esport des Jeux asiatiques 2026.",
    "lead": "L’esport entre dans une nouvelle phase de standardisation. Dans un communiqué daté du 22 septembre 2026, Tencent annonce que sa Tencent Esports Competition Solution accompagnera les 11 épreuves prévues aux Jeux asiatiques, au Japon, du 22 septembre au 2 octobre.",
    "intro": "La solution veut couvrir toute la chaîne de compétition : contrôle des périphériques et de l’environnement avant le match, surveillance en temps réel de plus de 30 indicateurs, puis réexamen et archivage des données après chaque rencontre. Tencent présente l’ECS comme une couche technique commune à plusieurs jeux et éditeurs.",
    "h2": "UN ARBITRE TECHNIQUE",
    "p1": "L’intérêt de l’annonce n’est pas un nouveau jeu, mais la promesse d’un cadre plus homogène. En traitant le matériel, l’environnement et les données de match dans un même dispositif, Tencent cherche à réduire les zones grises qui compliquent les compétitions multi-titres.",
    "quote": "À ce niveau, la technologie ne remplace pas l’arbitre : elle donne enfin une trace exploitable à chaque décision.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "217 MATCHS COMME PREUVE DE TERRAIN",
    "p2": "Tencent affirme que son système avait déjà assuré le support technique de 217 matchs lors des Jeux asiatiques de Hangzhou, sans incident technique selon son bilan officiel. Cette expérience sert de précédent à un déploiement plus large dans l’édition 2026.",
    "p3": "Le dispositif devra maintenant composer avec onze épreuves et plusieurs catégories de jeux. La réussite se mesurera moins à la promesse marketing qu’à la capacité du système à rester lisible pour les joueurs, les arbitres et le public.",
    "p4": "Cette annonce donne surtout un aperçu de l’infrastructure qui se construit derrière les grandes compétitions. L’esport devient un événement sportif ; ses outils de contrôle cherchent désormais à afficher le même niveau de rigueur.",
    "take": "À RETENIR",
    "takeText": "Tencent déploie son ECS pour les 11 épreuves d’esport des Jeux asiatiques 2026, avec contrôle pré-match, surveillance en direct et archivage.",
    "source": "D’après le communiqué officiel Tencent publié le 22.09.2026.",
    "sourceUrl": "https://www.tencent.com/zh-cn/tencent-esports-competition-solution-to-support-esports-at-the-20th-asian-games/",
    "sourceDetail": "Lire le communiqué officiel",
    "sourceName": "TENCENT",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "auto": true,
    "thumbnail": "news-auto/tencent-ecs-jeux-asiatiques-esport-2026-official.png",
    "officialThumbnailUrl": "https://www.tencent.com/wp-content/uploads/2026/09/OCA.png"
  },
  "dune-awakening-sortie-consoles-mise-a-jour-15": {
    "slug": "dune-awakening-sortie-consoles-mise-a-jour-15",
    "date": "22.09.2026",
    "category": "SORTIES · FUNCOM",
    "image": "news-auto/dune-awakening-sortie-consoles-mise-a-jour-15.svg",
    "imageAlt": "Dune: Awakening — visuel éditorial Let’s Play sur la sortie consoles et la mise à jour 1.5",
    "cover": "DUNE: AWAKENING",
    "title": "DUNE: AWAKENING",
    "accent": "PASSE À L’ATTAQUE SUR CONSOLES.",
    "dek": "Dune: Awakening arrive sur consoles avec sa mise à jour 1.5, un mode solo complet et la conclusion du Livre 1.",
    "lead": "Arrakis ouvre enfin ses portes sur consoles. Le 22 septembre 2026, Dune: Awakening lance sa version complète sur PlayStation 5, Xbox Series X|S et Microsoft Store, avec une mise à jour 1.5 qui change aussi la manière de jouer en solo.",
    "intro": "Funcom accompagne cette sortie d’un mode solo complet, de trois niveaux de difficulté et d’options de personnalisation plus fines. La mise à jour ajoute également Great Convention Part III et le chapitre final du Livre 1, tandis que le Game Pass, le Play Anywhere et le cloud gaming sont annoncés côté Xbox.",
    "h2": "ARRAKIS S’OUVRE À TOUS",
    "p1": "La sortie console complète intervient après un accès anticipé réservé aux précommandes Deluxe et Ultimate depuis le 17 septembre. Les éditions physiques rejoignent donc le lancement du 22 septembre, avec un parcours désormais pensé pour celles et ceux qui veulent découvrir l’univers de Dune sans passer par le PC.",
    "quote": "Le vrai signal du jour, ce n’est pas seulement la console : c’est le solo qui devient une porte d’entrée à part entière.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE LIVRE 1 FERME SON PREMIER CHAPITRE",
    "p2": "Avec Great Convention Part III et son chapitre final, la mise à jour 1.5 donne aussi une conclusion au premier arc narratif. Funcom ne présente donc pas cette version comme un simple portage : le lancement sert de nouveau point d’entrée et de rendez-vous pour les joueurs déjà présents.",
    "p3": "Le mode solo propose trois difficultés prédéfinies, mais aussi des réglages plus précis pour adapter l’expérience. Cette souplesse compte dans un jeu qui mêle survie, exploration et progression persistante dans un monde partagé.",
    "p4": "Pour Let’s Play, le rendez-vous est clair : la version console doit maintenant prouver que l’échelle d’Arrakis fonctionne aussi loin du clavier-souris. Le trailer officiel pose l’ambiance ; le verdict, lui, viendra des premières heures manette en main.",
    "take": "À RETENIR",
    "takeText": "Dune: Awakening sort sur consoles le 22 septembre 2026 avec la mise à jour 1.5, un mode solo complet et la fin du Livre 1.",
    "source": "D’après l’annonce officielle de Funcom publiée le 22.09.2026.",
    "sourceUrl": "https://duneawakening.com/news/announcement/the-new-dune-awakening-is-here/",
    "sourceDetail": "Lire l’annonce officielle",
    "sourceName": "FUNCOM",
    "video": "pn7OQJ9EbR0",
    "videoTitle": "Dune: Awakening — Console and Single-Player Launch Trailer",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "auto": true,
    "thumbnail": "news-auto/dune-awakening-sortie-consoles-mise-a-jour-15-official.jpg",
    "officialThumbnailUrl": "https://duneawakening.com/wp-content/uploads/Steam-News-Website-Banners_Website_16x9.jpg"
  },
};
