// ⚙️ FICHIER GÉNÉRÉ par scripts/news-bot/fetch-news.mjs — ne pas éditer à la main.
// Dernière génération : 2026-10-03T09:59:52.132Z — 26 article(s).
// Ce module alimente la page Actus et les routes /news/<slug> du site.
export const autoStories = {
  "tournez-manette-the-witcher-3-remastered-sur-switch-2-faut-i": {
    "slug": "tournez-manette-the-witcher-3-remastered-sur-switch-2-faut-i",
    "date": "03.10.2026",
    "category": "NINTENDO · GAMEKULT",
    "image": "news-auto/tournez-manette-the-witcher-3-remastered-sur-switch-2-faut-i-official.jpg",
    "imageAlt": "Tournez manette - The Witcher 3 Remastered sur Switch 2 : faut-il répondre à l'appel de la nouvelle partie ? — visuel éditorial Let’s Play",
    "cover": "SWITCH 2",
    "title": "TOURNEZ MANETTE",
    "accent": "THE WITCHER 3.",
    "dek": "Sept ans après un premier portage hybride quelque peu bancal (c'est le moins que l'on puisse dire), The Witcher 3 revient sur Switch 2 grâce à sa version Remastered, plus fluide, nettement plus jolie et mieux pensée pour le jeu nomade.",
    "lead": "Mais si vous avez déjà de la bouteille, y a-t-il vraiment là de quoi repasser au bar ?",
    "intro": "Vous méritez bien une précision sur la raison pour laquelle nous allons principalement analyser la version Switch 2 de ce remaster de The Witcher 3 : par trois fois l'auteur de ces lignes a-t-il déjà arpenté la bourgade de Blanchefleur et les rues moites de Novigrad dans le but de retrouver une jeune fugueuse (on croyait pourtant l'avoir vue du côté de chez Apple).",
    "h2": "LES FAITS",
    "p1": "La première, c'était à la commercialisation du jeu, sur PS4. Puis sont venues les deux extensions, qui furent à leur tour l'occasion de tout reprendre à zéro. Et finalement, en 2019, le jeu a eu droit à une version portable sur Switch.",
    "quote": "Cette semaine néanmoins, tout a changé avec l'arrivée de The Witcher 3 : Wild Hunt - Remastered sur Nintendo Switch 2.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "Imaginez un peu : la profondeur de ce monde, son ambiance et son système de combat passable au creux de la main, bien enfoncé dans son lit ? On signe. Sauf que cette version Switch, quoique miraculeuse, péchait malgré tout d'une approximation technique (notez l'euphémisme) bien trop dominante pour véritablement offrir une expérience pleinement satisfaisante.",
    "p3": "En réalité, il a fallu se tourner vers le Steam Deck et ses nombreux rejetons officieux pour profiter de l'aventure médiévale polonaise dans les meilleures conditions permises par le jeu portable. Alors on repart pour un quatrième tour. Faire tourner le monde ouvert de CD Projekt RED sur une machine pensée autour d'une puce Tegra X1 avait demandé des sacrifices, évidents à aux yeux profanes ou pas : les textures étaient appauvries, la végétation largement clairsemée et la définition tombait à 960 × 540 dans les zones les plus exigeantes, le tout avec un framerate parfois aux fraises. Sept ans plus tard, le studio est parti de la base PC du remaster pour voir ce que la Switch 2 pouvait en garder, au lieu de rogner jusqu'à ce que le jeu daigne démarrer.",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Les prochaines communications officielles préciseront la suite. De votre côté, quel élément mérite d’être surveillé en premier ? Dites-le dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "En 2019, la sortie de The Witcher 3 sur la première Switch tenait donc certes de l'exploit, mais aussi et surtout de la concession.",
    "source": "D’après Gamekult, article consulté le 03.10.2026.",
    "sourceUrl": "https://www.gamekult.com/actualite/the-witcher-3-remastered-sur-switch-2-faut-il-repondre-a-l-appel-de-la-nouvelle-partie-3050872306.html",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/tournez-manette-the-witcher-3-remastered-sur-switch-2-faut-i-official.jpg",
    "officialThumbnailUrl": "https://cdn.gamekult.com/optim/images/news/30/3050872306/the-witcher-3-remastered-sur-switch-2-faut-il-repondre-a-l-appel-de-la-nouvelle-partie-090bf66b__1920_1080__0-394-1920-1014.jpg",
    "video": "IGk17XQ7IrQ",
    "videoTitle": "The Witcher 3: Wild Hunt – Remastered — trailer d’annonce officiel",
    "auto": true,
    "sourceName": "Gamekult"
  },
  "the-witcher-3-remastered-a-un-probleme-de-cheveux-mercredi-a": {
    "slug": "the-witcher-3-remastered-a-un-probleme-de-cheveux-mercredi-a",
    "date": "03.10.2026",
    "category": "SORTIES · NUMERAMA",
    "image": "news-auto/the-witcher-3-remastered-a-un-probleme-de-cheveux-mercredi-a-official.png",
    "imageAlt": "The Witcher 3 Remastered a un problème de cheveux, Mercredi a déjà sa saison 3, et le speedrun de Metal Gear Solid 2 évolue : c’est le récap pop culture de la semaine — visuel éditorial Let’s Play",
    "cover": "CD PROJEKT",
    "title": "THE WITCHER 3",
    "accent": "REMASTERED A UN.",
    "dek": "Tout le monde n'a pas les moyens de payer pour l'information. C'est pourquoi nous maintenons notre journalisme ouvert à tous.",
    "lead": "Mais si vous le pouvez, voici trois bonnes raisons de soutenir notre travail : Si vous croyez en un web gratuit et à une information de qualité accessible au plus grand nombre, rejoignez Numerama+.",
    "intro": "Ajoutez Numerama à votre écran d'accueil et restez connectés au futur ! Pour ne rien manquer de l’actualité, suivez Numerama sur Google !",
    "h2": "LES FAITS",
    "p1": "Cette semaine, il est question de poils et de vitesse dans le récap pop culture hebdomadaire de Numerama. Du côté de CD Projekt Red, on vous conseille de désactiver l'option Nvidia HairWorks dans la version Remastered de The Witcher 3. La saison 3 de Mercredi, quant à elle, a déjà terminé son tournage pour une sortie",
    "quote": "",
    "quoteBy": "",
    "h2b": "LE CONTEXTE",
    "p2": "",
    "p3": "",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Chaque nouveau communiqué officiel permettra d’en savoir plus. Quel point doit-on suivre en priorité selon vous ? Répondez dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "",
    "source": "D’après Numerama, article consulté le 03.10.2026.",
    "sourceUrl": "https://www.numerama.com/pop-culture/2345851-the-witcher-3-remastered-a-un-probleme-de-cheveux-la-saison-3-de-mercredi-est-deja-tournee-et-le-speedrun-de-metal-gear-solid-2-evolue-ca-va-vite-dans-le-recap-pop-culture-de-la-semaine.html",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/the-witcher-3-remastered-a-un-probleme-de-cheveux-mercredi-a-official.png",
    "officialThumbnailUrl": "https://img.numerama.com/www.numerama.com/wp-content/uploads/2026/09/wicther-3.png?resize=1600,900&key=d76da216",
    "auto": true,
    "sourceName": "Numerama"
  },
  "rayman-legends-retold-ubisoft-devoile-l-edition-de-lancement": {
    "slug": "rayman-legends-retold-ubisoft-devoile-l-edition-de-lancement",
    "date": "03.10.2026",
    "category": "ACTUALITÉ · GAMEKULT",
    "image": "news-auto/rayman-legends-retold-ubisoft-devoile-l-edition-de-lancement-official.png",
    "imageAlt": "Rayman Legends Retold : Ubisoft dévoile l'édition de lancement et tacle GTA 6 au passage — visuel éditorial Let’s Play",
    "cover": "ROCKSTAR",
    "title": "RAYMAN LEGENDS",
    "accent": "RETOLD : UBISOFT.",
    "dek": "Ubisoft a certes décalé Rayman Legends Retold de deux mois au dernier moment, mais c'est pour la bonne cause : celle d'un lancement réussi et de fans comblés.",
    "lead": "En tout cas, c'est la visée du studio français qui vient aussi de mettre en lumière la Launch Edition du jeu, avec une jolie pique envoyée à Rockstar par la même occasion. \"Nous n'avons peut-être pas de Glade of Dreams Collection...",
    "intro": "MAIS notre Launch Edition à 39,99 dollars comprend une carte de la Croisée des Rêves, trois lithographies, un étui exclusif… et les DEUX jeux que sont Rayman Legends Retord et Origins : Enanced Edition\", a posté Ubisoft il y a quelques jours.",
    "h2": "LES FAITS",
    "p1": "Avec, à la toute fin, un émoji clin d'œil pas piqué des hannetons, s'adressant évidemment à un certain R étoilé. We might not have a Glade of Dreams Collection... BUT our $39.99 Launch Edition comes with: 🗺️ A printed Glade of Dreams map 🖼️ Three lithographs ✨ An exclusive slipcase...and a copy of BOTH Rayman Legends Retold and Origins: Enhanced Edition 😉 pic.twitter.com/Mu1piw5rnm",
    "quote": "Il faudra donc débourser 89,99 euros supplémentaires en parallèle pour obtenir le titre en dématérialisé.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "Alors, on recontextualise un peu. La semaine dernière, Rockstar annonçait en grande pompe la \"Vice City Collection\", soit l'édition collector officielle de Grand Theft Auto VI.",
    "p3": "Celle-ci est disponible sur la boutique de Rockstar Games et comprend plusieurs goodies - la figurine \"Macca the Gator\", des lunettes de soleil, un sac à bandoulière, une casquette, un miroir aimanté, un verre à shot, une cuillère à cocktail, etc. - pour la somme de 399,99 euros. Ce n'est pas donné, oui, mais surtout : le jeu n'est pas compris dedans. Bref, même si l'on ne s'en fait pas trop pour les ventes de cette édition collector, on comprend aussi qu'Internet ait râlé devant le prix et le contenu. En mentionnant une \"Glade of Dreams Collection\" (\"Glade of Dreams\" étant la traduction anglaise pour la Croisée des Rêves, l'univers de Rayman), en insistant sur son prix très honnête et, surtout, la présence de jeux dans l'édition, Ubisoft vient taquiner directement Rockstar sur tous les sujets épineux du moment. Au passage, le post a carrément cartonné sur X pour ces mêmes raisons.",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Les prochaines communications officielles préciseront la suite. De votre côté, quel élément mérite d’être surveillé en premier ? Dites-le dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "Rappelons que Rayman Legends Retold arrivera le 3 décembre sur PC, PS5, Xbox Series et Nintendo Switch 2.",
    "source": "D’après Gamekult, article consulté le 03.10.2026.",
    "sourceUrl": "https://www.gamekult.com/actualite/rayman-legends-retold-ubisoft-devoile-l-edition-de-lancement-et-tacle-gta-6-au-passage-3050872235.html",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/rayman-legends-retold-ubisoft-devoile-l-edition-de-lancement-official.png",
    "officialThumbnailUrl": "https://cdn.gamekult.com/optim/images/news/30/3050872235/rayman-legends-retold-ubisoft-devoile-l-edition-de-lancement-et-tacle-gta-6-au-passage-8952ca2a__1920_1080__0-339-1920-959.png",
    "video": "i1hLarMpQSQ",
    "videoTitle": "Rayman Legends Retold — Official Game Overview Trailer",
    "auto": true,
    "sourceName": "Gamekult"
  },
  "metro-2033-et-metro-last-light-se-mettent-a-jour-gratuitemen": {
    "slug": "metro-2033-et-metro-last-light-se-mettent-a-jour-gratuitemen",
    "date": "02.10.2026",
    "category": "PLAYSTATION · ACTUGAMING",
    "image": "news-auto/metro-2033-et-metro-last-light-se-mettent-a-jour-gratuitemen-official.jpg",
    "imageAlt": "Metro 2033 et Metro Last Light se mettent à jour gratuitement sur PS5 et Xbox Series — visuel éditorial Let’s Play",
    "cover": "PS5",
    "title": "METRO 2033 ET METRO",
    "accent": "LAST LIGHT SE.",
    "dek": "Pas peu fier de ce résultat impressionnant, Deep Silver vient aujourd’hui nous annoncer que la licence Metro de 4A Games a dépassé les 50 millions de jeux vendus. Un joli exploit qui est de bon augure pour Metro 2039, nouvel épisode qui sortira le 4 février prochain.",
    "lead": "Avant de le découvrir, on nous offre une excuse pour replonger dans les premiers jeux de la licence avec une mise à jour pour les consoles les plus récentes. Mieux vaut tard que jamais.",
    "intro": "Si vous n’avez pas encore découvert Metro 2033 ou Metro Last Light dans leurs versions Redux, ce sera le moment ou jamais dès le 29 octobre sur PS5 et Xbox Series, puisque qu’une mise à jour gratuite pour les deux titres permettra d’apporter quelques améliorations technologiques.",
    "h2": "LES FAITS",
    "p1": "Le studio précise bien qu’il ne s’agit pas de viser un résultat proche d’un remaster, mais de proposer la prise en charge de certaines technologies, avec de meilleures animations et un rendu audio plus précis, tout en corrigeant quelques bugs au passage.",
    "quote": "Sur PS5 Pro, le PSSR sera par exemple activé et la manette DualSense mettra en avant ses gâchettes adaptatives, au même titre que l’anti-crénelage et l’audio spatial sur Xbox Series.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "Les jeux seront affichés en 4K et en 60 images par seconde, avec un upscaling possible jusqu’à 120 FPS si vous disposez d’un écran compatible. L’éclairage et les ombres seront revus, ainsi que les effets de particules. Le Xbox Play Anywhere sera activé, notamment pour jouer sur la ROG Xbox Ally.",
    "p3": "Et tout ceci sera évidemment gratuit. Pas peu fier de ce résultat impressionnant, Deep Silver vient aujourd&rsquo;hui nous annoncer que la licence Metro de 4A Games a dépassé les 50 [...]",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Les prochaines communications officielles préciseront la suite. De votre côté, quel élément mérite d’être surveillé en premier ? Dites-le dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "Le PC n’est pas oublié dans l’affaire, puisque le 22 octobre, une mise à jour permettra de profiter du DLSS et de l’audio spatial, en plus de quelques autres améliorations.",
    "source": "D’après ActuGaming, article consulté le 02.10.2026.",
    "sourceUrl": "https://www.actugaming.net/metro-2033-et-metro-last-light-se-mettent-a-jour-gratuitement-sur-ps5-et-xbox-series-828019/",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/metro-2033-et-metro-last-light-se-mettent-a-jour-gratuitemen-official.jpg",
    "officialThumbnailUrl": "https://static.actugaming.net/media/2016/05/metro-redux.jpg",
    "auto": true,
    "sourceName": "ActuGaming"
  },
  "les-jeux-resident-evil-posent-un-probleme-a-capcom-a-cause-d": {
    "slug": "les-jeux-resident-evil-posent-un-probleme-a-capcom-a-cause-d",
    "date": "02.10.2026",
    "category": "POP CULTURE · JEUXVIDEO.COM",
    "image": "news-auto/les-jeux-resident-evil-posent-un-probleme-a-capcom-a-cause-d-official.jpg",
    "imageAlt": "Les jeux Resident Evil posent un problème à Capcom : à cause des remakes, l'éditeur est désormais forcé de penser à des crossovers — visuel éditorial Let’s Play",
    "cover": "CAPCOM",
    "title": "LES JEUX RESIDENT",
    "accent": "EVIL POSENT UN.",
    "dek": "Entre remakes et nouveaux opus, la saga Resident Evil a su se réinventer en continuant de séduire les fans de la première heure tout en convainquant de nouveaux joueurs.",
    "lead": "Mais alors que les sorties s'enchaînent à un rythme soutenu, une question essentielle émerge : que se passera-t-il lorsque la ligne temporelle des remakes rattrapera enfin celle des jeux récents ? Quand nous avons posé les mains sur le remake de Resident Evil 2 en 2019, la claque a été monumental.",
    "intro": "Capcom ne se contentait pas de lisser quelques textures : l'éditeur dépoussiérait ses propres classiques sous le RE Engine en adaptant la formule aux exigences modernes. Depuis, la recette s'est déclinée avec succès.",
    "h2": "LES FAITS",
    "p1": "Nous avons eu droit à Resident Evil 3, puis à l’excellent Resident Evil 4 Remake qu’on a noté 18/20. En parallèle, la série a continué d'avancer avec des titres numérotés comme Resident Evil 7 Biohazard, véritable virage à 180 degrés à la première personne, suivi de Resident Evil Village et plus récemment de Resident Evil Requiem.",
    "quote": "En observant la chronologie de la série, Capcom va rapidement se heurter à deux cas d'école très particuliers : Resident Evil 5 et Resident Evil 6.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "La machine de guerre Resident Evil ne compte pas s'arrêter en si bon chemin, et le calendrier théorique de l'éditeur commence déjà à se dessiner pour les années à venir. Selon des informations partagées par sur IGN, la suite du programme s'annonce particulièrement chargée pour les amoureux du survival-horror :",
    "p3": "Si ces projets ont de quoi ravir les nostalgiques, la liste des jeux classiques restant à dépoussiérer s'amenuise progressivement. Et c'est là que le casse-tête commence pour Capcom. Le cinquième opus, malgré son immense carton commercial au moment de sa sortie, pose d'importants défis d'adaptation. Son cadre africain avait à l’époque suscité plusieurs polémiques… Quant à Resident Evil 6, le problème est avant tout d'ordre qualitatif. Orienté vers l'action débridée au détriment de l'angoisse, il reste le titre numéroté le moins bien noté de la franchise sur Metacritic. Faut-il le refaire à l'identique, ou le réinventer entièrement ? Conscient de cette “collision” inévitable entre le passé et le présent, Capcom prépare le terrain depuis un moment déjà.",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Chaque nouveau communiqué officiel permettra d’en savoir plus. Quel point doit-on suivre en priorité selon vous ? Répondez dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "Mais surtout, une fois arrivés à l'ère de Resident Evil 7, les remakes perdront de leur intérêt, ce septième volet étant déjà conçu sur les bases de la formule moderne.",
    "source": "D’après Jeuxvideo.com, article consulté le 02.10.2026.",
    "sourceUrl": "https://www.jeuxvideo.com/news/2107002/les-jeux-resident-evil-posent-un-probleme-a-capcom-a-cause-des-remakes-l-editeur-est-desormais-force-de-penser-a-des-crossovers.htm",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/les-jeux-resident-evil-posent-un-probleme-a-capcom-a-cause-d-official.jpg",
    "officialThumbnailUrl": "https://image.jeuxvideo.com/medias-crop-1200-675/179086/1790858512-1998-card.jpg",
    "auto": true,
    "sourceName": "Jeuxvideo.com"
  },
  "nintendo-avait-confie-le-developpement-d-un-jeu-zelda-a-ubis": {
    "slug": "nintendo-avait-confie-le-developpement-d-un-jeu-zelda-a-ubis",
    "date": "30.09.2026",
    "category": "NINTENDO · JEUXVIDEO.COM",
    "image": "news-auto/nintendo-avait-confie-le-developpement-d-un-jeu-zelda-a-ubis-official.jpg",
    "imageAlt": "Nintendo avait confié le développement d'un jeu Zelda à Ubisoft pour un projet dingue — visuel éditorial Let’s Play",
    "cover": "NINTENDO",
    "title": "NINTENDO AVAIT",
    "accent": "CONFIÉ LE DÉVELOPPEMENT.",
    "dek": "Une enquête révèle qu'Ubisoft Milan a secrètement développé un spin-off inédit de The Legend of Zelda centré sur Ganondorf. Récit d'une collaboration historique brisée net par le refus catégorique de Nintendo fin 2023.",
    "lead": "L'industrie du jeu vidéo conserve parfois ses secrets les plus fascinants dans l'ombre.",
    "intro": "Fin septembre 2026, une enquête menée sur plus de 18 mois par le journaliste Tom Henderson d'Insider Gaming a mis au jour les coulisses de ce qui aurait pu être l'un des crossovers les plus audacieux de la décennie.",
    "h2": "LES FAITS",
    "p1": "Après le succès d'estime des jeux de rôle tactiques Mario + The Lapins Crétins, le studio italien d'Ubisoft a tenté d'attaquer un tout autre monument de la firme de Kyoto : la saga Zelda. Acheter The Legend of Zelda : Ocarina of Time sur Nintendo Switch 2 chez Amazon",
    "quote": "Suite au lancement de Mario + The Lapins Crétins Sparks of Hope fin 2022, les équipes d'Ubisoft Milan bénéficient d'une cote de confiance au plus haut auprès de Nintendo.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "Porté par le directeur créatif Davide Soliani, un petit groupe de développeurs planche pendant l'hiver sur une proposition ambitieuse. L'idée prend forme sous le nom de code Goliath, un titre évocateur pour traduire la démesure de ce spin-off d'action et de narration. Initialement, le pitch ne prévoit pas de faire jouer Link ou d'investir le cadre traditionnel d'Hyrule.",
    "p3": "Les équipes conçoivent un personnage inédit afin d'échapper aux contraintes lourdes de la chronologie officielle. Séduite par le concept, la direction de Nintendo formule toutefois une contre-proposition majeure : abandonner le héros anonyme et placer Ganondorf, l'antagoniste emblématique de la franchise, au cœur du gameplay. Le choix d'incarner le Seigneur du Mal contraint Ubisoft Milan à revoir totalement sa formule narrative et mécanique. Le projet prend une tournure plus sombre, pensant le personnage comme un anti-héros complexe et nuancé. Fin novembre 2023, le prototype est officiellement soumis au constructeur japonais. Malgré les efforts déployés pour marier la force brute du personnage à l'exigence de la licence, la sentence tombe : Nintendo rejette la proposition et met fin au projet Goliath.",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Chaque nouveau communiqué officiel permettra d’en savoir plus. Quel point doit-on suivre en priorité selon vous ? Répondez dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "L'objectif fixé pour l'année 2023 consiste à concevoir une version de démonstration technique (une « vertical slice ») pour convaincre Nintendo.",
    "source": "D’après Jeuxvideo.com, article consulté le 30.09.2026.",
    "sourceUrl": "https://www.jeuxvideo.com/news/2106514/nintendo-avait-confie-le-developpement-d-un-jeu-zelda-a-ubisoft-pour-un-projet-dingue.htm",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/nintendo-avait-confie-le-developpement-d-un-jeu-zelda-a-ubis-official.jpg",
    "officialThumbnailUrl": "https://image.jeuxvideo.com/medias-crop-1200-675/179067/1790674670-6413-card.jpg",
    "auto": true,
    "sourceName": "Jeuxvideo.com"
  },
  "intergalactic-the-heretic-prophet-ne-se-montrera-pas-avant-2": {
    "slug": "intergalactic-the-heretic-prophet-ne-se-montrera-pas-avant-2",
    "date": "29.09.2026",
    "category": "ACTUALITÉ · ACTUGAMING",
    "image": "news-auto/intergalactic-the-heretic-prophet-ne-se-montrera-pas-avant-2-official.jpg",
    "imageAlt": "Intergalactic: The Heretic Prophet ne se montrera pas avant 2027, mais un nouvel artwork a été révélé — visuel éditorial Let’s Play",
    "cover": "NAUGHTY DOG",
    "title": "INTERGALACTIC: THE",
    "accent": "HERETIC PROPHET NE.",
    "dek": "Chaque année, Naughty Dog organise le Last of Us Day pour annoncer tout un tas de produits dérivés autour de sa licence fétiche.",
    "lead": "Mais 2026 est une année spéciale puisque le studio a la tête tournée vers les étoiles, avec un Intergalactic: The Heretic Prophet qui se fait attendre de pied ferme.",
    "intro": "Alors pour l’occasion, Neil Druckmann a bien voulu adresser un mot sur l’état de ce projet, et nous dire de patienter encore quelques mois. On pensait qu’avec une sortie prévue pour 2027, les prochains Game Awards seraient l’occasion idéale pour célébrer le retour d’ Intergalactic: The Heretic Prophet.",
    "h2": "LES FAITS",
    "p1": "Loupé. Neil Druckmann prévient que l’équipe en charge du jeu n’est pas encore tout à fait prête à nous en montrer davantage cette année, même si le tournage est désormais bouclé, et promet donc une présentation complète du jeu pour 2027, pas avant : « Nous tenons à clarifier les choses : nous resterons muets pour le reste de l’année.",
    "quote": "On se contentera de cela en attendant 2027, en espérant que le jeu sorte bien l’année prochaine.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "En 2027, ça changera. Nous dévoilerons alors pleinement Intergalactic: The Heretic Prophet et vous donnerons un véritable aperçu de l’aventure de science-fiction dans laquelle s’embarque Jordan. Nous savons que cela fait un moment que nous n’avons rien partagé avec vous.",
    "p3": "Nous ne tenons pas votre soutien pour acquis. D’ici là… Endurez et survivez ! » Néanmoins, on peut se consoler avec un nouvel artwork qui, il est vrai, ne montre rien de véritablement neuf par rapport au premier teaser. On y voit Jordan, protagoniste de cet Intergalactic: The Heretic Prophet, s’aventurer sur une planète sans doute très hostile, avec quelques bouts de technologies cachés. Mais 2026 est [...]",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Chaque nouveau communiqué officiel permettra d’en savoir plus. Quel point doit-on suivre en priorité selon vous ? Répondez dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "Nous travaillons d’arrache-pied pour créer quelque chose qui soit à la hauteur de votre patience.",
    "source": "D’après ActuGaming, article consulté le 29.09.2026.",
    "sourceUrl": "https://www.actugaming.net/intergalactic-the-heretic-prophet-ne-se-montrera-pas-avant-2027-827202/",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/intergalactic-the-heretic-prophet-ne-se-montrera-pas-avant-2-official.jpg",
    "officialThumbnailUrl": "https://static.actugaming.net/media/2026/09/Intergalactic-889x500.jpg",
    "auto": true,
    "sourceName": "ActuGaming"
  },
  "disponible-aujourd-hui-qu-apporte-concretement-the-witcher-3": {
    "slug": "disponible-aujourd-hui-qu-apporte-concretement-the-witcher-3",
    "date": "29.09.2026",
    "category": "NINTENDO · GAMEKULT",
    "image": "news-auto/disponible-aujourd-hui-qu-apporte-concretement-the-witcher-3-official.jpg",
    "imageAlt": "Disponible aujourd'hui, qu'apporte concrètement The Witcher 3 : Wild Hunt Remastered par rapport au jeu d'origine ? — visuel éditorial Let’s Play",
    "cover": "NINTENDO",
    "title": "DISPONIBLE",
    "accent": "AUJOURD'HUI, QU'APPORTE.",
    "dek": "The Witcher 3 : Wild Hunt Remastered sera disponible dès aujourd'hui (à midi) sur PC (Steam, GOG, Epic Games Store, Battle.net), PlayStation 5, Xbox Series X/S et Nintendo Switch 2, et absolument tout le monde peut en profiter, surtout si vous aviez déjà le jeu d'origine.",
    "lead": "On rappelle en effet que les joueurs qui possèdent déjà le jeu, en version physique ou numérique, passent gratuitement à l'édition remasterisée dès aujourd'hui sur la même plateforme.",
    "intro": "Présenté il y a quelques semaines, le Witcher 3 nouveau est là dès aujourd'hui, et s'accompagne entre autres de modifications visuelles majeures. Ainsi, le jeu adopte par exemple un nouveau modèle de shader et reprend de nombreux modèles et textures issus du mod The Witcher 3 HD Reworked Project.",
    "h2": "LES FAITS",
    "p1": "L'éclairage et les ombres de l'herbe et de la végétation sont améliorés, les signes et les compétences reçoivent de nouveaux effets visuels, et le moteur passe à un rendu natif sous DirectX 12 avec prise en charge du multithreading.",
    "quote": "The Witcher 3 : Wild Hunt Remastered est disponible dès aujourd'hui sur PS5, Xbox Series X/S, Switch 2 et PC.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "S'y ajoutent une mise à jour du tone mapping, le GTAO dans les options d'occlusion ambiante, de nouveaux réglages HDR, le Ray-Traced HairWorks pour les chevelures, un \" flou cinétique plus cinématographique \", un Subsurface Scattering revu pour la peau, un éclairage basé sur l'image (IBL) et un effet Bloom refondu.",
    "p3": "En voilà, des termes techniques incompréhensibles pour le commun des mortels dont l'unique but est de signifier ceci : logiquement, Geralt devrait être plus beau. L'intérêt principal de ce travail sur The Witcher 3 par CDProjekt tient plutôt à ses améliorations de gameplay : les compétences s'organisent désormais en arbre, chacune comportant trois rangs, avec certaines qui exigent d'avoir débloqué des prérequis plutôt que d'avoir investi un nombre précis de points. CD Projekt Red prévient que vos points de compétence seront réinitialisés en raison de cette refonte, qui s'accompagne aussi d'un rééquilibrage des bonus, effets et synergies, et du renommage de certaines compétences. Il devient aussi possible de reforger son équipement pour en changer l'apparence sans toucher aux statistiques, ce service étant proposé uniquement par les maîtres artisans Yoana et Hattori.",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Les prochaines communications officielles préciseront la suite. De votre côté, quel élément mérite d’être surveillé en premier ? Dites-le dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "Mise à jour de nombreux modèles et textures à partir des ressources du mod The Witcher 3 HD Reworked Project.",
    "source": "D’après Gamekult, article consulté le 29.09.2026.",
    "sourceUrl": "https://www.gamekult.com/actualite/disponible-aujourd-hui-qu-apporte-concretement-the-witcher-3-wild-hunt-remastered-par-rapport-au-jeu-d-origine-3050872234.html",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/disponible-aujourd-hui-qu-apporte-concretement-the-witcher-3-official.jpg",
    "officialThumbnailUrl": "https://cdn.gamekult.com/optim/images/news/30/3050872234/disponible-aujourd-hui-qu-apporte-concretement-the-witcher-3-wild-hunt-remastered-par-rapport-au-jeu-d-origine-269e9377__1920_1080__0-152-1920-773.jpg",
    "auto": true,
    "sourceName": "Gamekult"
  },
  "xbox-le-patron-de-microsoft-trouve-que-le-travail-de-rationa": {
    "slug": "xbox-le-patron-de-microsoft-trouve-que-le-travail-de-rationa",
    "date": "28.09.2026",
    "category": "XBOX · ACTUGAMING",
    "image": "news-auto/xbox-le-patron-de-microsoft-trouve-que-le-travail-de-rationa-official.jpg",
    "imageAlt": "Xbox : Le patron de Microsoft trouve que « le travail de rationalisation » effectué par Asha Sharma est « beau à voir » — visuel éditorial Let’s Play",
    "cover": "XBOX",
    "title": "XBOX : LE PATRON DE",
    "accent": "MICROSOFT TROUVE.",
    "dek": "Pendant qu’une partie de l’industrie se lamente de la situation dans laquelle est Xbox aujourd’hui, Satya Nadella dort sur ses deux oreilles.",
    "lead": "Le patron de Microsoft a déjà prouvé qu’il ne risquait pas de s’étouffer par surplus d’empathie par le passé, mais au micro d’Alex Heath, il montre une nouvelle fois qu’il n’a aucune pensée pour celles et ceux mis à la porte, tant que l’argent est là.",
    "intro": "Après tout, il ne faudrait pas demander à un PDG d’une grosse boîte de la tech d’agir avec un peu de décence et d’humanité. Ils ne sont pas là pour ça et ont probablement oublié comment faire.",
    "h2": "LES FAITS",
    "p1": "Satya Nadella en est un exemple frappant, surtout à quelques jours d’une nouvelle vague de licenciements chez Xbox. Interrogé sur la situation du groupe, le grand manitou de Microsoft se sent très bien dans ses baskets et vante les mérites de la « rationalisation » effectuée par Asha Sharma (puisqu’il ne faudrait surtout pas appeler un chat un chat), qui est « beau à voir » :",
    "quote": "Cela a toujours été notre but, qui est d’être à la fois un excellent éditeur et un fabricant de plateforme majeur pour les jeux, aussi bien sur PC que sur Xbox.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "« Je suis très enthousiaste à propos des licences dont nous disposons actuellement. Si je considère les studios, le portefeuille de licences que nous possédons et notre capacité à nous appuyer sur ces atouts pour produire d’excellents jeux à l’avenir, je suis très confiant. L’équipe, et Asha en particulier, mène un travail de rationalisation, qui est beau à voir. »",
    "p3": "On notera qu’il parle des licences avant des équipes, ce qui est loin d’être un détail tant la réorganisation chez Xbox de la semaine dernière a prouvé que ce sont les marques qui comptent, plutôt que les équipes. Qu’importe les personnes derrière le prochain Halo, tant qu’il y a un jeu Halo. Nadella se montre ensuite optimiste quant au futur de Xbox en pensant qu’un retour à la croissance est possible dès la prochaine année fiscale, ce qui sera sans doute facilité par les 3 200 salaires en moins à payer : « Il nous faut ensuite inventer le bon modèle économique durable qui nous permette de proposer des jeux vidéo à de plus en plus de monde.",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Chaque nouveau communiqué officiel permettra d’en savoir plus. Quel point doit-on suivre en priorité selon vous ? Répondez dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "Pendant qu&rsquo;une partie de l&rsquo;industrie se lamente de la situation dans laquelle est Xbox aujourd&rsquo;hui, Satya Nadella dort sur ses deux [...]",
    "source": "D’après ActuGaming, article consulté le 28.09.2026.",
    "sourceUrl": "https://www.actugaming.net/xbox-le-patron-de-microsoft-trouve-que-le-travail-de-rationalisation-effectue-par-asha-sharma-est-formidable-827061/",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/xbox-le-patron-de-microsoft-trouve-que-le-travail-de-rationa-official.jpg",
    "officialThumbnailUrl": "https://static.actugaming.net/media/2025/07/xbox.jpg",
    "auto": true,
    "sourceName": "ActuGaming"
  },
  "physint-un-budget-de-400-millions-de-dollars-pour-le-jeu-de": {
    "slug": "physint-un-budget-de-400-millions-de-dollars-pour-le-jeu-de",
    "date": "28.09.2026",
    "category": "PLAYSTATION · ACTUGAMING",
    "image": "news-auto/physint-un-budget-de-400-millions-de-dollars-pour-le-jeu-de-official.jpg",
    "imageAlt": "Physint : Un budget de 400 millions de dollars pour le jeu de Kojima ? Xbox aurait signé pour beaucoup moins que cela — visuel éditorial Let’s Play",
    "cover": "PLAYSTATION",
    "title": "PHYSINT : UN BUDGET",
    "accent": "DE 400 MILLIONS DE.",
    "dek": "En repêchant Hideo Kojima suite à sa rupture avec PlayStation, Xbox a fait un joli coup. Reste encore à savoir si celui-ci va s’avérer rentable.",
    "lead": "Les échos obtenus par Bloomberg concernant le retrait de Sony évoquaient une production qui accumulait les retards et qui dépassait déjà son budget, alors que les derniers jeux du studio n’avaient pas été des machines de rentabilité.",
    "intro": "La question est donc de savoir si Physint pourra rapporter quelque chose à Xbox, et pour le savoir, il faudra déjà connaître son budget. 400 millions de dollars, c’est le chiffre ahurissant qui a tourné en boucle ce week-end à propos du budget de Physint.",
    "h2": "LES FAITS",
    "p1": "Il nous vient du journaliste Christopher Dring, qui a déclaré cela dans son podcast. Pour clarifier la chose, il a ensuite précisé qu’il s’agissait d’un bruit de couloir qu’il avait entendu, et non d’un chiffre précis.",
    "quote": "Cela dit, une personne chez Xbox ayant une connaissance directe de l’accord m’a indiqué que le contrat pour Physint avait été signé pour un montant nettement inférieur. »",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "Un tel budget n’étonne même plus aujourd’hui tant on sait à quel point les prix ont flambé autour de la production AAA, mais souvent, on parle de AAA produits aux États-Unis, où les salaires sont plus élevés. Pour une production japonaise, cela semblait tout à fait excessif et peu vraisemblable.",
    "p3": "Jason Schreier a quant à lui déclaré qu’il ne connaissait pas le véritable budget de Physint, mais selon ses sources, Xbox a conclu un accord avec Kojima Productions pour un budget « nettement inférieur » : « Car il y a beaucoup de chiffres différents ici : Il y a le chiffre initial pour Physint avec PlayStation, le budget vers lequel le projet se dirigeait, le chiffre évoqué lors des négociations, le coût estimé si certaines stars de premier plan avaient été impliquées, le montant accepté par Xbox et, enfin, le coût réel que le proejt aurait coûté à sa sortie. Même pour ce joli coup de pub, on imagine en effet assez mal Xbox être prêt à s’engager sur un budget aussi conséquent, surtout lorsque Microsoft cherche à faire toutes les économies possibles dans sa branche gaming. Reste encore à savoir si celui-ci va s&rsquo;avérer [...]",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Les prochaines communications officielles préciseront la suite. De votre côté, quel élément mérite d’être surveillé en premier ? Dites-le dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "J’hésite à avancer des chiffres précis sans avoir vu les documents ou sans les avoir recoupés auprès de plusieurs sources directes.",
    "source": "D’après ActuGaming, article consulté le 28.09.2026.",
    "sourceUrl": "https://www.actugaming.net/physint-un-budget-de-400-millions-de-dollars-pour-le-jeu-de-kojima-xbox-aurait-signe-pour-beaucoup-moins-que-cela-827065/",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/physint-un-budget-de-400-millions-de-dollars-pour-le-jeu-de-official.jpg",
    "officialThumbnailUrl": "https://static.actugaming.net/media/2025/09/Physint.jpg",
    "auto": true,
    "sourceName": "ActuGaming"
  },
  "si-les-quetes-de-the-witcher-sont-parmi-les-meilleures-du-je": {
    "slug": "si-les-quetes-de-the-witcher-sont-parmi-les-meilleures-du-je",
    "date": "27.09.2026",
    "category": "ACTUALITÉ · JEUXVIDEO.COM",
    "image": "news-auto/si-les-quetes-de-the-witcher-sont-parmi-les-meilleures-du-je-official.webp",
    "imageAlt": "Si les quêtes de The Witcher sont parmi les meilleures du jeu vidéo, c'est parce qu'elles respectent ces deux règles — visuel éditorial Let’s Play",
    "cover": "THE WITCHER",
    "title": "SI LES QUÊTES DE THE",
    "accent": "WITCHER SONT PARMI.",
    "dek": "Si la saga du Sorceleur a marqué l'histoire du RPG à tout jamais, ce n'est pas uniquement pour son univers sombre ou ses combats à l'épée.",
    "lead": "C'est avant tout grâce à l'écriture clinique de ses quêtes, façonnée par un principe fondamental : vous forcer à lâcher votre manette pour peser le poids de vos actes. Quand on évoque les aventures de Geralt de Riv, une poignée de souvenirs revient immédiatement en mémoire.",
    "intro": "Notamment des conversations sous haute tension avec des choix aux conséquences dévastatrices. Loin d'être un hasard de conception, cette réussite narrative repose sur une méthodologie stricte initiée par Marcin Blacha, responsable de la narration chez CD Projekt RED depuis le premier volet.",
    "h2": "LES FAITS",
    "p1": "Pour comprendre pourquoi les quêtes de The Witcher 3: Wild Hunt résonnent encore chez les joueurs des années après leur découverte, il faut plonger dans la mécanique d'un écriture qui refuse catégoriquement les compromis. L'ADN narratif de la licence trouve ses racines dans l'œuvre littéraire d'Andrzej Sapkowski.",
    "quote": "Contrairement aux RPG traditionnels où l'on cherche à accumuler des points de vertu, The Witcher vous confronte à des miroirs de la nature humaine.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "Dès les premières étapes de développement, l'équipe menée par Marcin Blacha a fait le choix de bannir les systèmes de morale classiques. Pas de jauge de karma, pas d'alignement bon ou mauvais, ni d'option \"gentille\" nettement surlignée en bleu dans un menu de dialogue. Le monde de Geralt est un marécage moral où chaque alternative débouche sur un compromis amer.",
    "p3": "L'objectif n'est pas de vous proposer une fable héroïque face à un mal cosmique abstrait, mais de vous plonger dans des tragédies intimes, poignantes et souvent insolubles. Il existe un indicateur infaillible pour mesurer la qualité d'une quête selon les équipes de CD Projekt RED. Une écriture est considérée comme réussie lorsque le script provoque un tel choc ou un tel dilemme que le joueur s'arrête, pose sa manette et commence à réfléchir longuement à ce qu'il doit faire. Pour obtenir cet effet, les scénaristes appliquent deux règles fondamentales : L'exemple le plus emblématique reste l'arc du Baron Sanglant. Placé face à un dilemme tragique entre la vie d'enfants orphelins et le salut de l'épouse du Baron, le joueur réalise qu'il n'existe aucune fin heureuse. Quoi qu'il décide, il y aura des victimes. Cette absence d'option rassurante impose une véritable responsabilité morale.",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Les prochaines communications officielles préciseront la suite. De votre côté, quel élément mérite d’être surveillé en premier ? Dites-le dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "Cette approche découle d'un constat simple : adapter la profondeur psychologique d'un roman en expérience interactive demande de placer le joueur face à ses propres valeurs.",
    "source": "D’après Jeuxvideo.com, article consulté le 27.09.2026.",
    "sourceUrl": "https://www.jeuxvideo.com/news/2106091/si-les-quetes-de-the-witcher-sont-parmi-les-meilleures-du-jeu-video-c-est-parce-qu-elles-respectent-ces-deux-regles.htm",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "mixed",
    "thumbnail": "news-auto/si-les-quetes-de-the-witcher-sont-parmi-les-meilleures-du-je-official.webp",
    "officialThumbnailUrl": "https://image.jeuxvideo.com/medias-crop-1200-675/179026/1790261539-9009-card.jpg",
    "auto": true,
    "sourceName": "Jeuxvideo.com"
  },
  "avant-gta-rockstar-travaillait-sur-un-jeu-kirby-annule-il-vi": {
    "slug": "avant-gta-rockstar-travaillait-sur-un-jeu-kirby-annule-il-vi",
    "date": "27.09.2026",
    "category": "NINTENDO · GAMEKULT",
    "image": "news-auto/avant-gta-rockstar-travaillait-sur-un-jeu-kirby-annule-il-vi-official.jpg",
    "imageAlt": "Avant GTA, Rockstar travaillait sur un jeu Kirby annulé : il vient d'être recréé et rendu jouable — visuel éditorial Let’s Play",
    "cover": "NINTENDO",
    "title": "AVANT GTA, ROCKSTAR",
    "accent": "TRAVAILLAIT SUR UN.",
    "dek": "En des temps anciens où Rockstar North s'appelait encore DMA Design et n'avait pas pondu Grand Theft Auto, Nintendo avait confié au studio écossais le développement d'un jeu inédit pour la Super Nintendo, un certain Kid Kirby.",
    "lead": "Le projet a été annulé en cours de route, mais un fan vient de se mettre en tête de le ressusciter en mettant soi-même les mains dans le cambouis.",
    "intro": "C'est une jolie surprise que nous avons là : Kid Kirby vient d'être recréé de toutes pièces et rendu jouable sur PC par NovaStar, un développeur amateur et indépendant.",
    "h2": "LES FAITS",
    "p1": "Le héros du jour s'est appuyé sur divers documents de conception et des ressources partagés publiquement au fil des années par d'anciens membres de DMA Design. Parce que oui, c'est bien là le problème : très peu d'images officielles du projet ont été publiées à l'époque, dans les années 90. Voici d'ailleurs tout ce que l'on peut trouver.",
    "quote": "Le titre avait été pensé à l'époque pour exploiter la souris de la Super Nintendo, et comprenait de nombreux éléments 3D et 2D.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "Mais en glanant des informations çà et là, NovaStar a quand même pu livrer sa propre interprétation d'un jeu prématurément jeté à la poubelle. On parle tout de même d'une campagne complète composée de huit niveaux distincts, introduisant chacun de nouvelles mécaniques, avec également un boss au programme. Pour la petite histoire, Kid Kirby n'était pas un jeu comme les autres.",
    "p3": "Cette version fanmade reprend donc le concept : ici, le joueur utilise le clic de sa souris pour attraper Kirby, l'étirer vers l'arrière puis le relâcher pour le propulser à travers les décors. En éliminant certains adversaires, il est possible de s'approprier des pouvoirs emblématiques, activables avec le clic droit, pour une durée de dix secondes. Cette petite aventure est aussi ponctuée de phases de vol sous la forme d'un avion en papier, où l'on doit jongler entre la perte d'altitude et le gain de vitesse pour planer sur de longues distances (le développeur avoue d'ailleurs s'être inspiré de Paper Mario : La Porte Millénaire). Bref, ce jeu fanmade est disponible gratuitement en téléchargement ici.",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Chaque nouveau communiqué officiel permettra d’en savoir plus. Quel point doit-on suivre en priorité selon vous ? Répondez dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "Le gameplay se base d'ailleurs entièrement sur la gravité et l'élan du personnage, comme DMA Design l'avait imaginé à l'époque (plus ou moins, on imagine).",
    "source": "D’après Gamekult, article consulté le 27.09.2026.",
    "sourceUrl": "https://www.gamekult.com/actualite/avant-gta-rockstar-travaillait-sur-un-jeu-kirby-annule-il-vient-d-etre-recree-et-rendu-jouable-3050872142.html",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "mixed",
    "thumbnail": "news-auto/avant-gta-rockstar-travaillait-sur-un-jeu-kirby-annule-il-vi-official.jpg",
    "officialThumbnailUrl": "https://cdn.gamekult.com/optim/images/news/30/3050872142/avant-gta-rockstar-travaillait-sur-un-jeu-kirby-annule-il-vient-d-etre-recree-et-jouable-e2aa4c49__1920_1080__0-107-547-283.jpg",
    "auto": true,
    "sourceName": "Gamekult"
  },
  "nintendo-97-cartouches-d-une-edition-jamais-vue-de-super-mar": {
    "slug": "nintendo-97-cartouches-d-une-edition-jamais-vue-de-super-mar",
    "date": "26.09.2026",
    "category": "NINTENDO · GAMEKULT",
    "image": "news-auto/nintendo-97-cartouches-d-une-edition-jamais-vue-de-super-mar-official.jpg",
    "imageAlt": "Nintendo : 97 cartouches d'une édition jamais vue de Super Mario Bros. retrouvées dans un grenier — visuel éditorial Let’s Play",
    "cover": "NINTENDO",
    "title": "SUPER MARIO BROS.",
    "accent": "ÉDITION INÉDITE.",
    "dek": "Quand on cause Super Mario Bros., généralement, il est rare d'apprendre quelque chose de nouveau : c'est peut-être le titre le plus poncé de l'histoire.",
    "lead": "Que nenni : le site Nintendo Wire déclare avoir récemment trouvé une édition inédite du jeu et, qui plus est, dans un carton qui renfermait près de cent cartouches dans un état impeccable. Prenez vous un café, on vous raconte tout ça.",
    "intro": "Comme son nom l'indique assez bien, Nintendo Wire est un média consacré à l'actualité Nintendo. Son créateur, Jason Ganos, est un Américain qui vit dans le Wisconsin.",
    "h2": "LES FAITS",
    "p1": "Il avait l'habitude de travailler avec Kevin Braun, un propriétaire de boutiques rétro. Bref, après sa mort, son fils hérite d'un carton rempli de cartouches NES. Genre, rempli à ras bord.",
    "quote": "Visiblement destinés à être fondus puis recyclés (c'est l'or qui se trouve sur les broches qui était dans le viseur), les jeux sont finalement restés là, intacts.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "L'homme ignorait quoi en faire et l'a donc gardé chez lui pendant une vingtaine d'années.",
    "p3": "",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Chaque nouveau communiqué officiel permettra d’en savoir plus. Quel point doit-on suivre en priorité selon vous ? Répondez dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "",
    "source": "D’après Gamekult, article consulté le 26.09.2026.",
    "sourceUrl": "https://www.gamekult.com/actualite/nintendo-97-cartouches-d-une-edition-jamais-vue-de-super-mario-bros-retrouvees-dans-un-grenier-3050872192.html",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/nintendo-97-cartouches-d-une-edition-jamais-vue-de-super-mar-official.jpg",
    "officialThumbnailUrl": "https://cdn.gamekult.com/optim/images/news/30/3050872192/nintendo-97-cartouches-d-une-edition-jamais-vue-de-super-mario-bros-retrouvees-dans-un-grenier-dfb868d4__1920_1080__0-34-1000-357.jpg",
    "auto": true,
    "sourceName": "Gamekult"
  },
  "memoire-cash-castlevania-avant-le-metroidvania-le-chef-d-uvr": {
    "slug": "memoire-cash-castlevania-avant-le-metroidvania-le-chef-d-uvr",
    "date": "26.09.2026",
    "category": "PLAYSTATION · GAMEKULT",
    "image": "news-auto/memoire-cash-castlevania-avant-le-metroidvania-le-chef-d-uvr-official.jpg",
    "imageAlt": "Mémoire cash - Castlevania : avant le Metroidvania, le chef-d'œuvre de Konami était surtout un hommage au cinéma d'horreur — visuel éditorial Let’s Play",
    "cover": "PLAYSTATION",
    "title": "CASTLEVANIA 1986",
    "accent": "NÉ DU CINÉMA.",
    "dek": "Dans la mémoire collective des joueurs, la saga Castlevania évoque immédiatement les capes flottantes d'Alucard, les cartes remplies ras la gueule, la montée en puissance d'un héros et les envolées de violons baroques popularisées par Koji Igarashi sur PlayStation.",
    "lead": "Ce qui est tout à fait exact. Mais il faut y ajouter le fait que l'acte fondateur Castlevania (Akumajo Dracula), bien avant d'inventer la moitié du mot-valise Metroidvania, était surtout une virée en mode train fantôme dans le panthéon du cinéma d'horreur des années 30 à 60.",
    "intro": "Dès que notre bon Simon Belmont franchit la grille du domaine sous un ciel d'orage sur NES, le contrat est clair. Pas de monologue tragique, pas de poésie victorienne ampoulée, ce Castlevania veut juste vous offrir un tour de grand huit de l'horreur, sans s'embarrasser de fioritures.",
    "h2": "LES FAITS",
    "p1": "Les développeurs de Konami ont simplement ont pillé sans retenue l'âge d'or des monstres de la Universal et de la Hammer pour le balancer cul par-dessus tête dans un couloir d'action pure. On esquive d'abord une chauve-souris géante, avant de croiser la tête volante de Médusa, puis deux momies ressuscitées tout droit sorties de La Malédiction des pharaons de Terence Fisher (on reparle de lui juste après).",
    "quote": "",
    "quoteBy": "",
    "h2b": "LE CONTEXTE",
    "p2": "Deux étages plus haut, le monstre de Frankenstein débarque flanqué de son sidekick bossu survolté qui sautille partout pour pourrir la trajectoire du joueur.",
    "p3": "",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Chaque nouveau communiqué officiel permettra d’en savoir plus. Quel point doit-on suivre en priorité selon vous ? Répondez dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "",
    "source": "D’après Gamekult, article consulté le 26.09.2026.",
    "sourceUrl": "https://www.gamekult.com/actualite/castlevania-avant-le-metroidvania-le-chef-d-oeuvre-de-konami-etait-surtout-un-hommage-au-cinema-d-horreur-3050872211.html",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "mixed",
    "thumbnail": "news-auto/memoire-cash-castlevania-avant-le-metroidvania-le-chef-d-uvr-official.jpg",
    "officialThumbnailUrl": "https://cdn.gamekult.com/optim/images/news/30/3050872211/castlevania-1986-53224fee__1920_1080__0-369-1600-887.jpg",
    "auto": true,
    "sourceName": "Gamekult"
  },
  "dawngazer-apres-unicorn-overlord-et-13-sentinels-aegis-rim-t": {
    "slug": "dawngazer-apres-unicorn-overlord-et-13-sentinels-aegis-rim-t",
    "date": "25.09.2026",
    "category": "NINTENDO · GAMEKULT",
    "image": "news-auto/dawngazer-apres-unicorn-overlord-et-13-sentinels-aegis-rim-t-official.jpg",
    "imageAlt": "Dawngazer : après Unicorn Overlord et 13 Sentinels : Aegis Rim, Takafumi Noma (Vanillaware) fait le choix de l'action/RPG — visuel éditorial Let’s Play",
    "cover": "NINTENDO",
    "title": "DAWNGAZER",
    "accent": "L’ACTION/RPG DE NOMA.",
    "dek": "Monochrome Corporation et Good Smile Company ont présenté Dawngazer, un nouvel action-RPG attendu pour 2028 sur PC, PS5 et Nintendo Switch 2. Pour rappel, Noma a quitté Vanillaware en mars 2025 (juste après la sortie de Unicorn Overlord).",
    "lead": "Le titre marquera en outre les débuts d'Ignisphere Studio, structure fondée par Takafumi Noma, vétéran de Vanillaware connu comme réalisateur et character designer d'Unicorn Overlord en 2024, et qui avait également contribué à 13 Sentinels : Aegis Rim, Dragon's Crown Pro et Odin Sphere Leifthrasir.",
    "intro": "",
    "h2": "LES FAITS",
    "p1": "Dawngazer sera le tout premier projet Ignisphere, qui représente à la fois le nom d'une nouvelle filiale interne à Monochrome Corp dirigée par Takafumi Noma, mais aussi la licence originale bâtie conjointement par Monochrome Corp et Good Smile Company à l'occasion du 15e anniversaire du studio.",
    "quote": "Ce nouveau projet Dawngazer sera l'occasion pour Takafumi Noma d'effectuer un retour vers l'action/RPG (il avait déjà travaillé sur Odin Sphere Leifthrasir et Dragon's Crown Pro).",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CONTEXTE",
    "p2": "Selon lui, la sensation de prise en main immédiate et le plaisir manette en main reposent sur l'accumulation de détails minutieux, à savoir la réactivité des commandes, l'impact ressenti lors d'un coup porté, la gestion de la distance avec l'adversaire.",
    "p3": "",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Chaque nouveau communiqué officiel permettra d’en savoir plus. Quel point doit-on suivre en priorité selon vous ? Répondez dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "",
    "source": "D’après Gamekult, article consulté le 25.09.2026.",
    "sourceUrl": "https://www.gamekult.com/actualite/dawngazer-apres-unicorn-overlord-et-13-sentinels-aegis-rim-takafumi-noma-vanillaware-fait-le-choix-de-l-action-rpg-3050872205.html",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/dawngazer-apres-unicorn-overlord-et-13-sentinels-aegis-rim-t-official.jpg",
    "officialThumbnailUrl": "https://cdn.gamekult.com/optim/images/news/30/3050872205/dawngazer-apres-unicorn-overlord-et-13-sentinels-aegis-rim-takafumi-noma-vanillaware-fait-le-choix-de-l-action-rpg-75cd5f66__1920_1080__0-480-3840-1721.jpg",
    "auto": true,
    "sourceName": "Gamekult"
  },
  "valor-mortis-sortie-24-septembre-2026": {
    "slug": "valor-mortis-sortie-24-septembre-2026",
    "date": "24.09.2026",
    "category": "ACTION-RPG · ONE MORE LEVEL",
    "image": "news-auto/valor-mortis-sortie-24-septembre-2026-official.jpg",
    "imageAlt": "Valor Mortis — miniature officielle du trailer de sortie",
    "cover": "VALOR MORTIS",
    "title": "VALOR MORTIS",
    "accent": "SORT DE L’ENFER.",
    "dek": "La campagne napoléonienne bascule dans le surnaturel. Valor Mortis arrive le 24 septembre 2026 sur PS5, Xbox Series X|S et Steam avec une proposition d’action-RPG à la première personne.",
    "lead": "Le jeu suit William, un ancien soldat de l’armée de Napoléon revenu d’entre les morts. One More Level mêle combats exigeants, pouvoirs surnaturels et exploration d’une Europe déformée par une épidémie mystérieuse.",
    "intro": "Valor Mortis utilise le cadre des guerres napoléoniennes pour construire un monde de dark fantasy. Le joueur incarne William, qui doit comprendre ce qui l’a ramené à la vie tout en affrontant des ennemis et des créatures issus de cette version altérée de l’Histoire.",
    "h2": "NAPOLÉON APRÈS LA MORT",
    "p1": "Le studio One More Level associe affrontements au corps à corps, capacités surnaturelles et déplacements acrobatiques. Cette combinaison doit donner au jeu une identité différente des Soulslike plus traditionnels joués à la troisième personne. La sortie couvre les consoles de génération actuelle et le PC via Steam.",
    "quote": "Le jeu transforme le Soulslike en récit de survie militaire, avec la première personne comme ligne de front.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "UN COMBAT À LA PREMIÈRE PERSONNE",
    "p2": "Le trailer officiel révèle le ton, le personnage de William et plusieurs menaces de cette campagne surnaturelle, tandis que la difficulté et la variété des situations devront être vérifiées manette en main.",
    "p3": "",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Les prochaines communications officielles préciseront la suite. De votre côté, quel élément mérite d’être surveillé en premier ? Dites-le dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "",
    "source": "D’après le communiqué de lancement officiel publié via GamesPress.",
    "sourceUrl": "https://www.gamespress.com/Valor-Mortis-Arrives-September-24-on-Xbox-PlayStation-and-PC-Launches-",
    "sourceDetail": "Lire le communiqué",
    "sourceName": "ONE MORE LEVEL",
    "video": "X3ItbfcUb3Y",
    "videoTitle": "Valor Mortis — Official Release Date Trailer",
    "thumbnail": "news-auto/valor-mortis-sortie-24-septembre-2026-official.jpg",
    "officialThumbnailUrl": "https://i.ytimg.com/vi/X3ItbfcUb3Y/maxresdefault.jpg",
    "auto": true,
    "credit": "Miniature officielle : https://i.ytimg.com/vi/X3ItbfcUb3Y/maxresdefault.jpg",
    "sentiment": "positive"
  },
  "silent-hill-townfall-sortie-24-septembre-2026": {
    "slug": "silent-hill-townfall-sortie-24-septembre-2026",
    "date": "24.09.2026",
    "category": "HORREUR · KONAMI",
    "image": "news-auto/silent-hill-townfall-sortie-24-septembre-2026-official.jpg",
    "imageAlt": "SILENT HILL: Townfall — miniature officielle du trailer de lancement",
    "cover": "SILENT HILL",
    "title": "SILENT HILL",
    "accent": "RETOUR À LA BRUME.",
    "dek": "SILENT HILL: Townfall sort le 24 septembre 2026 sur PlayStation 5, Steam et l’Epic Games Store.",
    "lead": "La brume revient aujourd’hui. SILENT HILL: Townfall, nouvel épisode de la série de Konami, est disponible le 24 septembre 2026 sur PlayStation 5 et PC.",
    "intro": "Le jeu adopte une vue à la première personne et situe son histoire dans la ville côtière fictive de St. Amelia, en Écosse, au milieu des années 1990. Konami accompagne la sortie d’un trailer de lancement consacré aux créatures et aux lieux de cette nouvelle descente psychologique.",
    "h2": "UNE VILLE AU BORD DE L’EAU",
    "p1": "Townfall déplace l’horreur de Silent Hill vers une localité côtière isolée. La première personne doit renforcer la proximité avec les énigmes, les apparitions et les créatures qui attendent le joueur dans la brume.",
    "quote": "Townfall ne promet pas seulement un retour à Silent Hill : il installe la série dans une autre géographie de la peur.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE RETOUR DU PSYCHOLOGIQUE",
    "p2": "Konami présente cette aventure comme une expérience horrifique autonome, construite autour de la tension et de l’exploration. Le cadre écossais et le contexte des années 1990 distinguent Townfall des repères habituels de la franchise.",
    "p3": "La sortie est confirmée sur PS5, Steam et Epic Games Store. Le trailer officiel montre les menaces qui attendent dans St. Amelia, mais la force du jeu dépendra surtout de la qualité de ses énigmes, du rythme de sa narration et de sa capacité à maintenir l’inquiétude.",
    "p4": "Le prochain rendez-vous sera la réception de cette nouvelle approche en vue subjective. La brume de Townfall vous semble-t-elle capable de renouveler Silent Hill, ou attendez-vous une formule plus proche des épisodes précédents ?",
    "take": "À RETENIR",
    "takeText": "SILENT HILL: Townfall sort le 24 septembre 2026 sur PS5, Steam et Epic Games Store, dans une ville côtière écossaise en vue subjective.",
    "source": "D’après l’annonce officielle de Konami.",
    "sourceUrl": "https://www.konami.com/games/ca/en/topics/3265/",
    "sourceDetail": "Lire l’annonce officielle",
    "sourceName": "KONAMI",
    "video": "WARs8turgnM",
    "videoTitle": "SILENT HILL: Townfall | Launch Trailer",
    "thumbnail": "news-auto/silent-hill-townfall-sortie-24-septembre-2026-official.jpg",
    "officialThumbnailUrl": "https://i.ytimg.com/vi/WARs8turgnM/maxresdefault.jpg",
    "auto": true,
    "credit": "Miniature officielle : https://i.ytimg.com/vi/WARs8turgnM/maxresdefault.jpg",
    "sentiment": "positive"
  },
  "control-resonant-sortie-mondiale-24-septembre-2026": {
    "slug": "control-resonant-sortie-mondiale-24-septembre-2026",
    "date": "24.09.2026",
    "category": "PLAYSTATION · REMEDY",
    "image": "news-auto/control-resonant-sortie-mondiale-24-septembre-2026-official.jpg",
    "imageAlt": "CONTROL Resonant — miniature officielle du trailer de lancement",
    "cover": "CONTROL RESONANT",
    "title": "CONTROL RESONANT",
    "accent": "SORT ENFIN.",
    "dek": "Le nouvel épisode de Remedy Entertainment sort mondialement le 24 septembre 2026 sur PlayStation 5, Xbox Series X|S et PC.",
    "lead": "La Zone de Contrôle ouvre une nouvelle porte. CONTROL Resonant est disponible à partir du 24 septembre 2026 sur PlayStation 5, Xbox Series X|S et PC via Steam et l’Epic Games Store.",
    "intro": "Remedy présente cette suite comme une aventure d’action paranormale plus vaste, centrée sur Dylan Faden et une Manhattan altérée. Le studio confirme aussi une sortie sur GeForce NOW, en plus des versions consoles et PC.",
    "h2": "DYLAN REPREND LE SIGNAL",
    "p1": "CONTROL Resonant prolonge l’univers de Remedy avec Dylan Faden au centre du récit. Le jeu se déroule dans une version transformée de Manhattan, où les phénomènes paranormaux deviennent le terrain d’une nouvelle enquête.",
    "quote": "Le lancement ne cherche pas à refermer la Zone de Contrôle : il l’élargit à une autre ville et à un autre Faden.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "UNE SORTIE MULTI-SUPPORTS",
    "p2": "La disponibilité simultanée sur PS5, Xbox Series X|S et PC donne à cette suite une portée plus large que celle d’un lancement limité à une seule plateforme. Les joueurs PC peuvent passer par Steam ou l’Epic Games Store, tandis que le cloud gaming complète le dispositif.",
    "p3": "Le trailer de lancement met l’accent sur l’action, l’étrangeté visuelle et la menace qui traverse Manhattan. La réponse de Remedy sera désormais jugée sur la variété de ses environnements, la place donnée à Dylan et la capacité du jeu à renouveler les pouvoirs de la série.",
    "p4": "Le premier signal à surveiller sera la manière dont le jeu équilibre son récit paranormal et son exploration plus ambitieuse. CONTROL Resonant vous attire-t-il davantage pour son univers ou pour ses combats ? Dites-le dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "CONTROL Resonant sort le 24 septembre 2026 sur PS5, Xbox Series X|S et PC, avec Dylan Faden dans une Manhattan altérée.",
    "source": "D’après l’annonce officielle de Remedy Entertainment.",
    "sourceUrl": "https://www.remedygames.com/article/control-resonant-launches-worldwide-on-september-24",
    "sourceDetail": "Lire l’annonce officielle",
    "sourceName": "REMEDY ENTERTAINMENT",
    "video": "G1-lx73dP5g",
    "videoTitle": "CONTROL Resonant — Launch Trailer",
    "thumbnail": "news-auto/control-resonant-sortie-mondiale-24-septembre-2026-official.jpg",
    "officialThumbnailUrl": "https://i.ytimg.com/vi/G1-lx73dP5g/maxresdefault.jpg",
    "auto": true,
    "credit": "Miniature officielle : https://i.ytimg.com/vi/G1-lx73dP5g/maxresdefault.jpg",
    "sentiment": "positive"
  },
  "bethesda-promet-une-liberte-creative-a-obsidian-desormais-pa": {
    "slug": "bethesda-promet-une-liberte-creative-a-obsidian-desormais-pa",
    "date": "24.09.2026",
    "category": "XBOX · GAMEKULT",
    "image": "news-auto/bethesda-promet-une-liberte-creative-a-obsidian-desormais-pa-official.jpg",
    "imageAlt": "Bethesda promet une \"liberté créative\" à Obsidian, désormais partie intégrante de la famille — visuel éditorial Let’s Play",
    "cover": "XBOX",
    "title": "OBSIDIAN :",
    "accent": "LA LIBERTÉ PROMISE.",
    "dek": "Dans le cadre de la restructuration continue d'Xbox, Microsoft a licencié 268 employés supplémentaires cette semaine et réorganisé ses studios, plusieurs équipes se retrouvant intégrées à Bethesda et Activision.",
    "lead": "Et bien entendu, cette annonce ne manque pas d'alimenter les craintes de voir le talentueux studio réduit à une simple annexe de la production Fallout. Parmi elles, Obsidian, studio à l'origine d'Avowed, Outer Worlds et Fallout : New Vegas, rejoint donc désormais le giron de Bethesda.",
    "intro": "",
    "h2": "LES FAITS",
    "p1": "Ce faisant, Jill Braff, directrice des studios de jeux Bethesda/ZeniMax, a tenté de rassurer les employés dans un email consulté par Aftermath, afin de minimiser la portée de ce changement de statut. \" L'identité créative et les forces qui rendent Obsidian original resteront au cœur de leur studio et de leur travail \", a-t-elle écrit.",
    "quote": "",
    "quoteBy": "",
    "h2b": "LE CONTEXTE",
    "p2": "On rappellera que, selon des informations rapportées par Bloomberg en juillet dernier, la restructuration menée par Microsoft avait déjà contraint Obsidian à annuler plusieurs projets, dont une suite pour Avowed, pour se consacrer à un nouveau titre situé dans l'univers Fallout.",
    "p3": "",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Chaque nouveau communiqué officiel permettra d’en savoir plus. Quel point doit-on suivre en priorité selon vous ? Répondez dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "",
    "source": "D’après Gamekult, article consulté le 24.09.2026.",
    "sourceUrl": "https://www.gamekult.com/actualite/bethesda-promet-une-liberte-creative-a-obsidian-desormais-partie-integrante-de-la-famille-3050872180.html",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/bethesda-promet-une-liberte-creative-a-obsidian-desormais-pa-official.jpg",
    "officialThumbnailUrl": "https://cdn.gamekult.com/optim/images/news/30/3050872180/bethesda-promet-une-liberte-creative-a-obsidian-desormais-partie-integrante-de-la-famille-e7b43e7f__1920_1080__0-83-1920-703.jpg",
    "auto": true,
    "sourceName": "Gamekult"
  },
  "aniimo-cette-fonctionnalite-change-tout-compare-a-pokemon-et": {
    "slug": "aniimo-cette-fonctionnalite-change-tout-compare-a-pokemon-et",
    "date": "24.09.2026",
    "category": "PC · JEUXVIDEO.COM",
    "image": "news-auto/aniimo-cette-fonctionnalite-change-tout-compare-a-pokemon-et-official.png",
    "imageAlt": "Aniimo : cette fonctionnalité change tout comparé à Pokémon et Palworld. Le \"Twining\" expliqué — visuel éditorial Let’s Play",
    "cover": "STEAM",
    "title": "ANIIMO",
    "accent": "LE TWINING EXPLIQUÉ.",
    "dek": "Le 16 septembre 2026, Aniimo a franchi la barre des 101 000 joueurs simultanés sur Steam dès son lancement.",
    "lead": "Développé par Pawprint Studio et édité avec FunPlus, le titre entend renouveler le genre de la capture de créatures grâce au Twining, une mécanique d'incarnation directe permettant de contrôler physiquement chaque monstre.",
    "intro": "Le 16 septembre 2026 marque le déploiement officiel d'Aniimo sur PC et consoles, suivi d'une sortie mobile le 23 septembre. Selon Automaton Media, la production a rassemblé plus de 101 000 joueurs simultanés sur la plateforme Steam dans les trois heures suivant son ouverture.",
    "h2": "LES FAITS",
    "p1": "Derrière ce succès d'audience remarquable pour une nouvelle licence d'action-RPG en monde ouvert, le studio asiatique Pawprint Studio et son éditeur FunPlus proposent une refonte structurelle du monster-catching avec le «Twining ». Cette innovation de game design cherche à dépasser les schémas de commandement passifs pour réinventer la relation entre le joueur et ses créatures.",
    "quote": "",
    "quoteBy": "",
    "h2b": "LE CONTEXTE",
    "p2": "",
    "p3": "",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. La rédaction suivra les prochaines annonces pour compléter le dossier. Et vous, qu’avez-vous envie de voir en premier ? Dites-le dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "",
    "source": "D’après Jeuxvideo.com, article consulté le 24.09.2026.",
    "sourceUrl": "https://www.jeuxvideo.com/news/2105647/aniimo-cette-fonctionnalite-change-tout-compare-a-pokemon-et-palworld-le-twining-explique.htm",
    "sourceDetail": "Lire l’article source",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "sentiment": "positive",
    "thumbnail": "news-auto/aniimo-cette-fonctionnalite-change-tout-compare-a-pokemon-et-official.png",
    "officialThumbnailUrl": "https://image.jeuxvideo.com/medias-crop-1200-675/179009/1790089380-9100-card.jpg",
    "auto": true,
    "sourceName": "Jeuxvideo.com"
  },
  "shuffle-and-seek-sortie-steam-23-septembre-2026": {
    "slug": "shuffle-and-seek-sortie-steam-23-septembre-2026",
    "date": "23.09.2026",
    "category": "PC · GROOVY ZEBRA",
    "cover": "SHUFFLE AND SEEK",
    "title": "SHUFFLE AND SEEK",
    "accent": "RÈGLES MÉLANGÉES.",
    "imageAlt": "Shuffle and Seek — miniature officielle du trailer de lancement",
    "dek": "Le party game asymétrique de Groovy Zebra Studio sort sur Steam le 23 septembre 2026 avec une remise de lancement de 20 %.",
    "lead": "Un objet déplacé, une pièce qui change, et la partie bascule. Shuffle and Seek arrive sur Steam le 23 septembre avec une formule asymétrique qui oppose les joueurs chargés de modifier le décor à ceux qui doivent repérer les différences.",
    "intro": "Le communiqué de lancement présente un jeu de cache-cache où les Shufflers manipulent les objets tandis que les Seekers observent l’environnement pour identifier ce qui n’est plus à sa place. La promesse tient dans cette tension entre discrétion et lecture attentive.",
    "h2": "LE DÉCOR DEVIENT UN MENSONGE",
    "p1": "Shuffle and Seek transforme l’espace de jeu en terrain d’observation. Les Shufflers doivent déplacer ou modifier des éléments sans se faire repérer, alors que les Seekers cherchent les anomalies avant la fin du temps imparti.",
    "quote": "Ici, le décor n’est pas le terrain de jeu : c’est le coup de bluff.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "UN PARTY GAME À LIRE À PLUSIEURS",
    "p2": "La formule repose moins sur la vitesse que sur la mémoire et la communication. Chaque manche crée une petite enquête, avec des joueurs qui connaissent le changement et d’autres qui doivent faire confiance à leur regard.",
    "p3": "La sortie s’accompagne d’une remise de lancement de 20 %, annoncée par Groovy Zebra Studio. Cette offre ne dit rien de la longévité du jeu, mais elle peut faciliter l’entrée d’un premier groupe de joueurs nécessaire à ce type d’expérience.",
    "p4": "Le vrai test sera la variété des situations après quelques parties. Est-ce le genre de jeu que vous lanceriez entre amis pour traquer le moindre détail, ou préférez-vous les party games plus directs ?",
    "take": "À RETENIR",
    "takeText": "Shuffle and Seek sort sur Steam le 23 septembre 2026, avec une formule asymétrique fondée sur les objets déplacés et l’observation.",
    "source": "D’après le communiqué de lancement Groovy Zebra Studio publié via GamesPress.",
    "sourceUrl": "https://www.gamespress.com/Party-Game-Shuffle-and-Seek-Launches-on-Steam-September-23",
    "sourceDetail": "Lire le communiqué",
    "sourceName": "GROOVY ZEBRA STUDIO",
    "video": "ejJ6V_qE1Cw",
    "videoTitle": "Shuffle and Seek — Launch Date Announcement Official Trailer",
    "thumbnail": "news-auto/shuffle-and-seek-sortie-steam-23-septembre-2026-official.jpg",
    "officialThumbnailUrl": "https://i.ytimg.com/vi/ejJ6V_qE1Cw/maxresdefault.jpg",
    "image": "news-auto/shuffle-and-seek-sortie-steam-23-septembre-2026-official.jpg",
    "auto": true,
    "credit": "Miniature officielle : https://i.ytimg.com/vi/ejJ6V_qE1Cw/maxresdefault.jpg"
  },
  "lawn-mowing-simulator-2-sortie-23-septembre-2026": {
    "slug": "lawn-mowing-simulator-2-sortie-23-septembre-2026",
    "date": "23.09.2026",
    "category": "SIMULATION · SKYHOOK GAMES",
    "cover": "LAWN MOWING 2",
    "title": "LAWN MOWING 2",
    "accent": "REPASSE.",
    "imageAlt": "Lawn Mowing Simulator 2 — miniature officielle du trailer de lancement",
    "dek": "Lawn Mowing Simulator 2 sort le 23 septembre 2026 sur PC, PlayStation 5 et Xbox Series X|S avec un nouveau quartier général à gérer.",
    "lead": "La pelouse change de génération. Lawn Mowing Simulator 2 arrive le 23 septembre sur PC, PlayStation 5 et Xbox Series X|S, avec une technologie de terrain annoncée comme plus réaliste et une entreprise à développer.",
    "intro": "Skyhook Games accompagne la sortie de nouvelles tondeuses sous licence Kubota, SCAG et STIGA, mais aussi d’un QG entièrement explorable. La boucle ne s’arrête donc plus au contrat : il faut organiser son activité, sa flotte et les outils qui l’accompagnent.",
    "h2": "UNE PELOUSE PLUS AMBITIEUSE",
    "p1": "La suite veut rendre la simulation plus concrète avec une technologie de pelouse améliorée, des machines sous licence et des environnements qui demandent davantage qu’un simple passage en ligne droite. Le travail est toujours calme, mais le cadre cherche à gagner en précision.",
    "quote": "Le plaisir vient de la ligne parfaite, mais la suite veut aussi donner une histoire à la pelouse.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "GÉRER AVANT DE TONDRE",
    "p2": "Le nouveau QG sert de centre de gestion pour l’entreprise et la flotte. Des souffleurs et des contrats de ramassage de feuilles complètent les activités, ce qui élargit la routine au-delà de la tonte elle-même.",
    "p3": "La sortie simultanée sur PC, PS5 et Xbox Series X|S place cette suite dans une logique de confort partagé. Le trailer officiel met en avant les machines et les environnements ; la profondeur de la progression devra se juger manette en main.",
    "p4": "Le signal à surveiller sera l’équilibre entre détente et répétition. Vous cherchez ce type de jeu pour vous relaxer après une grosse session, ou la gestion d’une entreprise vous semble-t-elle trop sérieuse pour une tondeuse ?",
    "take": "À RETENIR",
    "takeText": "Lawn Mowing Simulator 2 sort le 23 septembre 2026 sur PC, PS5 et Xbox Series X|S avec un QG explorable et de nouvelles machines.",
    "source": "D’après le communiqué Skyhook Games publié via GamesPress le 21.09.2026.",
    "sourceUrl": "https://www.gamespress.com/en-GB/Lawn-Mowing-Simulator-2-Launch-Trailer-Revealed-Ahead-of-September-23r",
    "sourceDetail": "Lire le communiqué",
    "sourceName": "SKYHOOK GAMES",
    "video": "Bsquwuiwz0w",
    "videoTitle": "Lawn Mowing Simulator 2 | Launch Trailer",
    "thumbnail": "news-auto/lawn-mowing-simulator-2-sortie-23-septembre-2026-official.jpg",
    "officialThumbnailUrl": "https://i.ytimg.com/vi/Bsquwuiwz0w/maxresdefault.jpg",
    "image": "news-auto/lawn-mowing-simulator-2-sortie-23-septembre-2026-official.jpg",
    "auto": true,
    "credit": "Miniature officielle : https://i.ytimg.com/vi/Bsquwuiwz0w/maxresdefault.jpg"
  },
  "aniimo-lancement-mondial-mobile-23-septembre-2026": {
    "slug": "aniimo-lancement-mondial-mobile-23-septembre-2026",
    "date": "23.09.2026",
    "category": "MOBILE · ANIIMO",
    "cover": "ANIIMO",
    "title": "ANIIMO",
    "accent": "OUVRE AU MONDE.",
    "imageAlt": "Aniimo — visuel officiel de l’annonce de lancement mobile",
    "dek": "Le monde d’Aniimo s’ouvre d’abord sur mobile. Le communiqué officiel annonce un lancement régional le 23 septembre 2026, après un pré-téléchargement déjà disponible sur Google Play et l’App Store.",
    "lead": "Les horaires varient selon les territoires : l’Europe est annoncée à 02:00 UTC, tandis que les Amériques et l’APAC disposent de créneaux dédiés. Le jeu demande environ 18 Go d’espace libre et promet une progression partagée sur un même serveur.",
    "intro": "Aniimo ne se contente pas d’afficher une date unique. Le communiqué détaille plusieurs horaires régionaux afin d’accompagner l’ouverture progressive des serveurs, avec un pré-téléchargement lancé dès le 22 septembre à 00:00 UTC+8.",
    "h2": "UN LANCEMENT PAR VAGUES",
    "p1": "L’élément le plus intéressant concerne la continuité entre les supports. Aniimo indique que la progression est partagée entre PC, consoles et mobile sur un même serveur, une promesse qui devra maintenant résister aux premières heures de connexion. La sortie mobile ne suffit donc pas à résumer le rendez-vous.",
    "quote": "Elle sert aussi de test grandeur nature pour une expérience pensée autour de plusieurs écrans et de communautés qui ne joueront pas nécessairement avec le même type de commandes.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CROSS-PLATEFORME EN LIGNE DE MIRE",
    "p2": "Le lancement mobile est une porte d’entrée, pas un monde séparé : la progression doit suivre le joueur.",
    "p3": "",
    "p4": "Cet article a été préparé automatiquement par la rédaction Let’s Play à partir de la source citée ci-dessous. Les prochaines communications officielles préciseront la suite. De votre côté, quel élément mérite d’être surveillé en premier ? Dites-le dans les commentaires.",
    "take": "À RETENIR",
    "takeText": "",
    "source": "D’après le communiqué officiel Aniimo publié le 22.09.2026.",
    "sourceUrl": "https://www.aniimo.com/m/newslist/detail/100137",
    "sourceDetail": "Lire l’annonce officielle",
    "sourceName": "ANIIMO OFFICIAL",
    "video": "XHPS09hP7m4",
    "videoTitle": "Aniimo | Gameplay Showcase",
    "thumbnail": "news-auto/aniimo-lancement-mondial-mobile-23-septembre-2026-official.png",
    "officialThumbnailUrl": "https://kg-web-cdn.akamaized.net/master/official-website/worldx_office_frontend/images/ogImage.png",
    "image": "news-auto/aniimo-lancement-mondial-mobile-23-septembre-2026-official.png",
    "auto": true,
    "credit": "Miniature officielle : https://kg-web-cdn.akamaized.net/master/official-website/worldx_office_frontend/images/ogImage.png"
  },
  "xbox-consolidation-studios-licenciements-rapport": {
    "slug": "xbox-consolidation-studios-licenciements-rapport",
    "date": "22.09.2026",
    "category": "XBOX · INDUSTRIE",
    "image": "news-auto/xbox-consolidation-studios-licenciements-rapport-official.webp",
    "imageAlt": "Xbox — visuel éditorial Let’s Play sur le rapport de réorganisation",
    "cover": "XBOX",
    "title": "XBOX :",
    "accent": "UNE VAGUE DE COUPES.",
    "dek": "Selon VGC, Microsoft préparerait une réduction majeure des effectifs et une consolidation de plusieurs studios Xbox. L’information n’est pas confirmée par Microsoft.",
    "lead": "Le conditionnel est ici essentiel. VGC rapporte le 22 septembre 2026, en citant The Information, qu’une nouvelle vague de licenciements pourrait toucher Xbox Game Studios, Bethesda, Activision et Blizzard.",
    "intro": "Le rapport évoque des centaines de postes et de possibles fusions ou transferts entre entités. À ce stade, Microsoft n’a pas confirmé publiquement la forme exacte de la réorganisation : il s’agit donc d’une information de presse, pas d’une annonce officielle de Xbox.",
    "h2": "LE CONDITIONNEL AVANT LE BUZZ",
    "p1": "Le dossier arrive après une première vague annoncée en juillet. VGC rappelle alors un plan évoquant 1 600 suppressions de postes, avec 1 600 autres prévues d’ici la fin de l’exercice de Microsoft. Les chiffres et le périmètre rapportés aujourd’hui doivent encore être distingués de toute décision officiellement publiée.",
    "quote": "Quand une restructuration n’est pas encore confirmée, le premier devoir d’une actu est de garder le conditionnel.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "PLUSIEURS BRANCHES DANS LA MÊME ZONE",
    "p2": "Xbox Game Studios, Bethesda, Activision et Blizzard sont cités dans le rapport, ce qui dessinerait une opération plus large qu’un simple ajustement d’équipe. Une consolidation peut prendre plusieurs formes : fusion de structures, déplacement de fonctions ou fermeture de projets.",
    "p3": "La prudence est d’autant plus importante que les annonces de licenciements ont un impact humain direct. Tant que Microsoft n’a pas communiqué, impossible de confirmer le nombre de personnes concernées, les studios précis ou le calendrier d’application.",
    "p4": "Let’s Play suivra la confirmation officielle avant de transformer ce rapport en fait établi. Pour l’instant, l’information est suffisamment importante pour être signalée, mais pas pour être présentée comme une décision actée.",
    "take": "À RETENIR",
    "takeText": "VGC rapporte une nouvelle vague de licenciements et de consolidations chez Xbox, mais Microsoft n’a pas confirmé ces informations.",
    "source": "D’après VGC, publié le 22.09.2026, citant The Information. Information non confirmée par Microsoft au moment de la publication.",
    "sourceUrl": "https://www.videogameschronicle.com/news/xbox-will-reportedly-consolidate-several-studios-in-new-major-wave-of-layoffs/",
    "sourceDetail": "Lire le rapport VGC",
    "sourceName": "VGC",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "auto": true,
    "thumbnail": "news-auto/xbox-consolidation-studios-licenciements-rapport-official.webp",
    "officialThumbnailUrl": "https://files.manuscdn.com/search-media/310519663645820794/DkH0qyi7rbv66dQnKZOL3K/q6ZUZ8sDnFfvj9HKrgMPhf.jpg",
    "sentiment": "negative"
  },
  "tencent-ecs-jeux-asiatiques-esport-2026": {
    "slug": "tencent-ecs-jeux-asiatiques-esport-2026",
    "date": "22.09.2026",
    "category": "E-SPORT · TENCENT",
    "image": "news-auto/tencent-ecs-jeux-asiatiques-esport-2026-official.png",
    "imageAlt": "Tencent Esports Competition Solution — visuel éditorial Let’s Play",
    "cover": "TENCENT ECS",
    "title": "TENCENT",
    "accent": "DÉPLOIE SON ECS.",
    "dek": "Tencent annonce le déploiement de sa solution ECS pour encadrer les 11 épreuves d’esport des Jeux asiatiques 2026.",
    "lead": "L’esport entre dans une nouvelle phase de standardisation. Dans un communiqué daté du 22 septembre 2026, Tencent annonce que sa Tencent Esports Competition Solution accompagnera les 11 épreuves prévues aux Jeux asiatiques, au Japon, du 22 septembre au 2 octobre.",
    "intro": "La solution veut couvrir toute la chaîne de compétition : contrôle des périphériques et de l’environnement avant le match, surveillance en temps réel de plus de 30 indicateurs, puis réexamen et archivage des données après chaque rencontre. Tencent présente l’ECS comme une couche technique commune à plusieurs jeux et éditeurs.",
    "h2": "UN ARBITRE TECHNIQUE",
    "p1": "L’intérêt de l’annonce n’est pas un nouveau jeu, mais la promesse d’un cadre plus homogène. En traitant le matériel, l’environnement et les données de match dans un même dispositif, Tencent cherche à réduire les zones grises qui compliquent les compétitions multi-titres.",
    "quote": "À ce niveau, la technologie ne remplace pas l’arbitre : elle donne enfin une trace exploitable à chaque décision.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "217 MATCHS COMME PREUVE DE TERRAIN",
    "p2": "Tencent affirme que son système avait déjà assuré le support technique de 217 matchs lors des Jeux asiatiques de Hangzhou, sans incident technique selon son bilan officiel. Cette expérience sert de précédent à un déploiement plus large dans l’édition 2026.",
    "p3": "Le dispositif devra maintenant composer avec onze épreuves et plusieurs catégories de jeux. La réussite se mesurera moins à la promesse marketing qu’à la capacité du système à rester lisible pour les joueurs, les arbitres et le public.",
    "p4": "Cette annonce donne surtout un aperçu de l’infrastructure qui se construit derrière les grandes compétitions. L’esport devient un événement sportif ; ses outils de contrôle cherchent désormais à afficher le même niveau de rigueur.",
    "take": "À RETENIR",
    "takeText": "Tencent déploie son ECS pour les 11 épreuves d’esport des Jeux asiatiques 2026, avec contrôle pré-match, surveillance en direct et archivage.",
    "source": "D’après le communiqué officiel Tencent publié le 22.09.2026.",
    "sourceUrl": "https://www.tencent.com/zh-cn/tencent-esports-competition-solution-to-support-esports-at-the-20th-asian-games/",
    "sourceDetail": "Lire le communiqué officiel",
    "sourceName": "TENCENT",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "auto": true,
    "thumbnail": "news-auto/tencent-ecs-jeux-asiatiques-esport-2026-official.png",
    "officialThumbnailUrl": "https://www.tencent.com/wp-content/uploads/2026/09/OCA.png",
    "sentiment": "positive"
  },
  "dune-awakening-sortie-consoles-mise-a-jour-15": {
    "slug": "dune-awakening-sortie-consoles-mise-a-jour-15",
    "date": "22.09.2026",
    "category": "SORTIES · FUNCOM",
    "image": "news-auto/dune-awakening-sortie-consoles-mise-a-jour-15-official.jpg",
    "imageAlt": "Dune: Awakening — visuel éditorial Let’s Play sur la sortie consoles et la mise à jour 1.5",
    "cover": "DUNE: AWAKENING",
    "title": "DUNE: AWAKENING",
    "accent": "SUR PS5, XBOX.",
    "dek": "Dune: Awakening arrive sur consoles avec sa mise à jour 1.5, un mode solo complet et la conclusion du Livre 1.",
    "lead": "Arrakis ouvre enfin ses portes sur consoles. Le 22 septembre 2026, Dune: Awakening lance sa version complète sur PlayStation 5, Xbox Series X|S et Microsoft Store, avec une mise à jour 1.5 qui change aussi la manière de jouer en solo.",
    "intro": "Funcom accompagne cette sortie d’un mode solo complet, de trois niveaux de difficulté et d’options de personnalisation plus fines. La mise à jour ajoute également Great Convention Part III et le chapitre final du Livre 1, tandis que le Game Pass, le Play Anywhere et le cloud gaming sont annoncés côté Xbox.",
    "h2": "ARRAKIS S’OUVRE À TOUS",
    "p1": "La sortie console complète intervient après un accès anticipé réservé aux précommandes Deluxe et Ultimate depuis le 17 septembre. Les éditions physiques rejoignent donc le lancement du 22 septembre, avec un parcours désormais pensé pour celles et ceux qui veulent découvrir l’univers de Dune sans passer par le PC.",
    "quote": "Le vrai signal du jour, ce n’est pas seulement la console : c’est le solo qui devient une porte d’entrée à part entière.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE LIVRE 1 FERME SON PREMIER CHAPITRE",
    "p2": "Avec Great Convention Part III et son chapitre final, la mise à jour 1.5 donne aussi une conclusion au premier arc narratif. Funcom ne présente donc pas cette version comme un simple portage : le lancement sert de nouveau point d’entrée et de rendez-vous pour les joueurs déjà présents.",
    "p3": "Le mode solo propose trois difficultés prédéfinies, mais aussi des réglages plus précis pour adapter l’expérience. Cette souplesse compte dans un jeu qui mêle survie, exploration et progression persistante dans un monde partagé.",
    "p4": "Pour Let’s Play, le rendez-vous est clair : la version console doit maintenant prouver que l’échelle d’Arrakis fonctionne aussi loin du clavier-souris. Le trailer officiel pose l’ambiance ; le verdict, lui, viendra des premières heures manette en main.",
    "take": "À RETENIR",
    "takeText": "Dune: Awakening sort sur consoles le 22 septembre 2026 avec la mise à jour 1.5, un mode solo complet et la fin du Livre 1.",
    "source": "D’après l’annonce officielle de Funcom publiée le 22.09.2026.",
    "sourceUrl": "https://duneawakening.com/news/announcement/the-new-dune-awakening-is-here/",
    "sourceDetail": "Lire l’annonce officielle",
    "sourceName": "FUNCOM",
    "video": "pn7OQJ9EbR0",
    "videoTitle": "Dune: Awakening — Console and Single-Player Launch Trailer",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "auto": true,
    "thumbnail": "news-auto/dune-awakening-sortie-consoles-mise-a-jour-15-official.jpg",
    "officialThumbnailUrl": "https://duneawakening.com/wp-content/uploads/Steam-News-Website-Banners_Website_16x9.jpg",
    "sentiment": "positive"
  },
};
