// ⚙️ FICHIER GÉNÉRÉ par scripts/news-bot/fetch-news.mjs — ne pas éditer à la main.
// Dernière génération : 2026-09-23T12:50:00.000Z — 6 article(s).
// Ce module alimente la page Actus et les routes /news/<slug> du site.
export const autoStories = {
  "shuffle-and-seek-sortie-steam-23-septembre-2026": {
    "slug": "shuffle-and-seek-sortie-steam-23-septembre-2026",
    "date": "23.09.2026",
    "category": "PC · GROOVY ZEBRA",
    "cover": "SHUFFLE AND SEEK",
    "title": "SHUFFLE AND SEEK",
    "accent": "CHANGE LES RÈGLES DU CACHE-CACHE.",
    "imageAlt": "Shuffle and Seek — miniature officielle du trailer de lancement",
    "dek": "Le party game asymétrique de Groovy Zebra Studio sort sur Steam le 23 septembre 2026 avec une remise de lancement de 20 %.",
    "lead": "Un objet déplacé, une pièce qui change, et la partie bascule. Shuffle and Seek arrive sur Steam le 23 septembre avec une formule asymétrique qui oppose les joueurs chargés de modifier le décor à ceux qui doivent repérer les différences.",
    "intro": "Le communiqué de lancement présente un jeu de cache-cache où les Shufflers manipulent les objets tandis que les Seekers observent l’environnement pour identifier ce qui n’est plus à sa place. La promesse tient dans cette tension entre discrétion et lecture attentive.",
    "h2": "LE DÉCOR DEVIENT UN MENSONGE",
    "p1": "Shuffle and Seek transforme l’espace de jeu en terrain d’observation. Les Shufflers doivent déplacer ou modifier des éléments sans se faire repérer, alors que les Seekers cherchent les anomalies avant la fin du temps imparti.",
    "quote": "Ici, le décor n’est pas le terrain de jeu : c’est le coup de bluff.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "UN PARTY GAME À LIRE À PLUSIEURS",
    "p2": "La formule repose moins sur la vitesse que sur la mémoire et la communication. Chaque manche crée une petite enquête, avec des joueurs qui connaissent le changement et d’autres qui doivent faire confiance à leur regard.",
    "p3": "La sortie s’accompagne d’une remise de lancement de 20 %, annoncée par Groovy Zebra Studio. Cette offre ne dit rien de la longévité du jeu, mais elle peut faciliter l’entrée d’un premier groupe de joueurs nécessaire à ce type d’expérience.",
    "p4": "Le vrai test sera la variété des situations après quelques parties. Est-ce le genre de jeu que vous lanceriez entre amis pour traquer le moindre détail, ou préférez-vous les party games plus directs ?",
    "take": "À RETENIR",
    "takeText": "Shuffle and Seek sort sur Steam le 23 septembre 2026, avec une formule asymétrique fondée sur les objets déplacés et l’observation.",
    "source": "D’après le communiqué de lancement Groovy Zebra Studio publié via GamesPress.",
    "sourceUrl": "https://www.gamespress.com/Party-Game-Shuffle-and-Seek-Launches-on-Steam-September-23",
    "sourceDetail": "Lire le communiqué",
    "sourceName": "GROOVY ZEBRA STUDIO",
    "video": "ejJ6V_qE1Cw",
    "videoTitle": "Shuffle and Seek — Launch Date Announcement Official Trailer",
    "thumbnail": "news-auto/shuffle-and-seek-sortie-steam-23-septembre-2026-official.jpg",
    "officialThumbnailUrl": "https://i.ytimg.com/vi/ejJ6V_qE1Cw/maxresdefault.jpg",
    "image": "news-auto/shuffle-and-seek-sortie-steam-23-septembre-2026.svg",
    "auto": true,
    "credit": "Miniature officielle : https://i.ytimg.com/vi/ejJ6V_qE1Cw/maxresdefault.jpg"
  },
  "lawn-mowing-simulator-2-sortie-23-septembre-2026": {
    "slug": "lawn-mowing-simulator-2-sortie-23-septembre-2026",
    "date": "23.09.2026",
    "category": "SIMULATION · SKYHOOK GAMES",
    "cover": "LAWN MOWING 2",
    "title": "LAWN MOWING SIMULATOR 2",
    "accent": "REPASSE LA TONDEUSE.",
    "imageAlt": "Lawn Mowing Simulator 2 — miniature officielle du trailer de lancement",
    "dek": "Lawn Mowing Simulator 2 sort le 23 septembre 2026 sur PC, PlayStation 5 et Xbox Series X|S avec un nouveau quartier général à gérer.",
    "lead": "La pelouse change de génération. Lawn Mowing Simulator 2 arrive le 23 septembre sur PC, PlayStation 5 et Xbox Series X|S, avec une technologie de terrain annoncée comme plus réaliste et une entreprise à développer.",
    "intro": "Skyhook Games accompagne la sortie de nouvelles tondeuses sous licence Kubota, SCAG et STIGA, mais aussi d’un QG entièrement explorable. La boucle ne s’arrête donc plus au contrat : il faut organiser son activité, sa flotte et les outils qui l’accompagnent.",
    "h2": "UNE PELOUSE PLUS AMBITIEUSE",
    "p1": "La suite veut rendre la simulation plus concrète avec une technologie de pelouse améliorée, des machines sous licence et des environnements qui demandent davantage qu’un simple passage en ligne droite. Le travail est toujours calme, mais le cadre cherche à gagner en précision.",
    "quote": "Le plaisir vient de la ligne parfaite, mais la suite veut aussi donner une histoire à la pelouse.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "GÉRER AVANT DE TONDRE",
    "p2": "Le nouveau QG sert de centre de gestion pour l’entreprise et la flotte. Des souffleurs et des contrats de ramassage de feuilles complètent les activités, ce qui élargit la routine au-delà de la tonte elle-même.",
    "p3": "La sortie simultanée sur PC, PS5 et Xbox Series X|S place cette suite dans une logique de confort partagé. Le trailer officiel met en avant les machines et les environnements ; la profondeur de la progression devra se juger manette en main.",
    "p4": "Le signal à surveiller sera l’équilibre entre détente et répétition. Vous cherchez ce type de jeu pour vous relaxer après une grosse session, ou la gestion d’une entreprise vous semble-t-elle trop sérieuse pour une tondeuse ?",
    "take": "À RETENIR",
    "takeText": "Lawn Mowing Simulator 2 sort le 23 septembre 2026 sur PC, PS5 et Xbox Series X|S avec un QG explorable et de nouvelles machines.",
    "source": "D’après le communiqué Skyhook Games publié via GamesPress le 21.09.2026.",
    "sourceUrl": "https://www.gamespress.com/en-GB/Lawn-Mowing-Simulator-2-Launch-Trailer-Revealed-Ahead-of-September-23r",
    "sourceDetail": "Lire le communiqué",
    "sourceName": "SKYHOOK GAMES",
    "video": "Bsquwuiwz0w",
    "videoTitle": "Lawn Mowing Simulator 2 | Launch Trailer",
    "thumbnail": "news-auto/lawn-mowing-simulator-2-sortie-23-septembre-2026-official.jpg",
    "officialThumbnailUrl": "https://i.ytimg.com/vi/Bsquwuiwz0w/maxresdefault.jpg",
    "image": "news-auto/lawn-mowing-simulator-2-sortie-23-septembre-2026.svg",
    "auto": true,
    "credit": "Miniature officielle : https://i.ytimg.com/vi/Bsquwuiwz0w/maxresdefault.jpg"
  },
  "aniimo-lancement-mondial-mobile-23-septembre-2026": {
    "slug": "aniimo-lancement-mondial-mobile-23-septembre-2026",
    "date": "23.09.2026",
    "category": "MOBILE · ANIIMO",
    "cover": "ANIIMO",
    "title": "ANIIMO OUVRE",
    "accent": "SES PORTES AU MONDE.",
    "imageAlt": "Aniimo — visuel officiel de l’annonce de lancement mobile",
    "dek": "Aniimo lance sa version mobile le 23 septembre 2026 avec une progression partagée entre PC, consoles et mobile.",
    "lead": "Le monde d’Aniimo s’ouvre d’abord sur mobile. Le communiqué officiel annonce un lancement régional le 23 septembre 2026, après un pré-téléchargement déjà disponible sur Google Play et l’App Store.",
    "intro": "Les horaires varient selon les territoires : l’Europe est annoncée à 02:00 UTC, tandis que les Amériques et l’APAC disposent de créneaux dédiés. Le jeu demande environ 18 Go d’espace libre et promet une progression partagée sur un même serveur.",
    "h2": "UN LANCEMENT PAR VAGUES",
    "p1": "Aniimo ne se contente pas d’afficher une date unique. Le communiqué détaille plusieurs horaires régionaux afin d’accompagner l’ouverture progressive des serveurs, avec un pré-téléchargement lancé dès le 22 septembre à 00:00 UTC+8.",
    "quote": "Le lancement mobile est une porte d’entrée, pas un monde séparé : la progression doit suivre le joueur.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE CROSS-PLATEFORME EN LIGNE DE MIRE",
    "p2": "L’élément le plus intéressant concerne la continuité entre les supports. Aniimo indique que la progression est partagée entre PC, consoles et mobile sur un même serveur, une promesse qui devra maintenant résister aux premières heures de connexion.",
    "p3": "La sortie mobile ne suffit donc pas à résumer le rendez-vous. Elle sert aussi de test grandeur nature pour une expérience pensée autour de plusieurs écrans et de communautés qui ne joueront pas nécessairement avec le même type de commandes.",
    "p4": "Le prochain signal à surveiller sera la stabilité du lancement et la qualité du passage d’un support à l’autre. Et vous, l’accès mobile vous donne-t-il envie de découvrir Aniimo, ou attendez-vous encore la version PC et consoles ?",
    "take": "À RETENIR",
    "takeText": "Aniimo lance sa version mobile le 23 septembre 2026, avec une progression partagée entre PC, consoles et mobile.",
    "source": "D’après le communiqué officiel Aniimo publié le 22.09.2026.",
    "sourceUrl": "https://www.aniimo.com/m/newslist/detail/100137",
    "sourceDetail": "Lire l’annonce officielle",
    "sourceName": "ANIIMO OFFICIAL",
    "video": "XHPS09hP7m4",
    "videoTitle": "Aniimo | Gameplay Showcase",
    "thumbnail": "news-auto/aniimo-lancement-mondial-mobile-23-septembre-2026-official.png",
    "officialThumbnailUrl": "https://kg-web-cdn.akamaized.net/master/official-website/worldx_office_frontend/images/ogImage.png",
    "image": "news-auto/aniimo-lancement-mondial-mobile-23-septembre-2026.svg",
    "auto": true,
    "credit": "Miniature officielle : https://kg-web-cdn.akamaized.net/master/official-website/worldx_office_frontend/images/ogImage.png"
  },
  "xbox-consolidation-studios-licenciements-rapport": {
    "slug": "xbox-consolidation-studios-licenciements-rapport",
    "date": "22.09.2026",
    "category": "XBOX · INDUSTRIE",
    "image": "news-auto/xbox-consolidation-studios-licenciements-rapport.svg",
    "imageAlt": "Xbox — visuel éditorial Let’s Play sur le rapport de réorganisation",
    "cover": "XBOX",
    "title": "XBOX PRÉPARERAIT",
    "accent": "UNE NOUVELLE VAGUE DE CONSOLIDATION.",
    "dek": "Selon VGC, Microsoft préparerait une réduction majeure des effectifs et une consolidation de plusieurs studios Xbox. L’information n’est pas confirmée par Microsoft.",
    "lead": "Le conditionnel est ici essentiel. VGC rapporte le 22 septembre 2026, en citant The Information, qu’une nouvelle vague de licenciements pourrait toucher Xbox Game Studios, Bethesda, Activision et Blizzard.",
    "intro": "Le rapport évoque des centaines de postes et de possibles fusions ou transferts entre entités. À ce stade, Microsoft n’a pas confirmé publiquement la forme exacte de la réorganisation : il s’agit donc d’une information de presse, pas d’une annonce officielle de Xbox.",
    "h2": "LE CONDITIONNEL AVANT LE BUZZ",
    "p1": "Le dossier arrive après une première vague annoncée en juillet. VGC rappelle alors un plan évoquant 1 600 suppressions de postes, avec 1 600 autres prévues d’ici la fin de l’exercice de Microsoft. Les chiffres et le périmètre rapportés aujourd’hui doivent encore être distingués de toute décision officiellement publiée.",
    "quote": "Quand une restructuration n’est pas encore confirmée, le premier devoir d’une actu est de garder le conditionnel.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "PLUSIEURS BRANCHES DANS LA MÊME ZONE",
    "p2": "Xbox Game Studios, Bethesda, Activision et Blizzard sont cités dans le rapport, ce qui dessinerait une opération plus large qu’un simple ajustement d’équipe. Une consolidation peut prendre plusieurs formes : fusion de structures, déplacement de fonctions ou fermeture de projets.",
    "p3": "La prudence est d’autant plus importante que les annonces de licenciements ont un impact humain direct. Tant que Microsoft n’a pas communiqué, impossible de confirmer le nombre de personnes concernées, les studios précis ou le calendrier d’application.",
    "p4": "Let’s Play suivra la confirmation officielle avant de transformer ce rapport en fait établi. Pour l’instant, l’information est suffisamment importante pour être signalée, mais pas pour être présentée comme une décision actée.",
    "take": "À RETENIR",
    "takeText": "VGC rapporte une nouvelle vague de licenciements et de consolidations chez Xbox, mais Microsoft n’a pas confirmé ces informations.",
    "source": "D’après VGC, publié le 22.09.2026, citant The Information. Information non confirmée par Microsoft au moment de la publication.",
    "sourceUrl": "https://www.videogameschronicle.com/news/xbox-will-reportedly-consolidate-several-studios-in-new-major-wave-of-layoffs/",
    "sourceDetail": "Lire le rapport VGC",
    "sourceName": "VGC",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "auto": true,
    "thumbnail": "news-auto/xbox-consolidation-studios-licenciements-rapport-official.webp",
    "officialThumbnailUrl": "https://files.manuscdn.com/search-media/310519663645820794/DkH0qyi7rbv66dQnKZOL3K/q6ZUZ8sDnFfvj9HKrgMPhf.jpg",
    "sentiment": "negative"
  },
  "tencent-ecs-jeux-asiatiques-esport-2026": {
    "slug": "tencent-ecs-jeux-asiatiques-esport-2026",
    "date": "22.09.2026",
    "category": "E-SPORT · TENCENT",
    "image": "news-auto/tencent-ecs-jeux-asiatiques-esport-2026.svg",
    "imageAlt": "Tencent Esports Competition Solution — visuel éditorial Let’s Play",
    "cover": "TENCENT ECS",
    "title": "TENCENT INSTALLE",
    "accent": "SON ECS AUX JEUX ASIATIQUES.",
    "dek": "Tencent annonce le déploiement de sa solution ECS pour encadrer les 11 épreuves d’esport des Jeux asiatiques 2026.",
    "lead": "L’esport entre dans une nouvelle phase de standardisation. Dans un communiqué daté du 22 septembre 2026, Tencent annonce que sa Tencent Esports Competition Solution accompagnera les 11 épreuves prévues aux Jeux asiatiques, au Japon, du 22 septembre au 2 octobre.",
    "intro": "La solution veut couvrir toute la chaîne de compétition : contrôle des périphériques et de l’environnement avant le match, surveillance en temps réel de plus de 30 indicateurs, puis réexamen et archivage des données après chaque rencontre. Tencent présente l’ECS comme une couche technique commune à plusieurs jeux et éditeurs.",
    "h2": "UN ARBITRE TECHNIQUE",
    "p1": "L’intérêt de l’annonce n’est pas un nouveau jeu, mais la promesse d’un cadre plus homogène. En traitant le matériel, l’environnement et les données de match dans un même dispositif, Tencent cherche à réduire les zones grises qui compliquent les compétitions multi-titres.",
    "quote": "À ce niveau, la technologie ne remplace pas l’arbitre : elle donne enfin une trace exploitable à chaque décision.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "217 MATCHS COMME PREUVE DE TERRAIN",
    "p2": "Tencent affirme que son système avait déjà assuré le support technique de 217 matchs lors des Jeux asiatiques de Hangzhou, sans incident technique selon son bilan officiel. Cette expérience sert de précédent à un déploiement plus large dans l’édition 2026.",
    "p3": "Le dispositif devra maintenant composer avec onze épreuves et plusieurs catégories de jeux. La réussite se mesurera moins à la promesse marketing qu’à la capacité du système à rester lisible pour les joueurs, les arbitres et le public.",
    "p4": "Cette annonce donne surtout un aperçu de l’infrastructure qui se construit derrière les grandes compétitions. L’esport devient un événement sportif ; ses outils de contrôle cherchent désormais à afficher le même niveau de rigueur.",
    "take": "À RETENIR",
    "takeText": "Tencent déploie son ECS pour les 11 épreuves d’esport des Jeux asiatiques 2026, avec contrôle pré-match, surveillance en direct et archivage.",
    "source": "D’après le communiqué officiel Tencent publié le 22.09.2026.",
    "sourceUrl": "https://www.tencent.com/zh-cn/tencent-esports-competition-solution-to-support-esports-at-the-20th-asian-games/",
    "sourceDetail": "Lire le communiqué officiel",
    "sourceName": "TENCENT",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "auto": true,
    "thumbnail": "news-auto/tencent-ecs-jeux-asiatiques-esport-2026-official.png",
    "officialThumbnailUrl": "https://www.tencent.com/wp-content/uploads/2026/09/OCA.png",
    "sentiment": "positive"
  },
  "dune-awakening-sortie-consoles-mise-a-jour-15": {
    "slug": "dune-awakening-sortie-consoles-mise-a-jour-15",
    "date": "22.09.2026",
    "category": "SORTIES · FUNCOM",
    "image": "news-auto/dune-awakening-sortie-consoles-mise-a-jour-15.svg",
    "imageAlt": "Dune: Awakening — visuel éditorial Let’s Play sur la sortie consoles et la mise à jour 1.5",
    "cover": "DUNE: AWAKENING",
    "title": "DUNE: AWAKENING",
    "accent": "PASSE À L’ATTAQUE SUR CONSOLES.",
    "dek": "Dune: Awakening arrive sur consoles avec sa mise à jour 1.5, un mode solo complet et la conclusion du Livre 1.",
    "lead": "Arrakis ouvre enfin ses portes sur consoles. Le 22 septembre 2026, Dune: Awakening lance sa version complète sur PlayStation 5, Xbox Series X|S et Microsoft Store, avec une mise à jour 1.5 qui change aussi la manière de jouer en solo.",
    "intro": "Funcom accompagne cette sortie d’un mode solo complet, de trois niveaux de difficulté et d’options de personnalisation plus fines. La mise à jour ajoute également Great Convention Part III et le chapitre final du Livre 1, tandis que le Game Pass, le Play Anywhere et le cloud gaming sont annoncés côté Xbox.",
    "h2": "ARRAKIS S’OUVRE À TOUS",
    "p1": "La sortie console complète intervient après un accès anticipé réservé aux précommandes Deluxe et Ultimate depuis le 17 septembre. Les éditions physiques rejoignent donc le lancement du 22 septembre, avec un parcours désormais pensé pour celles et ceux qui veulent découvrir l’univers de Dune sans passer par le PC.",
    "quote": "Le vrai signal du jour, ce n’est pas seulement la console : c’est le solo qui devient une porte d’entrée à part entière.",
    "quoteBy": "L’ANALYSE LET’S PLAY",
    "h2b": "LE LIVRE 1 FERME SON PREMIER CHAPITRE",
    "p2": "Avec Great Convention Part III et son chapitre final, la mise à jour 1.5 donne aussi une conclusion au premier arc narratif. Funcom ne présente donc pas cette version comme un simple portage : le lancement sert de nouveau point d’entrée et de rendez-vous pour les joueurs déjà présents.",
    "p3": "Le mode solo propose trois difficultés prédéfinies, mais aussi des réglages plus précis pour adapter l’expérience. Cette souplesse compte dans un jeu qui mêle survie, exploration et progression persistante dans un monde partagé.",
    "p4": "Pour Let’s Play, le rendez-vous est clair : la version console doit maintenant prouver que l’échelle d’Arrakis fonctionne aussi loin du clavier-souris. Le trailer officiel pose l’ambiance ; le verdict, lui, viendra des premières heures manette en main.",
    "take": "À RETENIR",
    "takeText": "Dune: Awakening sort sur consoles le 22 septembre 2026 avec la mise à jour 1.5, un mode solo complet et la fin du Livre 1.",
    "source": "D’après l’annonce officielle de Funcom publiée le 22.09.2026.",
    "sourceUrl": "https://duneawakening.com/news/announcement/the-new-dune-awakening-is-here/",
    "sourceDetail": "Lire l’annonce officielle",
    "sourceName": "FUNCOM",
    "video": "pn7OQJ9EbR0",
    "videoTitle": "Dune: Awakening — Console and Single-Player Launch Trailer",
    "credit": "Visuel : carte éditoriale Let’s Play générée automatiquement.",
    "auto": true,
    "thumbnail": "news-auto/dune-awakening-sortie-consoles-mise-a-jour-15-official.jpg",
    "officialThumbnailUrl": "https://duneawakening.com/wp-content/uploads/Steam-News-Website-Banners_Website_16x9.jpg",
    "sentiment": "positive"
  }
};
