// Tests de la rédaction Let's Play — vignettes, notes et articles complets.
// Les tests reprennent la sélection et les verdicts d'ActuGaming, reformulés
// dans le ton maison par la rédaction Let's Play (source citée en bas d'article).
import { baseUrl as base } from './data';

const img = (file) => `${base}reviews/${file}`;

export const scoreTier = (score) => (score >= 8.5 ? 'is-hit' : score >= 7.5 ? 'is-good' : 'is-mid');
export const scoreLabel = (score, lang = 'fr') => String(score).replace('.', lang === 'en' ? '.' : ',');

export const gameTests = [
  {
    slug: 'wolverine',
    route: '/reviews/wolverine',
    name: "MARVEL'S WOLVERINE",
    accent: 'DES GRIFFES, PAS ENCORE UNE LAME.',
    cardTitle: "WOLVERINE — DE BELLES GRIFFES, UN MANQUE D'AFFÛTAGE",
    eyebrow: 'TEST · ACTION-AVENTURE',
    date: '10.09.2026',
    dateLong: '10 SEPTEMBRE 2026',
    platforms: 'PS5',
    genre: 'ACTION-AVENTURE',
    studio: 'INSOMNIAC GAMES · SONY',
    duration: '15-20 H',
    score: 7,
    image: img('wolverine.jpg'),
    alt: "Key art de Marvel's Wolverine, Logan en costume jaune, griffes en avant",
    coverKicker: 'SNIKT. ENFIN.',
    excerpt: "Insomniac met enfin Logan en tête d'affiche : combats bestiaux, écriture au cordeau… et quelques arènes qui tapent sur les nerfs.",
    dek: "Insomniac offrait à Logan son premier vrai grand jeu solo depuis dix-sept ans. Le combat est bestial, l'histoire mature et le doublage impec — mais la lisibilité prend souvent cher.",
    lead: "Dix-sept ans. C'est le temps qu'il a fallu attendre après X-Men Origins : le jeu vidéo pour revoir Wolverine en tête d'affiche. Autant dire que la rentrée de la PS5 lui déroulait le tapis rouge, entre le savoir-faire super-héroïque d'Insomniac et la promesse d'un combat viscéral. On a enfoncé les griffes dedans une vingtaine d'heures, en difficile. Verdict ?",
    sections: [
      {
        h2: 'LOGAN N’EST PAS L’ARAIGNÉE',
        ps: [
          "Oubliez tout de suite la recette Spider-Man : pas de monde ouvert, pas de toile entre les buildings. Marvel's Wolverine assume la ligne droite et nous embarque au Canada, au Japon et dans les bas-fonds de Madripoor aux côtés de la Team X — Mystique, Dents-de-Sabre — et d'une Jean Grey précieuse. Une aventure dirigiste, resserrée, qui a le bon goût de ne jamais se diluer.",
          "Le studio creuse surtout le passé brumeux de Logan, distillé goutte à goutte jusqu'à dessiner le portrait d'une brute tourmentée, bien plus profond que sa réputation de machine à découper. Mentions très spéciales aux comédiens : Liam McIntyre en VO et, en VF, Jérémie Covillault — la voix française habituelle de Hugh Jackman — livrent des prestations impeccables. On s'accroche à l'intrigue, même quand un ou deux raccourcis scénaristiques pointent le bout de leur griffe.",
        ],
      },
      {
        pull: { text: 'On ne joue pas un super-héros invincible : on joue un homme qui encaisse pour mieux faire saigner.', by: 'LA RÉDACTION, MANETTE EN MIETTES' },
      },
      {
        h2: 'LA FUREUR, OUI, MAIS À QUEL PRIX ?',
        ps: [
          "Logan est quasi immortel, en adamantium de la tête aux pieds : pour que le combat ait du sens, Insomniac a choisi de le faire souffrir. Les ennemis attaquent en meute, par deux, par trois, sans répit, à une vitesse qui donne l'impression de combattre les sbires d'un Spider-Man passés en ×2. Quand ça clique, c'est jouissif : parade au poil, exécutions sauvages et sensation de puissance animale.",
          'Mais trop souvent, on subit l’arène plus qu’on ne la maîtrise. Entre les angles morts de la caméra, les tirs à distance et les vagues chargées, deux ou trois esquives ratées d’affilée suffisent à vous mettre au tapis sans toujours comprendre ce qui vient d’arriver. Dommage : la lisibilité est le vrai facteur limitant du jeu, pas la difficulté.',
        ],
      },
      {
        h2: 'UN BLOCKBUSTER QUI A LA DALLE',
        ps: [
          "Sur PS5 Pro, la plastique est à la hauteur du studio : cadrages cinémas, visages crédibles et mise en scène qui en met plein les griffes. La quête principale se boucle entre quinze et vingt heures à 100 %, avec juste ce qu'il faut de contenu annexe pour prolonger sans gaver.",
          "Reste une petite frustration : Wolverine tient plus du très bon jeu de lancement que du classique instantané. Les fondations sont là, les personnages aussi. Avec une suite qui affûterait la lisibilité des arènes, Insomniac tient sa prochaine grande saga Marvel.",
        ],
      },
    ],
    pros: [
      'Écriture mature et doublages impeccables, VF comprise',
      'Un combat viscéral, griffes qui font vraiment mal',
      'Mise en scène et voyage : Canada, Japon, Madripoor',
      'Une vingtaine d’heures resserrées, sans remplissage',
    ],
    cons: [
      'Arènes trop chargées : la lisibilité dans le dur',
      'Des ennemis rapides et nombreux, parfois injustes',
      'Deux ou trois facilités scénaristiques',
    ],
    verdictTitle: 'GRATTÉ, PAS K.-O.',
    verdictText: 'À faire pour son histoire et sa violence jouissive, en pardonnant des arènes qui tabassent plus que de raison. Logan méritait sa revanche : la voilà, vivement la lame affûtée.',
    sourceUrl: 'https://www.actugaming.net/test-marvels-wolverine-review-821408/',
  },
  {
    slug: 'orbitals',
    route: '/reviews/orbitals',
    name: 'ORBITALS',
    accent: 'DEUX MANETTES, UN SEUL VAISSEAU.',
    cardTitle: 'ORBITALS — LE COOP CANAP’ QUI RESSEMBLE À UN ANIMÉ DES ANNÉES 80',
    eyebrow: 'TEST · AVENTURE COOPÉRATIVE',
    date: '09.09.2026',
    dateLong: '9 SEPTEMBRE 2026',
    platforms: 'SWITCH 2',
    genre: 'AVENTURE / COOP',
    studio: 'SHAPEFARM · KEPLER INTERACTIVE',
    duration: '6-8 H',
    score: 8.5,
    image: img('orbitals.jpg'),
    alt: "Key art d'Orbitals, deux héros façon animé spatial japonais des années 80",
    coverKicker: 'PRÊTS POUR LE DÉCOLLAGE ?',
    excerpt: 'Deux joueurs, un canapé et un animé spatial des années 80 à dérouler. La plus jolie surprise coop de la Switch 2.',
    dek: "Premier jeu du studio tokyoïte Shapefarm, exclusivité Switch 2, Orbitals transforme la coopération en langage commun. Beau comme un dessin animé du samedi matin, malin comme un It Takes Two envoyé en orbite.",
    lead: "À l'heure où le multijoueur en ligne règne sans partage, Shapefarm défend une espèce en voie de disparition : l'aventure à deux sur le même canapé. Et dès la cinématique d'introduction, tournée à l'ancienne, avec son filtre cathodique et ses doublages qui sentent bon le Capitaine Flam, on était déjà conquis. Reste une question : Orbitals a-t-il autre chose qu'une direction artistique de folie ?",
    sections: [
      {
        h2: 'UN ANIMÉ JAPONAIS… JOUABLE',
        ps: [
          "Le pari est simple : donner l'impression de plonger dans un animé nippon des années 80/90. Pari tenu du début à la fin. Les personnages, les décors, les animations, tout est au diapason, sans aucune texture laissée au hasard. Le filtre façon écran CRT fera sourire ceux qui ont connu ces moniteurs ; les autres le couperont, mais personne ne restera indifférent.",
          "Carcasses de vaisseaux, planètes gelées, vide intersidéral bariolé : même cloisonné et taillé en couloirs, le voyage n'ennuie jamais. On a testé en couple, manette Pro d'un côté et Joy-Con de l'autre, et la constante du jeu nous a bluffés : là où tant de titres donnent tout dans les deux premières heures, Orbitals surprend jusqu'au générique de fin.",
        ],
      },
      {
        pull: { text: 'On ne regarde pas Orbitals, on y met les mains — et c’est encore plus beau.', by: 'LA RÉDACTION, DEUX MANETTES À LA MAIN' },
      },
      {
        h2: 'IL EN FAUT DEUX',
        ps: [
          "Comme chez Hazelight, chaque joueur voit des choses différentes et détient la moitié de la solution. L'un manipule un panneau pendant que l'autre vise, les écrens se séparent puis se rejoignent, les énigmes vous forcent à communiquer avec les mains quand les mots ne suffisent plus. Les mécaniques se renouvellent en permanence, jusqu'aux mini-jeux bonus planqués après le générique.",
          "L'histoire, elle, ne révolutionne rien — c'est un prétexte d'aventure, mais un prétexte magnifiquement mis en scène, avec une petite troupe attachante et un retournement prévisible qui fait malgré tout son effet. Doublages français et japonais sont de qualité ; on a fini en VO pour la synchronisation labiale, pur régal.",
        ],
      },
      {
        h2: 'COURT, MAIS JAMAIS CREUX',
        ps: [
          "Comptez six à huit heures pour voir le bout, et une trentaine de minutes de mini-jeux en prime. À une cinquantaine d'euros sur l'eShop, l'heure de vol pique un peu. Mais comme chez un certain Boomerang X, la durée n'est pas vraiment un défaut : Orbitals se termine avant de tomber à court d'idées ou de se mettre à recycler pour meubler.",
          "On en voulait encore, et c'est sans doute le plus beau compliment qu'on puisse faire à un premier jeu. Shapefarm est un studio à surveiller comme une comète.",
        ],
      },
    ],
    pros: [
      'Direction artistique « animé 80’s » sans la moindre fausse note',
      'Coop canap’ aussi drôle qu’intelligente',
      'Aucun temps mort, des mécaniques renouvelées jusqu’au bout',
      'Doublages FR et japonais de grande qualité',
    ],
    cons: [
      '6-8 h seulement, on en voudrait le double',
      '50 €, ça pique un peu l’heure de vol',
      'Scénario prétexte, même très mignon',
    ],
    verdictTitle: 'ÉQUIPAGE OBLIGATOIRE',
    verdictText: "Le jeu à lancer avec son pote, sa moitié ou son petit frère un dimanche soir. Une exclusivité Switch 2 qui justifie à elle seule de dépoussiérer les Joy-Con. Hazelight peut rester tranquille… et prendre des notes.",
    sourceUrl: 'https://www.actugaming.net/test-orbitals-review-823213/',
  },
  {
    slug: 'zero-company',
    route: '/reviews/zero-company',
    name: 'STAR WARS ZERO COMPANY',
    accent: 'XCOM RENCONTRE LA FORCE.',
    cardTitle: 'ZERO COMPANY — LA GALAXIE LOINTAINE PASSE AU TOUR PAR TOUR',
    eyebrow: 'TEST · TACTIQUE TOUR PAR TOUR',
    date: '01.09.2026',
    dateLong: '1er SEPTEMBRE 2026',
    platforms: 'PC · PS5 · XBOX SERIES',
    genre: 'STRATÉGIE / TACTIQUE',
    studio: 'BIT REACTOR · ELECTRONIC ARTS',
    duration: '~40 H',
    score: 7.5,
    image: img('zero-company.jpg'),
    alt: 'Key art de Star Wars Zero Company, Hawks et son escouade de héros',
    coverKicker: 'LA GUERRE DES CLONES, AU TOUR PAR TOUR',
    excerpt: 'Les papas de XCOM s’emparent de la Guerre des Clones. Strat’ solide, écriture au poil, démarrage poussif : la Force est là, mais elle prend son temps.',
    dek: "Bit Reactor, fondé par des vétérans de Firaxis et de XCOM, embarque la Guerre des Clones dans le tour par tour tactique. Une campagne généreuse et très écrite, qui se contente hélas de mettre une quinzaine d'heures à décoller.",
    lead: "Après des dizaines de jeux Star Wars, la licence s'attaque enfin à un genre qu'on ne lui connaissait pas : la tactique au tour par tour. Et pour ce premier tir, Electronic Arts a confié le sabre à Bit Reactor, un studio fondé en 2022 par d'anciens de Firaxis — les gens derrière XCOM. Quarante heures de campagne plus tard, la visée est bonne, même si le laser met du temps à chauffer.",
    sections: [
      {
        h2: 'LA COMPAGNIE ZÉRO À LA RESCOUSSE',
        ps: [
          "Direction le crépuscule de la Guerre des Clones. Vous incarnez Hawks, ancien officier de la République devenu bouc émissaire d'une catastrophe et reconverti chef d'une escouade secrète, la Compagnie Zéro. Sa cible : Kundri Fathom, gourou de la Spire infinie, une secte séparatiste qui entend bien renverser l'issue du conflit.",
          "Une douzaine de planètes sont réellement jouables — Sullust, Lothal, Ryloth, Vandor — aux environnements et level design étonnamment variés, tandis que cent cinquante autres mondes se vivent en opérations textuelles sur l'holotable. Le fan-service est partout, des batailles canon aux caméos iconiques, mais toujours distillé avec respect, sans jamais noyer le nouveau venu.",
        ],
      },
      {
        pull: { text: 'Chaque opération ratée, c’est une info qui file entre les doigts : le jeu vous oblige à choisir, et c’est là qu’il gagne.', by: 'LA RÉDACTION, HOLOTABLE PLEINE D’ONGLETS' },
      },
      {
        h2: 'LE TEMPS, C’EST DU RENSEIGNEMENT',
        ps: [
          "L'holotable est le cœur de votre planque, et la plus belle idée du jeu. Les « cycles » font avancer le calendrier : impossible de remplir toutes les missions et opérations disponibles, il faut sans cesse prioriser en fonction des récompenses, des dilemmes moraux et des renseignements rapportés. La dimension stratégique commence avant même de poser un pied sur le champ de bataille.",
          "Sur le terrain, l'ADN Firaxis coule dans les veines : couvertures, lignes de vue, capacités de Jedi au sabre ou blasters de spécialistes. C'est une excellente porte d'entrée dans le genre, accessible sans être idiot, avec suffisamment de profondeur pour tenir les quarante heures de campagne. Idéal pour découvrir la grille sans pleurer sur un écran de game over.",
        ],
      },
      {
        h2: 'IL LUI FAUT UN DÉMARREUR',
        ps: [
          "Le vrai défaut, c'est le rythme. Pendant la première dizaine d'heures, les missions s'enchaînent sans véritable objectif clair ; l'histoire ne décolle vraiment qu'une fois l'escouade complète réunie, soit entre quinze et dix-neuf cycles. Accrochez-vous : la seconde moitié, écrite et politique comme il faut, vaut largement l'attente.",
          "Techniquement et visuellement, Zero Company reste fonctionnel sans jamais décrocher la mâchoire. Très bon jeu narratif tactique, il lui manquait juste un premier acte aussi serré que le reste.",
        ],
      },
    ],
    pros: [
      'La patte tactique d’ex-Firaxis, accessible sans être simpliste',
      'Holotable, cycles et dilemmes qui ont vraiment du sens',
      'Écriture et fan-service respectueux de la saga',
      'Une quarantaine d’heures de campagne bien remplie',
    ],
    cons: [
      '10 à 15 h avant que l’histoire et l’équipe ne décollent',
      'Première impression générique',
      'Technique et mise en scène fonctionnelles, sans plus',
    ],
    verdictTitle: 'À JOUER EN PATIENCE',
    verdictText: "Un très bon jeu tactique pour qui tient la distance. Les impatients peuvent passer leur chemin ; les amateurs de grille et de sabre laser, réservez votre semaine, la seconde moitié vaut le détour.",
    sourceUrl: 'https://www.actugaming.net/test-star-wars-zero-company-un-tres-bon-jeu-tactique-dans-lunivers-de-la-guerre-des-etoiles-821024/',
  },
  {
    slug: 'onimusha',
    route: '/reviews/onimusha',
    legacy: true,
    name: 'ONIMUSHA: WAY OF THE SWORD',
    accent: 'LA LAME SE SOUVIENT.',
    cardTitle: 'ONIMUSHA — LA SAGA SAMOURAÏ RÉAFFÛTE SA LAME',
    eyebrow: 'TEST · ACTION',
    date: '31.08.2026',
    dateLong: '31 AOÛT 2026',
    platforms: 'PC · PS5 · XBOX SERIES · SWITCH 2',
    genre: 'ACTION / SAMOURAÏ',
    studio: 'CAPCOM',
    duration: '30 H+',
    score: 8,
    image: img('onimusha.jpg'),
    alt: 'Key art de Onimusha: Way of the Sword, le héros armé face aux démons',
    coverKicker: 'LA LAME SE SOUVIENT',
    excerpt: 'Capcom ressuscite sa saga samouraï avec une lame affûtée. Trente heures d’action précise, quelques finitions à reprendre et un final qui fait mouche.',
    dek: "Way of the Sword relance la saga avec des combats précis, un contenu généreux et une poignée d'aspérités. Le test complet vous attend dans son article dédié.",
    sourceUrl: 'https://www.actugaming.net/test-onimusha-way-of-the-sword-review-818222/',
  },
  {
    slug: 'dawnwalker',
    route: '/reviews/dawnwalker',
    name: 'THE BLOOD OF DAWNWALKER',
    accent: '30 JOURS POUR NE PAS DEVENIR UN MONSTRE.',
    cardTitle: 'DAWNWALKER — LE RPG DES EX-WITCHER QUI FAIT DU TEMPS SA RESSOURCE',
    eyebrow: "TEST · ACTION-RPG MONDE OUVERT",
    date: '31.08.2026',
    dateLong: '31 AOÛT 2026',
    platforms: 'PC · PS5 · XBOX SERIES',
    genre: 'ACTION-RPG / MONDE OUVERT',
    studio: 'REBEL WOLVES',
    duration: '~35 H',
    score: 8,
    image: img('dawnwalker.jpg'),
    alt: 'Key art de The Blood of Dawnwalker, Coen griffes et épée sous un soleil de sang',
    coverKicker: 'LA NUIT APPARTIENT AUX VAMPIRES',
    excerpt: "Vampire la nuit, humain le jour, 30 jours pour sauver sa famille. Le premier RPG des ex-Witcher fait de l'horloge son meilleur système.",
    dek: "Les ex-CD Projekt de Rebel Wolves signent un action-RPG sombre, très Witcher-esque, où le temps est votre seule vraie ressource. Encore imparfait techniquement, mais sacrément vivant.",
    lead: "Quand une équipe composée d'anciens de The Witcher annonce un RPG de fantasy crépusculaire, tout le monde dresse l'oreille. The Blood of Dawnwalker assume même fièrement son héritage : mordu par un vampire, son héros ne dispose que de trente jours et de trente nuits pour sauver les siens. On y a passé près de trente-cinq heures sur PS5, avant le patch day one. Récit d'un pari tenu de justesse.",
    sections: [
      {
        h2: 'VAL SANGORA, VALLÉE SOUS LE JOUG',
        ps: [
          "Bienvenue à Val Sangora, vallée des Carpates au XIVe siècle, dévastée par la peste. Le seigneur local fait exécuter quiconque présente un symptôme — jusqu'à l'arrivée des Vrakhiri, des vampires que la peste n'affecte pas et dont le sang guérit. Le marché est vite une prise d'otage : obéissance et messes impies contre la santé.",
          "C'est dans le village de Laslea que vit Coen, héros malgré lui. Mordu, il devient un « Vespéral » : humain au soleil, vampire à la nuit tombée. Sa famille enlevée par le nouveau seigneur Brencis, le compte à rebours commence. La promesse est énorme ; le cadre, lui, joue la carte du réalisme condensé — montagnes, forêts, marais et capitale Svartrau, sans jamais viser la claque graphique.",
        ],
      },
      {
        pull: { text: 'Ici, nettoyer un camp coûte un segment de journée. Aider un inconnu en coûte trois. Et soudain, chaque quête compte.', by: 'LA RÉDACTION, L’HORLOGE DANS LA TÊTE' },
      },
      {
        h2: 'LE MEILLEUR SYSTÈME DU JEU, C’EST L’HORLOGE',
        ps: [
          "Chaque jour et chaque nuit sont divisés en huit segments. L'exploration libre ne consomme rien, mais les actions importantes, elles, débitent le compteur. Rebel Wolves prévient toujours du temps que prendra une tâche, et surtout : pas de game over si vous gérez mal. Les trente jours ne concernent que le sort de la famille. L'horloge structure l'aventure, crée de l'enjeu et change la résolution des quêtes, sans jamais devenir un carcan.",
          "Fini les annexes qui sabotent l'urgence du récit : ici, on se demande réellement si une mission vaut la nuit qu'on lui sacrifie. Ajoutez à cela les pouvoirs nocturnes de Coen, ses choix moraux, son équipement et ses arbres de compétences, et vous tenez la relève la plus convaincante de la formule CD Projekt depuis des années.",
        ],
      },
      {
        h2: 'DU SANG, DES CROCS ET DES RATS TECHNIQUES',
        ps: [
          "Soyons honnêtes : sur notre build pré-patch, la finition était clairement insuffisante, et la vallée donne parfois une impression de « déjà-arpenté » propre aux mondes ouverts de fantasy. Le combat, solide sans être révolutionnaire, demande encore un peu d'huile.",
          "Mais le socle est là : des quêtes écrites avec l'exigence qu'on attendait, une mécanique centrale qui change tout, et une identité vampirique qui sort du lot. Avec le patch day one et quelques mois de polish, Dawnwalker pourrait bien devenir l'incontournable des amateurs du genre.",
        ],
      },
    ],
    pros: [
      'Le système de temps, brillant, qui donne du poids à chaque action',
      'Écriture et quêtes dignes de l’héritage Witcher',
      'Ambiance crépusculaire et vampires qui renouvellent la formule',
      '35 h d’enjeux permanents, sans jamais gaver',
    ],
    cons: [
      'Technique à la rue sur notre version pré-patch',
      'Monde ouvert visuellement très (trop ?) familier',
      'Quelques combats perfectibles',
    ],
    verdictTitle: 'À MORDRE, PATCH RECOMMANDÉ',
    verdictText: "Le pari est réussi, avec de béantes aspérités de finition. Si vous attendiez un RPG qui vous demande de choisir plutôt que de cocher des cases, foncez — de préférence après le patch day one.",
    sourceUrl: 'https://www.actugaming.net/test-the-blood-of-dawnwalker-821035/',
  },
  {
    slug: 'boomerang-x',
    route: '/reviews/boomerang-x',
    name: 'BOOMERANG X',
    accent: 'UNE SEULE ARME, UN FLOW INFINI.',
    cardTitle: 'BOOMERANG X — LA PÉPITE FPS D’UN STUDIO MORT AVANT LA GLOIRE',
    eyebrow: 'TEST · FPS / ARÈNES',
    date: '28.08.2026',
    dateLong: '28 AOÛT 2026',
    platforms: 'PC · SWITCH',
    genre: 'FPS / ACTION',
    studio: 'DANG · DEVOLVER DIGITAL',
    duration: '2 H 30 + NG+',
    score: 8.5,
    image: img('boomerang-x.jpg'),
    alt: 'Bannière noir et jaune de Boomerang X, le logo cerné de créatures à l’encre',
    coverKicker: 'LANCER. RAPPELER. RECOMMENCER.',
    excerpt: "Un seul boomerang, un flow de folie et 2 h 30 de pur bonheur. La pépite oubliée d'un studio de cinq personnes fermé avant la gloire.",
    dek: "En 2021, cinq personnes sous le nom de DANG signaient chez Devolver un FPS qui remplaçait tous les flingues par un boomerang magique. Chef-d'œuvre de flow enterré trop tôt avec son studio, qu'on ressort aujourd'hui du placard.",
    lead: "Boomerang X n'est pas un FPS comme les autres. Pas de shotgun, pas de mitrailleuse, pas de rechargement : juste vous, une plage déserte et un boomerang légué par une civilisation éteinte. Et croyez-nous, c'est suffisant pour tutoyer le culte. Petit retour en 2021, sur la Switch de l'époque, pour rendre hommage à un jeu que son propre studio n'a pas eu le temps de voir triompher.",
    sections: [
      {
        h2: 'LE BOOMERANG QUI VOUS DÉPLACE',
        ps: [
          "Les premières minutes sont trompeuses : pas de dash, pas de double saut, votre personnage se traîne. Puis vous mettez la main sur le boomerang. On le lance — ça tue net ; on le charge — il traverse plusieurs cibles ; on le rappelle d'une gâchette et il revient instantanément. Jusqu'ici, classique.",
          "Le génie, c'est que le boomerang est aussi un outil de déplacement. En vous rappelant à lui en plein vol, vous vous propulsez dans les airs ; le ralenti au bon moment permet d'enchaîner les éliminations sans retoucher le sol. Ajoutez les pouvoirs distribués arène après arène et, au bout d'une heure, on se croit dans Ghostrunner… avec un bout de bois. On vous conseille juste de monter la sensibilité caméra, trop molle par défaut.",
        ],
      },
      {
        pull: { text: 'On lance, on se rappelle à soi-même en plein vol, on tranche trois ennemis, et le sol ne nous manque plus jamais.', by: 'LA RÉDACTION, EN ÉTAT DE FLOW' },
      },
      {
        h2: 'LOW POLY, HAUTES SENSATIONS',
        ps: [
          "Le jeu se découpe en arènes reliées par des couloirs menant à de vieilles statues et des constructions titanesques. Son esthétique low poly cache des lieux gigantesques et variés, qui racontent plus qu'ils ne parlent — l'histoire est à peine un prétexte, et ce n'est pas plus mal.",
          "Seul accompagnement qui déçoit : la bande-son, quelconque là où on rêvait d'électro nerveuse à la Ghostrunner. Heureusement, le rythme du gameplay compose sa propre musique.",
        ],
      },
      {
        h2: 'DEUX HEURES TRENTE, ZÉRO REMPLISSAGE',
        ps: [
          "Sans forcer, malgré les morts, la première run se plie en 2 h 30, avec une fin expédiée après une arène infernale et un boss final presque trop clément. On aurait aimé que ça dure : les idées lumineuses auraient largement tenu le double, et un New Game + permet de prolonger le plaisir.",
          "Mais le plus triste, c'est l'histoire autour du jeu : DANG, cinq personnes, n'a jamais sorti qu'un seul titre avant de fermer, faute de financement pour le suivant. En 2026 comme en 2021, Boomerang X mérite une place de choix dans toute ludothèque — et son studio, qu'on se souvienne de lui.",
        ],
      },
    ],
    pros: [
      'Un FPS de mouvement parmi les plus grisants du genre',
      'Le boomerang, jouet mortel aux possibilités énormes',
      'Arènes low-poly majestueuses et parfaitement rythmées',
      'Zéro gras, que du flow',
    ],
    cons: [
      '2 h 30, c’est brutalement court',
      'OST totalement oubliable',
      'Fin expédiée et boss final trop gentil',
      'Le studio n’existe plus, pas de suite en vue',
    ],
    verdictTitle: 'À LANCER D’URGENCE',
    verdictText: "Une pépite à faire d'une traite, souvent en promo sur l'eShop ou Steam. On donne rarement 8,5 à un jeu de deux heures et demie : celui-là les vaut largement — et c'est bien ça qui rend la fin de DANG si triste.",
    sourceUrl: 'https://www.actugaming.net/test-boomerang-x-chef-doeuvre-dun-studio-mort-avant-la-gloire-812967/',
  },
  {
    slug: 'resonance',
    route: '/reviews/resonance',
    name: 'RESONANCE: A PLAGUE TALE LEGACY',
    accent: 'LE PASSÉ DE SOPHIA, ENTRE CRÈTE ET LABYRINTHE.',
    cardTitle: 'RESONANCE — PLAGUE TALE PART EN GRÈCE ANTIQUE ET PREND DES RISQUES',
    eyebrow: 'TEST · ACTION-AVENTURE / ÉNIGMES',
    date: '26.08.2026',
    dateLong: '26 AOÛT 2026',
    platforms: 'PC · PS5 · XBOX SERIES',
    genre: 'ACTION-AVENTURE',
    studio: 'ASOBO STUDIO · FOCUS',
    duration: '~16 H',
    score: 7.5,
    image: img('resonance.jpg'),
    alt: 'Key art de Resonance: A Plague Tale Legacy, Sophia armée en Crète antique',
    coverKicker: '15 ANS AVANT LA MACULA',
    excerpt: 'Asobo fait de Sophia l’héroïne d’une préquelle entre Crète minoenne et XIVe siècle. Énigmes brillantes, combats fragiles, récit qui prend son temps.',
    dek: "Asobo change de héros et d'époque pour sa préquelle : place à Sophia, quinze ans avant Amicia et Hugo, entre Moyen Âge et Crète minoenne. Des énigmes superbes, des combats en demi-teinte, un pari narratif audacieux.",
    lead: "Troisième épisode d'une série qu'on n'attendait pas aussi ambitieuse, Resonance lâche Amicia et Hugo pour suivre Sophia, la capitaine contrebandière croisée dans Requiem. Présenté au Xbox Games Showcase, il raconte les événements quinze ans avant la tragédie de la Prima Macula — et dévie carrément vers la mythologie grecque. Seize heures plus tard, le pari s'avère plus passionnant que bancal, mais pas sans éraflures.",
    sections: [
      {
        h2: 'DEUX ÉPOQUES, UNE SEULE SOPHIA',
        ps: [
          "Le jeu nous fait chevaucher deux lignes temporelles : le XIVe siècle de la jeune Sophia et l'époque minoenne, Thésée inclus, à travers un récit qui cherche à remonter aux origines de la malédiction. Démarrage déroutant, questions qui s'empilent — jusqu'au chapitre X, où toutes les pièces du puzzle s'assemblent avec une netteté presque jouissive. Le lien avec les deux premiers jeux est criant, contrairement à ce qu'on pouvait craindre.",
          "Le bât blesse côté relations : Leni, qui accompagne Sophia pendant l'essentiel de l'aventure, n'a que quelques phrases de cutscene pour établir une amitié censée nous tenir à cœur. L'alchimie Amicia/Hugo ne se décrète pas, et quelques scènes de fondation manquent à l'appel. Le trio Sophia/Thésée/antagoniste, lui, est traité avec bien plus de soin.",
        ],
      },
      {
        pull: { text: 'Jusqu’au chapitre X, on doutait. Après, toutes les pièces du labyrinthe s’emboîtent — et on aurait aimé y arriver plus tôt.', by: 'LA RÉDACTION, CARNET DE MYTHO À LA MAIN' },
      },
      {
        h2: 'RÉFLÉCHIR VAUT MIEUX QUE FRAPPER',
        ps: [
          "La première moitié est une réussite de game design d'énigmes. On se creuse la tête sans jamais s'ennuyer, et les indices sont ingénieux : ils orientent sans donner la réponse, forçant à envisager le problème autrement. Dans ces séquences, Resonance trouve son identité et fait même mieux que ses aînés.",
          "Mais le titre mute ensuite en jeu d'action, et c'est là que le bât blesse fort. Les combats sont rigides, les ennemis ont des comportements quasi identiques et aucune vraie variété tactique n'est proposée ; l'arbre de compétences de Sophie semble même perdre son sens une fois qu'on comprend d'où viennent ses pouvoirs. On subit des affrontements qui tranchent avec la finesse des énigmes.",
        ],
      },
      {
        h2: 'UN TROISIÈME ÉPISODE QUI PREND DES RISQUES',
        ps: [
          "Avec sa mythologie riche, ses deux époques et son héroïne solaire, Resonance est plus qu'un spin-off : c'est une vraie prise de risque pour Asobo, dont on aimerait que les autres studios s'inspirent. Le dosage entre énigmes, action et narration demande juste une seconde couche de réglage.",
          "En l'état, les fidèles d'Amicia seront récompensés de leur patience ; les nouveaux venus feraient mieux de commencer par les deux premiers avant de plonger dans ce labyrinthe.",
        ],
      },
    ],
    pros: [
      'Les énigmes de la première moitié, fines et gratifiantes',
      'Double époque audacieuse, liée à la saga avec intelligence',
      'Sophia, héroïne complexe qui mérite son jeu',
      'Ambiance Asobo et travail sonore toujours aussi soignés',
    ],
    cons: [
      'Les combats, rigides et vite redondants',
      'La relation Sophia/Leni, largement survolée',
      'Récit qui met plusieurs chapitres à démarrer',
      'Équilibre énigmes/action à revoir sur la seconde moitié',
    ],
    verdictTitle: 'SORTIR DU LABYRINTHE VAUT LE COUP',
    verdictText: "Un changement de direction courageux qui paie sur le fond mais trébuche sur ses phases d'action. Accrochez-vous pendant les premiers chapitres : la sortie du labyrinthe réserve de belles émotions aux amateurs de la série.",
    sourceUrl: 'https://www.actugaming.net/test-resonance-a-plague-tale-legacy-819939/',
  },
  {
    slug: 'duskfade',
    route: '/reviews/duskfade',
    name: 'DUSKFADE',
    accent: 'JAK, RATCHET… ET UN PEU DE KEYBLADE.',
    cardTitle: 'DUSKFADE — LA LETTRE D’AMOUR AUX PLATFORMERS 3D DES ANNÉES 2000',
    eyebrow: 'TEST · ACTION-PLATEFORME 3D',
    date: '21.08.2026',
    dateLong: '21 AOÛT 2026',
    platforms: 'PC · PS5 · XBOX SERIES · SWITCH 2',
    genre: 'PLATEFORME / ACTION',
    studio: 'WEIRD BELUGA · FIRESHINE GAMES',
    duration: '~14 H',
    score: 8,
    image: img('duskfade.jpg'),
    alt: 'Key art de Duskfade, Zirian sur une aiguille géante face à une tour d’horloge cosmique',
    coverKicker: 'IL ÉTAIT UNE FOIS LA NUIT',
    excerpt: 'Notre lettre d’amour aux platformers 3D des années 2000 : deuil, horloges et grappin, entre Jak, Ratchet et un soupçon de Kingdom Hearts.',
    dek: "Hommage vibrant aux action-platformers 3D des années 2000, Duskfade cache sous ses couleurs clockpunk une vraie histoire de deuil. Les sauts sont au poil ; les combats de base, dans le brouillard.",
    lead: "Jak & Daxter, Ratchet & Clank, Kingdom Hearts : le studio espagnol Weird Beluga ne cache aucune de ses amours. Avec Duskfade, il ressuscite une époque où les platformers 3D étaient colorés, bavards et un peu bancals. Et contre toute attente, c'est quand il parle de la mort que ce premier jeu touche le plus juste. Quatorze heures sur PC et Steam Deck plus tard, on vous explique pourquoi.",
    sections: [
      {
        h2: 'ZIRIAN ET LA NUIT ÉTERNELLE',
        ps: [
          "Zirian est apprenti artisan dans un monde frappé par une nuit sans fin. L'apparition d'une mystérieuse tour coïncide avec la disparition de sa sœur Allira. Accompagné de Coucou, son compagnon mécanique volant, et armé de Minutero — une épée en forme d'aiguille d'horloge qui doit beaucoup à une certaine Keyblade —, il part la chercher.",
          "Le casting des boss donne d'emblée le ton émotionnel : Misère, Tristesse, Remords, Rage. Le deuil et l'acceptation ne sont pas des thèmes posés là pour faire sérieux : certaines cinématiques, très bien mises en scène, pincent sincèrement le cœur. Rare qu'un platformer indépendant assume autant.",
        ],
      },
      {
        pull: { text: 'Affronter des boss nommés Tristesse, Remords et Rage avec une épée-aiguille : voilà un jeu qui transforme le deuil en niveau de plateforme, sans jamais le rendre mièvre.', by: 'LA RÉDACTION, UN PEU LES YEUX HUMIDES' },
      },
      {
        h2: 'QUAND LA PLATEFORME CHANTE',
        ps: [
          "Les déplacements sont un modèle de lecture : sauts faciles à appréhender, grappin, bouclier qui sert de rail à glisser, nouveaux jouets distribués au rythme des biomes. Flottant et déroutant dans les premières heures, le personnage enchaîne ensuite de très jolies chorégraphies aériennes.",
          "L'exploration fait confiance au joueur, sans mini-carte ni grosse flèche jaune, et récompense la curiosité par des collectables. La direction artistique clockpunk fait des merveilles, notamment à l'Académie des horlogers, et le jeu est parfaitement validé Steam Deck — testé et approuvé par nos soins.",
        ],
      },
      {
        h2: 'QUAND LE COMBAT CRIE',
        ps: [
          "C'est le vrai point noir : les affrontements de base sont un bazar. Les ennemis « encreurs », très Kingdom Hearts dans l'âme, débarquent en meute là où la lisibilité n'est déjà pas le point fort. Le verrouillage adopte un mode cinéma à bandes noires et perd le fil dès qu'il y a plus de trois cibles à l'écran. On subit plus qu'on ne maîtrise.",
          "Et c'est d'autant plus frustrant que les combats de boss, eux, sont excellents : mise en scène spectaculaire, plateforme et gadgets mélangés, lisibilité revenue. Preuve que Weird Beluga sait faire — il restera à tout porter au même niveau pour la prochaine fois.",
        ],
      },
    ],
    pros: [
      'Direction artistique clockpunk charmante et colorée',
      'La plateforme, précise et pleine de bonnes idées (grappin, rails)',
      'Une histoire de deuil vraie, des boss qui ont du sens',
      'Les combats de boss, carrément réussis · Steam Deck Verified',
    ],
    cons: [
      'Les combats de base, illisibles et brouillons',
      'Verrouillage de caméra fantaisiste',
      'Légère flottabilité déroutante au début',
    ],
    verdictTitle: 'UN RÉVEIL QUI VAUT LE DÉTOUR',
    verdictText: "Un tendre hommage aux jeux de notre enfance, avec un grand cœur et des trash mobs à reprendre. À faire pour sa plateforme, ses boss et sa petite larme : pour quatorze heures de dépaysement, le réveil sonne juste.",
    sourceUrl: 'https://www.actugaming.net/test-duskfade-review-817934/',
  },
  {
    slug: 'metal-gear-solid-vol2',
    route: '/reviews/metal-gear-solid-vol2',
    name: 'MGS: MASTER COLLECTION VOL. 2',
    accent: 'DEUX LÉGENDES, UN ÉCRIN SOBRE.',
    cardTitle: 'MASTER COLLECTION VOL. 2 — MGS4 ET PEACE WALKER ENFIN DE RETOUR',
    eyebrow: 'TEST · COMPILATION / INFILTRATION',
    date: '21.08.2026',
    dateLong: '21 AOÛT 2026',
    platforms: 'PC · PS5 · XBOX SERIES · SWITCH · SWITCH 2',
    genre: 'INFILTRATION / COMPILATION',
    studio: 'KONAMI',
    duration: '40 H+ DE JEUX',
    score: 7,
    image: img('mgs-vol2.jpg'),
    alt: 'Jaquette de Metal Gear Solid Master Collection Vol. 2, Old Snake et Big Boss',
    coverKicker: 'SOLID, POUR L’ÉTERNITÉ',
    excerpt: 'MGS4 et Peace Walker enfin de retour sur toutes les bécanes : deux légendes pour une compilation sobre, presque paresseuse, mais impossible à bouder.',
    dek: "Metal Gear Solid 4 : Guns of the Patriots et Peace Walker reviennent sur toutes les machines actuelles, accompagnés du petit Ghost Babel. Indispensable sur le fond, l'écrin l'est beaucoup moins sur la forme.",
    lead: "Huit ans après The Phantom Pain et la séparation d'avec Kojima, Konami poursuit son travail de mémoire. Après un Vol. 1 qui ramenait les cinq premiers opus canoniques sur les bécanes modernes et un remake Delta très sage de Snake Eater, voici enfin le deuxième volume : MGS4, Peace Walker et l'inattendu Ghost Babel, sorti sur Game Boy Color en l'an 2000. Une dizaine d'heures de vérification sur PS5 Pro plus tard, le contrat est rempli… sans panache.",
    sections: [
      {
        h2: 'OLD SNAKE ET LA PAIX DES BRAVES',
        ps: [
          "Le programme justifie à lui seul l'achat : Metal Gear Solid 4 : Guns of the Patriots, conclusion fleuve et nostalgique d'Old Snake en 2008, dormait sur PS3 ; Peace Walker, origine d'Outer Heaven et pilier de la saga Big Boss, était né sur PSP. Les voir tourner sur console actuelle — et même sur Switch 2, MGS4 en mode portable — a quelque chose d'un petit miracle.",
          "Ghost Babel, le bonus Game Boy Color, s'avère une jolie surprise pour les curieux, et les Master Books, contenu encyclopédique bourré d'archives et de chronologies, restent le plus bel ajout de la formule Master Collection.",
        ],
      },
      {
        pull: { text: 'MGS4 sur une console portable, Peace Walker qui tourne comme un charme : la nostalgie fait la moitié du travail, et elle la fait bien.', by: 'LA RÉDACTION, BOÎTE EN CARTON SUR LE DOS' },
      },
      {
        h2: 'DES PORTAGES, PAS UN REMASTER',
        ps: [
          "Il faut calibrer les attentes, exactement comme pour le Vol. 1 : Konami livre des portages propres, pas des remasters. Pas de refonte visuelle, pas de contrôles repensés, l'essentiel des réglages hérités des versions HD et des soucis qui vont avec — les habitués du premier volume ne seront pas dépaysés, en bien comme en moins bien.",
          "Bonne nouvelle pour le portefeuille : ce deuxième volume coûte dix euros de moins (49,99 €), et chaque jeu peut aussi s'acheter séparément en dématérialisé pour qui ne veut que Peace Walker ou que MGS4.",
        ],
      },
      {
        h2: 'LES GRANDS ABSENTS',
        ps: [
          "La compilation est plus maigre que la première : deux jeux principaux là où le Vol. 1 en proposait cinq. Et les absents font mal : Portable Ops, chaînon direct entre Snake Eater et Peace Walker (pourtant cité dans les Master Books !), brille par son absence, à l'image des deux Metal Gear Acid et de leur tactique par cartes.",
          "Ajoutez l'absence de versions PS4 et Xbox One — là où le premier volume y avait droit — et l'incohérence du concept « collection » saute aux yeux. Reste l'espoir d'un Vol. 3 pour Ground Zeroes et The Phantom Pain, et pourquoi pas, enfin, les vieux spin-off.",
        ],
      },
    ],
    pros: [
      'Enfin MGS4 et Peace Walker sur les supports actuels',
      'Les Master Books, vrai trésor encyclopédique',
      '10 € moins cher que le Vol. 1, jeux aussi vendus séparément',
      'Ghost Babel, le bonus surprise qui vaut le détour',
    ],
    cons: [
      'De simples portages, zéro ambition de remasterisation',
      'Volume bien moins garni que le premier (deux jeux principaux)',
      'Portable Ops et les Metal Gear Acid aux abonnés absents',
      'Pas de versions PS4 / Xbox One',
    ],
    verdictTitle: 'INDISPENSABLE, MAIS SANS SURPRISE',
    verdictText: "Pour qui n'a jamais eu de PS3 ou de PSP, c'est un achat obligé, tant ces deux jeux comptent. Les collectionneurs qui attendaient un écrin à la hauteur des légendes resteront sur leur faim — comme avec le Vol. 1, Konami assure le minimum vital.",
    sourceUrl: 'https://www.actugaming.net/test-metal-gear-solid-master-collection-vol-2-review-817039/',
  },
  {
    slug: 'marvel-tokon',
    route: '/reviews/marvel-tokon',
    name: 'MARVEL TŌKON: FIGHTING SOULS',
    accent: 'ARC SYSTEM MET LA GARDÉ.',
    cardTitle: 'MARVEL TŌKON — LE VERSUS MARVEL MAGNIFIQUE D’ARC SYSTEM WORKS',
    eyebrow: 'TEST · JEU DE COMBAT',
    date: '17.08.2026',
    dateLong: '17 AOÛT 2026',
    platforms: 'PC · PS5',
    genre: 'VERSUS FIGHTING',
    studio: 'ARC SYSTEM WORKS · SONY',
    duration: '25 H+',
    score: 7.5,
    image: img('marvel-tokon.webp'),
    alt: 'Key art de Marvel Tōkon: Fighting Souls, Spider-Man, Captain America et leurs alliés',
    coverKicker: 'QUATRE HÉROS, UNE ÂME',
    excerpt: 'Arc System Works habille Marvel en anime fighter de rêve. Quatre persos, une seule barre de vie, 21 guerriers : magnifique, mais un peu juste en contenu.',
    dek: "Neuf ans après Marvel vs. Capcom Infinite, Marvel confie ses héros aux maîtres de Guilty Gear et Dragon Ball FighterZ. Quatre combattants, une seule barre de vie, une plastique de rêve et un roster qui reste sur sa faim.",
    lead: "Quand Sony a annoncé Arc System Works aux manettes d'un versus Marvel, les fans de FighterZ et de Strive ont dressé les poings. Fini la collaboration Capcom des années 90 : place au studio roi de l'anime fighter, qui hybride ici tout son savoir-faire. Plus de vingt-cinq heures passées sur la version PS5 plus tard, le constat est net : le jeu est splendide et malin, mais il faudra repasser pour la générosité.",
    sections: [
      {
        h2: 'UNE SEULE ÂME POUR QUATRE HÉROS',
        ps: [
          "Tōkon se joue en équipe de quatre, avec un système de tag et d'assists — mais la vraie idée de génie, c'est la barre de vie unique. Les quatre combattants partagent une seule et même âme (le « tōkon » du titre) : changer de personnage au pire moment, et c'est toute l'équipe qui s'effondre. L'ordre de placement influence même les techniques d'assist. Plus simple à apprivoiser qu'un Marvel vs. Capcom à trois slots, plus tactique qu'il en a l'air.",
          "On regrette juste l'absence de temps de recharge sur les assists, qui ouvre la porte aux abus, là où un cooldown évident eût resserré les parties. Mais dans l'ensemble, la prise en main est un modèle du genre : le studio a transformé un chiffre intimidant en accessibilité.",
        ],
      },
      {
        pull: { text: 'Quatre persos, une seule barre de vie. Changez au mauvais moment et c’est toute l’équipe qui trinque : une idée aussi simple que géniale.', by: 'LA RÉDACTION, QUARTS DE CERCLE PLEIN LES POUCES' },
      },
      {
        h2: 'L’ANIME FIGHTER LE PLUS BEAU DU MONDE',
        ps: [
          "Difficile de rester de marbre : la 3D façon anime d'Arc System Works fait encore des étincelles. Les combattants sont respectés dans leurs moindres singularités — mention spéciale à Deadpool et à ses dizaines de références — et les arènes, quoique peu nombreuses, vivent comme de vrais lieux Marvel, du premier plan à l'arrière-plan.",
          "Le son est plus inégal : les musiques d'arènes s'oublient vite, là où les thèmes de personnages, eux, réveillent les matchs. Et comme toujours chez ASW, les animations sont à tomber.",
        ],
      },
      {
        h2: 'QUALITÉ SUR QUANTITÉ',
        ps: [
          "C'est le principal reproche : 21 slots de roster, c'est juste pour un jeu en équipe de quatre, et les matchs en ligne finissent par opposer toujours les mêmes têtes. Heureusement, les trouvailles de gameplay compensent : Ororo et sa gestion du vent, Hulk et ses déplacements volontairement limités, le Bouffon Vert et son planeur transforment chaque main en quelque chose d'unique. Difficile en revanche de défendre un Carnage aussi fade.",
          "Dernier point de vigilance : au lancement, le portage PC souffrait encore de gros problèmes d'optimisation. Sur PS5, en revanche, c'est du velours. À réserver aux patients sur ordinateur, le temps des patchs.",
        ],
      },
    ],
    pros: [
      'Le concept « une âme, une barre de vie », clair et tactique',
      'Graphismes et animations au sommet de l’anime fighter',
      'Des personnages vraiment uniques (Storm, Hulk, le Bouffon)',
      'Plus accessible qu’un Marvel vs. Capcom, sans perdre en profondeur',
    ],
    cons: [
      'Roster bloqué à 21, ça tourne vite en rond en ligne',
      'Peu d’arènes et OST en demi-teinte',
      'Quelques persos décevants (coucou Carnage)',
      'Portage PC dans le dur au lancement',
    ],
    verdictTitle: 'BEAU COMME UN COMBAT, JUSTE COMME UN COMIC',
    verdictText: "Le versus Marvel qu'on attendait sur le fond, splendide et malin, qui pèche surtout par générosité. À privilégier sur PS5 en attendant que le roster — et le port PC — se renforcent.",
    sourceUrl: 'https://www.actugaming.net/test-marvel-tokon-fighting-souls-review-817082/',
  },
];

export const getTest = (slug) => gameTests.find((test) => test.slug === slug);
