export const DEFAULT_DEMO_KEY = 'vortex';

export const DEMO_PROFILES = {
  vortex: {
    profileKey: 'vortex',
    id: 'demo-user-7721',
    email: 'sami.vortex@letsplay.dz',
    isDemo: true,
    user_metadata: {
      gamertag: 'VORTEX_DZ',
      fullName: 'Sami Khelifi',
      role: 'PRO PLAYER & SPEEDRUNNER',
      tier: 'TIER III · ELITE',
      level: 42,
      xp: 4850,
      nextLevelXp: 5000,
      rankTitle: 'Master Speedrunner',
      rankTag: 'TOP 5% DZ',
      avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&auto=format&fit=crop&q=80',
      joinedDate: 'October 2024',
      location: 'Algiers, Algeria',
      bio: 'Fighting games veteran (Tekken 8, Street Fighter 6) & Zelda speedrunner. 7ouma Arena 2025 finalist.',
      googleConnected: true,
      googleEmail: 'sami.vortex@gmail.com',
      googleLinkedDate: '12 Oct 2024',
      microsoftConnected: true,
      microsoftGamertag: 'VortexDZ#7721',
      microsoftLinkedDate: '04 Nov 2024',
      platforms: ['PS5', 'PC STEAM', 'SWITCH 2', 'XBOX SERIES X'],
      stats: {
        articlesRead: 48,
        commentsPosted: 19,
        savedArticles: 4,
        badgesUnlocked: 6,
      },
      badges: [
        { id: 'early', icon: '⚡', name: 'Day-1 Pioneer', desc: 'Joined Let’s Play during early alpha', rarity: 'Legendary' },
        { id: 'arena', icon: '🏆', name: '7ouma Arena 2025', desc: 'Top 16 Djezzy Mobile Cup contender', rarity: 'Epic' },
        { id: 'critic', icon: '✍️', name: 'Top Reviewer', desc: '15+ high-voted community comments', rarity: 'Rare' },
        { id: 'comiccon', icon: '🎟️', name: 'GCC Dzaïr VIP', desc: 'Registered for GCC Dzaïr 2026', rarity: 'Epic' },
        { id: 'souls', icon: '🔥', name: 'Soulsborne Veteran', desc: 'Completed the Elden Ring & Dark Souls deep-dives', rarity: 'Rare' },
        { id: 'speedrun', icon: '⏱️', name: 'Time Attack Master', desc: 'Fastest Zelda Ocarina water temple time', rarity: 'Legendary' },
      ],
      savedArticlesList: [
        { id: 'gta6', title: 'GTA VI & DualSense: Haptic Feedback Deep Dive', category: 'TECH / HARDWARE', readTime: '5 MIN READ', link: '/news/gta6-dualsense' },
        { id: 'onimusha', title: 'Onimusha: Way of the Sword — Review (8.5/10)', category: 'TEST / ACTION', readTime: '6 MIN READ', link: '/reviews/onimusha' },
        { id: 'zelda', title: 'Zelda: Ocarina of Time Remake on Switch 2', category: 'NEWS / FIRST LOOK', readTime: '4 MIN READ', link: '/news/zelda-ocarina' },
        { id: 'physint', title: 'Physint Moves to Xbox: Kojima’s Next Big Leap', category: 'INDUSTRY SHIFT', readTime: '6 MIN READ', link: '/news/physint' },
      ],
    },
  },
  pixel: {
    profileKey: 'pixel',
    id: 'demo-user-8842',
    email: 'amina.pixel@letsplay.dz',
    isDemo: true,
    user_metadata: {
      gamertag: 'PIXEL_QUEEN',
      fullName: 'Amina Benali',
      role: 'CREATOR & STREAMER',
      tier: 'TIER II · CREATOR',
      level: 28,
      xp: 2900,
      nextLevelXp: 3500,
      rankTitle: 'Cozy Explorer',
      rankTag: 'VERIFIED CREATOR',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      joinedDate: 'January 2025',
      location: 'Oran, Algeria',
      bio: 'JRPG lover, Metroidvania collector & indie game enthusiast. Streaming weekly Let’s Play community co-ops.',
      googleConnected: true,
      googleEmail: 'amina.pixel@gmail.com',
      googleLinkedDate: '15 Jan 2025',
      microsoftConnected: false,
      microsoftGamertag: 'PixelQueenDZ',
      microsoftLinkedDate: null,
      platforms: ['SWITCH 2', 'PC STEAM', 'PS5'],
      stats: {
        articlesRead: 32,
        commentsPosted: 27,
        savedArticles: 3,
        badgesUnlocked: 4,
      },
      badges: [
        { id: 'streamer', icon: '🎥', name: 'Community Streamer', desc: 'Featured on Let’s Play Community Live', rarity: 'Epic' },
        { id: 'indie', icon: '💎', name: 'Indie Spotlight', desc: 'Discovered GOYA HicoSoft Studio first', rarity: 'Rare' },
        { id: 'metroid', icon: '🛸', name: 'Metroid Hunter', desc: 'Pre-ordered Metroid Ravenous Switch 2', rarity: 'Rare' },
        { id: 'comiccon', icon: '🎟️', name: 'GCC Dzaïr Pass', desc: 'Cosplay showcase participant 2026', rarity: 'Epic' },
      ],
      savedArticlesList: [
        { id: 'metroid', title: 'Metroid Ravenous: First Look on Switch 2', category: 'NEWS / NINTENDO', readTime: '4 MIN READ', link: '/news/metroid-ravenous' },
        { id: 'goya', title: 'HicoSoft Studio: The Making of GOYA RPG in Algeria', category: 'DOSSIER / STUDIO', readTime: '8 MIN READ', link: '/dossiers/goya-hicosoft' },
        { id: 'awards', title: 'Let’s Play Awards 2025: Game of the Year Recap', category: 'DOSSIER / AWARDS', readTime: '7 MIN READ', link: '/dossiers/let-play-awards-2025' },
      ],
    },
  },
};
